numprocs=80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch13/v5_batch13_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py

Start time:  2021-07-21 21:08:02.336975
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py
Importing netParams from ../data/v5_batch13/v5_batch13_netParams.py

Creating network of 61 cell populations on 80 hosts...
  Number of cells on node 26: 483 
  Number of cells on node 62: 482 
  Number of cells on node 35: 483 
  Number of cells on node 28: 483 
  Number of cells on node 20: 483 
  Number of cells on node 15: 483 
  Number of cells on node 19: 483 
  Number of cells on node 42: 483 
  Number of cells on node 45: 483 
  Number of cells on node 17: 483 
  Number of cells on node 64: 482 
  Number of cells on node 3: 483 
  Number of cells on node 31: 483 
  Number of cells on node 38: 483 
  Number of cells on node 46: 483 
  Number of cells on node 51: 483 
  Number of cells on node 6: 483 
  Number of cells on node 48: 483 
  Number of cells on node 8: 483 
  Number of cells on node 9: 483 
  Number of cells on node 33: 483 
  Number of cells on node 69: 482 
  Number of cells on node 2: 483 
  Number of cells on node 56: 482 
  Number of cells on node 25: 483 
  Number of cells on node 21: 483 
  Number of cells on node 70: 482 
  Number of cells on node 73: 482 
  Number of cells on node 1: 483 
  Number of cells on node 37: 483 
  Number of cells on node 41: 483 
  Number of cells on node 5: 483 
  Number of cells on node 72: 482 
  Number of cells on node 7: 483 
  Number of cells on node 61: 482 
  Number of cells on node 63: 482 
  Number of cells on node 78: 482 
  Number of cells on node 50: 483 
  Number of cells on node 49: 483 
  Number of cells on node 57: 482 
  Number of cells on node 4: 483 
  Number of cells on node 79: 482 
  Number of cells on node 43: 483 
  Number of cells on node 40: 483 
  Number of cells on node 39: 483 
  Number of cells on node 68: 482 
  Number of cells on node 54: 482 
  Number of cells on node 12: 483 
  Number of cells on node 36: 483 
  Number of cells on node 29: 483 
  Number of cells on node 0: 483 
  Done; cell creation time = 29.00 s.
Making connections...
  Number of cells on node 66: 482 
  Number of cells on node 34: 483 
  Number of cells on node 13: 483 
  Number of cells on node 16: 483 
  Number of cells on node 55: 482 
  Number of cells on node 32: 483 
  Number of cells on node 24: 483 
  Number of cells on node 74: 482 
  Number of cells on node 71: 482 
  Number of cells on node 10: 483 
  Number of cells on node 18: 483 
  Number of cells on node 65: 482 
  Number of cells on node 11: 483 
  Number of cells on node 75: 482 
  Number of cells on node 58: 482 
  Number of cells on node 77: 482 
  Number of cells on node 44: 483 
  Number of cells on node 53: 482 
  Number of cells on node 30: 483 
  Number of cells on node 67: 482 
  Number of cells on node 76: 482 
  Number of cells on node 47: 483 
  Number of cells on node 14: 483 
  Number of cells on node 27: 483 
  Number of cells on node 52: 482 
  Number of cells on node 23: 483 
  Number of cells on node 60: 482 
  Number of cells on node 22: 483 
  Number of cells on node 59: 482 
  Number of connections on node 72: 119444 
  Number of synaptic contacts on node 72: 1271538 
  Number of connections on node 46: 118009 
  Number of synaptic contacts on node 46: 1266323 
  Number of connections on node 32: 116603 
  Number of synaptic contacts on node 32: 1238346 
  Number of connections on node 52: 120166 
  Number of synaptic contacts on node 52: 1280635 
  Number of connections on node 70: 120085 
  Number of synaptic contacts on node 70: 1282468 
  Number of connections on node 30: 118402 
  Number of synaptic contacts on node 30: 1266540 
  Number of connections on node 68: 120134 
  Number of synaptic contacts on node 68: 1274170 
  Number of connections on node 76: 121672 
  Number of synaptic contacts on node 76: 1294024 
  Number of connections on node 62: 118333 
  Number of synaptic contacts on node 62: 1257897 
  Number of connections on node 44: 119972 
  Number of synaptic contacts on node 44: 1279749 
  Number of connections on node 16: 119285 
  Number of synaptic contacts on node 16: 1269344 
  Number of connections on node 8: 119918 
  Number of synaptic contacts on node 8: 1278066 
  Number of connections on node 58: 120150 
  Number of synaptic contacts on node 58: 1279783 
  Number of connections on node 12: 119053 
  Number of synaptic contacts on node 12: 1269631 
  Number of connections on node 22: 117316 
  Number of synaptic contacts on node 22: 1256766 
  Number of connections on node 60: 119016 
  Number of synaptic contacts on node 60: 1270014 
  Number of connections on node 42: 119526 
  Number of synaptic contacts on node 42: 1270100 
  Number of connections on node 33: 119882 
  Number of synaptic contacts on node 33: 1283530 
  Number of connections on node 38: 118363 
  Number of synaptic contacts on node 38: 1263748 
  Number of connections on node 26: 118051 
  Number of synaptic contacts on node 26: 1267679 
  Number of connections on node 64: 120233 
  Number of synaptic contacts on node 64: 1280660 
  Number of connections on node 4: 119634 
  Number of synaptic contacts on node 4: 1276516 
  Number of connections on node 28: 119099 
  Number of synaptic contacts on node 28: 1266433 
  Number of connections on node 66: 118799 
  Number of synaptic contacts on node 66: 1262171 
  Number of connections on node 6: 118300 
  Number of synaptic contacts on node 6: 1265246 
  Number of connections on node 74: 120058 
  Number of synaptic contacts on node 74: 1272317 
  Number of connections on node 24: 120763 
  Number of synaptic contacts on node 24: 1291024 
  Number of connections on node 36: 120118 
  Number of synaptic contacts on node 36: 1283306 
  Number of connections on node 50: 117281 
  Number of synaptic contacts on node 50: 1257609 
  Number of connections on node 0: 119145 
  Number of synaptic contacts on node 0: 1271026 
  Number of connections on node 2: 119501 
  Number of synaptic contacts on node 2: 1278591 
  Number of connections on node 14: 118949 
  Number of synaptic contacts on node 14: 1271136 
  Number of connections on node 20: 118325 
  Number of synaptic contacts on node 20: 1257785 
  Number of connections on node 79: 119579 
  Number of synaptic contacts on node 79: 1272421 
  Number of connections on node 63: 120395 
  Number of synaptic contacts on node 63: 1278745 
  Number of connections on node 7: 120385 
  Number of synaptic contacts on node 7: 1283488 
  Number of connections on node 78: 119296 
  Number of synaptic contacts on node 78: 1270348 
  Number of connections on node 57: 120789 
  Number of synaptic contacts on node 57: 1291067 
  Number of connections on node 18: 119177 
  Number of synaptic contacts on node 18: 1260243 
  Number of connections on node 21: 120101 
  Number of synaptic contacts on node 21: 1275178 
  Number of connections on node 25: 119470 
  Number of synaptic contacts on node 25: 1279980 
  Number of connections on node 54: 120258 
  Number of synaptic contacts on node 54: 1283196 
  Number of connections on node 41: 119525 
  Number of synaptic contacts on node 41: 1276469 
  Number of connections on node 77: 121084 
  Number of synaptic contacts on node 77: 1290946 
  Number of connections on node 11: 119880 
  Number of synaptic contacts on node 11: 1274668 
  Number of connections on node 10: 120119 
  Number of synaptic contacts on node 10: 1283022 
  Number of connections on node 59: 120444 
  Number of synaptic contacts on node 59: 1283912 
  Number of connections on node 43: 120032 
  Number of synaptic contacts on node 43: 1279158 
  Number of connections on node 69: 118111 
  Number of synaptic contacts on node 69: 1256211 
  Number of connections on node 19: 119105 
  Number of synaptic contacts on node 19: 1265748 
  Number of connections on node 13: 118258 
  Number of synaptic contacts on node 13: 1257084 
  Number of connections on node 53: 120287 
  Number of synaptic contacts on node 53: 1284799 
  Number of connections on node 27: 118988 
  Number of synaptic contacts on node 27: 1273248 
  Number of connections on node 15: 118282 
  Number of synaptic contacts on node 15: 1256770 
  Number of connections on node 51: 120466 
  Number of synaptic contacts on node 51: 1282265 
  Number of connections on node 1: 119494 
  Number of synaptic contacts on node 1: 1273101 
  Number of connections on node 61: 119077 
  Number of synaptic contacts on node 61: 1264455 
  Number of connections on node 3: 117589 
  Number of synaptic contacts on node 3: 1252457 
  Number of connections on node 47: 120391 
  Number of synaptic contacts on node 47: 1284859 
  Number of connections on node 40: 120869 
  Number of synaptic contacts on node 40: 1290119 
  Number of connections on node 48: 119136 
  Number of synaptic contacts on node 48: 1278403 
  Number of connections on node 31: 118062 
  Number of synaptic contacts on node 31: 1259242 
  Number of connections on node 75: 121598 
  Number of synaptic contacts on node 75: 1297101 
  Number of connections on node 9: 119526 
  Number of synaptic contacts on node 9: 1271669 
  Number of connections on node 37: 121151 
  Number of synaptic contacts on node 37: 1293601 
  Number of connections on node 56: 119459 
  Number of synaptic contacts on node 56: 1273226 
  Number of connections on node 34: 118965 
  Number of synaptic contacts on node 34: 1272749 
  Number of connections on node 55: 119738 
  Number of synaptic contacts on node 55: 1276830 
  Number of connections on node 5: 116872 
  Number of synaptic contacts on node 5: 1246696 
  Number of connections on node 45: 120263 
  Number of synaptic contacts on node 45: 1286546 
  Number of connections on node 65: 118741 
  Number of synaptic contacts on node 65: 1261081 
  Number of connections on node 49: 118739 
  Number of synaptic contacts on node 49: 1270761 
  Number of connections on node 17: 119166 
  Number of synaptic contacts on node 17: 1264663 
  Number of connections on node 35: 117460 
  Number of synaptic contacts on node 35: 1248694 
  Number of connections on node 73: 120930 
  Number of synaptic contacts on node 73: 1296253 
  Number of connections on node 67: 121488 
  Number of synaptic contacts on node 67: 1289595 
  Number of connections on node 23: 120048 
  Number of synaptic contacts on node 23: 1278530 
  Number of connections on node 39: 118462 
  Number of synaptic contacts on node 39: 1260808 
  Number of connections on node 71: 117003 
  Number of synaptic contacts on node 71: 1246562 
  Number of connections on node 29: 119336 
  Number of synaptic contacts on node 29: 1271355 
  Done; cell connection time = 19916.57 s.
Adding stims...
  Number of stims on node 14: 3973 
  Number of stims on node 10: 3973 
  Number of stims on node 28: 3974 
  Number of stims on node 50: 3974 
  Number of stims on node 25: 3974 
  Number of stims on node 4: 3973 
  Number of stims on node 78: 3963 
  Number of stims on node 34: 3974 
  Number of stims on node 72: 3963 
  Number of stims on node 8: 3973 
  Number of stims on node 55: 3973 
  Number of stims on node 58: 3973 
  Number of stims on node 29: 3974 
  Number of stims on node 33: 3974 
  Number of stims on node 5: 3973 
  Number of stims on node 9: 3973 
  Number of stims on node 63: 3973 
  Number of stims on node 51: 3974 
  Number of stims on node 79: 3963 
  Number of stims on node 23: 3974 
  Number of stims on node 15: 3973 
  Number of stims on node 73: 3963 
  Number of stims on node 76: 3963 
  Number of stims on node 24: 3974 
  Number of stims on node 19: 3973 
  Number of stims on node 18: 3973 
  Number of stims on node 37: 3974 
  Number of stims on node 36: 3974 
  Number of stims on node 77: 3963 
  Number of stims on node 59: 3973 
  Number of stims on node 21: 3974 
  Number of stims on node 42: 3974 
  Number of stims on node 48: 3974 
  Number of stims on node 71: 3963 
  Number of stims on node 49: 3974 
  Number of stims on node 17: 3973 
  Number of stims on node 70: 3963 
  Number of stims on node 61: 3973 
  Number of stims on node 22: 3974 
  Number of stims on node 56: 3973 
  Number of stims on node 6: 3973 
  Number of stims on node 31: 3974 
  Number of stims on node 67: 3963 
  Number of stims on node 46: 3974 
  Number of stims on node 44: 3974 
  Number of stims on node 39: 3974 
  Number of stims on node 30: 3974 
  Number of stims on node 3: 3973 
  Number of stims on node 60: 3973 
  Number of stims on node 2: 3973 
  Number of stims on node 74: 3963 
  Number of stims on node 32: 3974 
  Number of stims on node 41: 3974 
  Number of stims on node 26: 3974 
  Number of stims on node 65: 3973 
  Number of stims on node 43: 3974 
  Number of stims on node 7: 3973 
  Number of stims on node 20: 3973 
  Number of stims on node 13: 3973 
  Number of stims on node 35: 3974 
  Number of stims on node 64: 3973 
  Number of stims on node 52: 3973 
  Number of stims on node 0: 3973 
  Number of stims on node 66: 3963 
  Number of stims on node 45: 3974 
  Number of stims on node 47: 3974 
  Number of stims on node 12: 3973 
  Number of stims on node 69: 3963 
  Number of stims on node 1: 3973 
  Number of stims on node 62: 3973 
  Number of stims on node 16: 3973 
  Number of stims on node 53: 3973 
  Number of stims on node 57: 3973 
  Number of stims on node 27: 3974 
  Number of stims on node 75: 3963 
  Number of stims on node 11: 3973 
  Number of stims on node 38: 3974 
  Number of stims on node 68: 3963 
  Number of stims on node 54: 3973 
  Number of stims on node 40: 3974 
  Done; cell stims creation time = 11.18 s.
Recording 16 traces of 1 types on node 70
Recording 12 traces of 1 types on node 2
Recording 12 traces of 1 types on node 74
Recording 11 traces of 1 types on node 30
Recording 11 traces of 1 types on node 32
Recording 16 traces of 1 types on node 46
Recording 13 traces of 1 types on node 12
Recording 15 traces of 1 types on node 52
Recording 15 traces of 1 types on node 38
Recording 14 traces of 1 types on node 51
Recording 14 traces of 1 types on node 58
Recording 16 traces of 1 types on node 54
Recording 12 traces of 1 types on node 50
Recording 13 traces of 1 types on node 78
Recording 19 traces of 1 types on node 31
Recording 17 traces of 1 types on node 66
Recording 13 traces of 1 types on node 25
Recording 15 traces of 1 types on node 28
Recording 10 traces of 1 types on node 37
Recording 8 traces of 1 types on node 69
Recording 17 traces of 1 types on node 22
Recording 14 traces of 1 types on node 23
Recording 10 traces of 1 types on node 6
Recording 18 traces of 1 types on node 11
Recording 8 traces of 1 types on node 19
Recording 16 traces of 1 types on node 55
Recording 14 traces of 1 types on node 27
Recording 15 traces of 1 types on node 14
Recording 12 traces of 1 types on node 33
Recording 12 traces of 1 types on node 68
Recording 15 traces of 1 types on node 35
Recording 17 traces of 1 types on node 49
Recording 10 traces of 1 types on node 53
Recording 9 traces of 1 types on node 63
Recording 16 traces of 1 types on node 57
Recording 10 traces of 1 types on node 13
Recording 14 traces of 1 types on node 4
Recording 11 traces of 1 types on node 61
Recording 13 traces of 1 types on node 73
Recording 15 traces of 1 types on node 62
Recording 12 traces of 1 types on node 56
Recording 10 traces of 1 types on node 59
Recording 16 traces of 1 types on node 5
Recording 10 traces of 1 types on node 1
Recording 11 traces of 1 types on node 21
Recording 4 traces of 1 types on node 79
Recording 15 traces of 1 types on node 40
Recording 15 traces of 1 types on node 45
Recording 10 traces of 1 types on node 10
Recording 11 traces of 1 types on node 36
Recording 11 traces of 1 types on node 9
Recording 14 traces of 1 types on node 20
Recording 15 traces of 1 types on node 29
Recording 9 traces of 1 types on node 24
Recording 13 traces of 1 types on node 3
Recording 11 traces of 1 types on node 15
Recording 12 traces of 1 types on node 39
Recording 15 traces of 1 types on node 76
Recording 16 traces of 1 types on node 67
Recording 9 traces of 1 types on node 8
Recording 14 traces of 1 types on node 18
Recording 9 traces of 1 types on node 17
Recording 7 traces of 1 types on node 41
Recording 14 traces of 1 types on node 48
Recording 8 traces of 1 types on node 71
Recording 7 traces of 1 types on node 47
Recording 17 traces of 1 types on node 42
Recording 11 traces of 1 types on node 34
Recording 6 traces of 1 types on node 65
Recording 18 traces of 1 types on node 72
Recording 14 traces of 1 types on node 0
Recording 8 traces of 1 types on node 7
Recording 12 traces of 1 types on node 44
Recording 9 traces of 1 types on node 77
Recording 16 traces of 1 types on node 60
Recording 17 traces of 1 types on node 16
Recording 16 traces of 1 types on node 26
Recording 10 traces of 1 types on node 43
Recording 10 traces of 1 types on node 75
Recording 17 traces of 1 types on node 64
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 48474.01 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 16.82 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 236742 (3.07 Hz)
  Simulated time: 2.0 s; 80 workers
  Run time: 48474.01 s
   L1_DAC : 0.103 Hz
   L1_DLAC : 0.062 Hz
   L1_HAC : 0.071 Hz
   L1_NGC-DA : 0.403 Hz
   L1_NGC-SA : 0.490 Hz
   L1_SLAC : 0.512 Hz
   L23_BP : 7.339 Hz
   L23_BTC : 1.202 Hz
   L23_ChC : 1.238 Hz
   L23_DBC : 4.337 Hz
   L23_LBC : 1.458 Hz
   L23_MC : 0.578 Hz
   L23_NBC : 0.819 Hz
   L23_NGC : 1.438 Hz
   L23_PC : 1.031 Hz
   L23_SBC : 2.401 Hz
   L4_BP : 10.562 Hz
   L4_BTC : 2.200 Hz
   L4_ChC : 1.812 Hz
   L4_DBC : 3.150 Hz
   L4_LBC : 2.459 Hz
   L4_MC : 0.898 Hz
   L4_NBC : 3.078 Hz
   L4_NGC : 2.333 Hz
   L4_PC : 1.809 Hz
   L4_SBC : 3.200 Hz
   L4_SP : 1.969 Hz
   L4_SS : 1.653 Hz
   L5_BP : 10.294 Hz
   L5_BTC : 2.421 Hz
   L5_ChC : 2.658 Hz
   L5_DBC : 2.880 Hz
   L5_LBC : 3.112 Hz
   L5_MC : 2.030 Hz
   L5_NBC : 4.376 Hz
   L5_NGC : 4.250 Hz
   L5_SBC : 3.820 Hz
   L5_STPC : 2.560 Hz
   L5_TTPC1 : 2.866 Hz
   L5_TTPC2 : 2.408 Hz
   L5_UTPC : 2.909 Hz
   L6_BPC : 2.047 Hz
   L6_BP : 5.064 Hz
   L6_BTC : 3.102 Hz
   L6_ChC : 2.344 Hz
   L6_DBC : 3.290 Hz
   L6_IPC : 1.428 Hz
   L6_LBC : 5.672 Hz
   L6_MC : 1.455 Hz
   L6_NBC : 4.866 Hz
   L6_NGC : 3.412 Hz
   L6_SBC : 5.716 Hz
   L6_TPC_L1 : 1.651 Hz
   L6_TPC_L4 : 1.684 Hz
   L6_UTPC : 1.759 Hz
   ss_RTN_o : 10.650 Hz
   ss_RTN_m : 12.173 Hz
   ss_RTN_i : 10.677 Hz
   VPL_sTC : 5.224 Hz
   VPM_sTC : 5.634 Hz
   POm_sTC_s1 : 7.436 Hz
Saving output as ../data/v5_batch13/v5_batch13_0_0.json  ... 
Finished saving!
  Done; saving time = 34.81 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 397.71 s

Total time = 68933.84 s

End time:  2021-07-22 16:16:56.172733
