numprocs=224

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 7: 178 
  Number of connections on node 7: 2800 
  Number of synaptic contacts on node 7: 16748 
  Number of stims on node 7: 50 
Recording 5 traces of 1 types on node 7

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 9: 178 
  Number of connections on node 9: 2648 
  Number of synaptic contacts on node 9: 16952 
  Number of stims on node 9: 50 
Recording 5 traces of 1 types on node 9

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 11: 178 
  Number of connections on node 11: 2751 
  Number of synaptic contacts on node 11: 17396 
  Number of stims on node 11: 50 
Recording 5 traces of 1 types on node 11

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 13: 178 
  Number of connections on node 13: 2700 
  Number of synaptic contacts on node 13: 17170 
  Number of stims on node 13: 50 
Recording 5 traces of 1 types on node 13

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 16: 178 
  Number of connections on node 16: 2686 
  Number of synaptic contacts on node 16: 16889 
  Number of stims on node 16: 50 
Recording 5 traces of 1 types on node 16

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 17: 178 
  Number of connections on node 17: 2695 
  Number of synaptic contacts on node 17: 16773 
  Number of stims on node 17: 50 
Recording 5 traces of 1 types on node 17

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 24: 178 
  Number of connections on node 24: 2706 
  Number of synaptic contacts on node 24: 17253 
  Number of stims on node 24: 50 
Recording 5 traces of 1 types on node 24

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 28: 178 
  Number of connections on node 28: 2687 
  Number of synaptic contacts on node 28: 16934 
  Number of stims on node 28: 50 
Recording 5 traces of 1 types on node 28

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 30: 178 
  Number of connections on node 30: 2777 
  Number of synaptic contacts on node 30: 17657 
  Number of stims on node 30: 50 
Recording 5 traces of 1 types on node 30

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 31: 178 
  Number of connections on node 31: 2799 
  Number of synaptic contacts on node 31: 17772 
  Number of stims on node 31: 50 
Recording 5 traces of 1 types on node 31

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 32: 178 
  Number of connections on node 32: 2765 
  Number of synaptic contacts on node 32: 17585 
  Number of stims on node 32: 50 
Recording 5 traces of 1 types on node 32

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 33: 178 
  Number of connections on node 33: 2797 
  Number of synaptic contacts on node 33: 17595 
  Number of stims on node 33: 50 
Recording 5 traces of 1 types on node 33

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 35: 178 
  Number of connections on node 35: 2766 
  Number of synaptic contacts on node 35: 17103 
  Number of stims on node 35: 50 
Recording 5 traces of 1 types on node 35

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 36: 178 
  Number of connections on node 36: 2730 
  Number of synaptic contacts on node 36: 17374 
  Number of stims on node 36: 50 
Recording 5 traces of 1 types on node 36

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 39: 178 
  Number of connections on node 39: 2679 
  Number of synaptic contacts on node 39: 16911 
  Number of stims on node 39: 50 
Recording 5 traces of 1 types on node 39

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 41: 178 
  Number of connections on node 41: 2694 
  Number of synaptic contacts on node 41: 16963 
  Number of stims on node 41: 50 
Recording 5 traces of 1 types on node 41

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 42: 178 
  Number of connections on node 42: 2762 
  Number of synaptic contacts on node 42: 17766 
  Number of stims on node 42: 50 
Recording 5 traces of 1 types on node 42

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 43: 178 
  Number of connections on node 43: 2777 
  Number of synaptic contacts on node 43: 17622 
  Number of stims on node 43: 50 
Recording 5 traces of 1 types on node 43

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 48: 178 
  Number of connections on node 48: 2651 
  Number of synaptic contacts on node 48: 16268 
  Number of stims on node 48: 50 
Recording 5 traces of 1 types on node 48

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 49: 178 
  Number of connections on node 49: 2768 
  Number of synaptic contacts on node 49: 17095 
  Number of stims on node 49: 50 
Recording 5 traces of 1 types on node 49

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 50: 178 
  Number of connections on node 50: 2770 
  Number of synaptic contacts on node 50: 17363 
  Number of stims on node 50: 50 
Recording 5 traces of 1 types on node 50

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 51: 178 
  Number of connections on node 51: 2808 
  Number of synaptic contacts on node 51: 17600 
  Number of stims on node 51: 50 
Recording 5 traces of 1 types on node 51

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 54: 178 
  Number of connections on node 54: 2988 
  Number of synaptic contacts on node 54: 17554 
  Number of stims on node 54: 50 
Recording 5 traces of 1 types on node 54

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 58: 178 
  Number of connections on node 58: 3012 
  Number of synaptic contacts on node 58: 18166 
  Number of stims on node 58: 50 
Recording 5 traces of 1 types on node 58

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 59: 178 
  Number of connections on node 59: 2999 
  Number of synaptic contacts on node 59: 18309 
  Number of stims on node 59: 50 
Recording 5 traces of 1 types on node 59

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 62: 178 
  Number of connections on node 62: 2988 
  Number of synaptic contacts on node 62: 17839 
  Number of stims on node 62: 50 
Recording 5 traces of 1 types on node 62

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 63: 178 
  Number of connections on node 63: 2959 
  Number of synaptic contacts on node 63: 17950 
  Number of stims on node 63: 50 
Recording 5 traces of 1 types on node 63

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 64: 178 
  Number of connections on node 64: 3119 
  Number of synaptic contacts on node 64: 18496 
  Number of stims on node 64: 50 
Recording 5 traces of 1 types on node 64

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 65: 178 
  Number of connections on node 65: 3039 
  Number of synaptic contacts on node 65: 18084 
  Number of stims on node 65: 50 
Recording 5 traces of 1 types on node 65

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 67: 178 
  Number of connections on node 67: 3014 
  Number of synaptic contacts on node 67: 18169 
  Number of stims on node 67: 50 
Recording 5 traces of 1 types on node 67

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 68: 178 
  Number of connections on node 68: 3007 
  Number of synaptic contacts on node 68: 17693 
  Number of stims on node 68: 50 
Recording 5 traces of 1 types on node 68

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 69: 178 
  Number of connections on node 69: 2893 
  Number of synaptic contacts on node 69: 17545 
  Number of stims on node 69: 50 
Recording 5 traces of 1 types on node 69

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 70: 178 
  Number of connections on node 70: 3016 
  Number of synaptic contacts on node 70: 17821 
  Number of stims on node 70: 50 
Recording 5 traces of 1 types on node 70

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 71: 178 
  Number of connections on node 71: 3015 
  Number of synaptic contacts on node 71: 17802 
  Number of stims on node 71: 50 
Recording 5 traces of 1 types on node 71

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 72: 178 
  Number of connections on node 72: 2952 
  Number of synaptic contacts on node 72: 17744 
  Number of stims on node 72: 50 
Recording 5 traces of 1 types on node 72

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 73: 178 
  Number of connections on node 73: 3043 
  Number of synaptic contacts on node 73: 18330 
  Number of stims on node 73: 50 
Recording 5 traces of 1 types on node 73

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 74: 178 
  Number of connections on node 74: 2987 
  Number of synaptic contacts on node 74: 18073 
  Number of stims on node 74: 50 
Recording 5 traces of 1 types on node 74

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 75: 178 
  Number of connections on node 75: 2571 
  Number of synaptic contacts on node 75: 16194 
  Number of stims on node 75: 50 
Recording 5 traces of 1 types on node 75

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 76: 178 
  Number of connections on node 76: 2595 
  Number of synaptic contacts on node 76: 16721 
  Number of stims on node 76: 50 
Recording 5 traces of 1 types on node 76

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 77: 178 
  Number of connections on node 77: 2616 
  Number of synaptic contacts on node 77: 16652 
  Number of stims on node 77: 50 
Recording 5 traces of 1 types on node 77

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 79: 178 
  Number of connections on node 79: 2537 
  Number of synaptic contacts on node 79: 16011 
  Number of stims on node 79: 50 
Recording 5 traces of 1 types on node 79

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 80: 178 
  Number of connections on node 80: 2597 
  Number of synaptic contacts on node 80: 16313 
  Number of stims on node 80: 50 
Recording 5 traces of 1 types on node 80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 81: 178 
  Number of connections on node 81: 2666 
  Number of synaptic contacts on node 81: 17256 
  Number of stims on node 81: 50 
Recording 5 traces of 1 types on node 81

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 82: 178 
  Number of connections on node 82: 2741 
  Number of synaptic contacts on node 82: 18011 
  Number of stims on node 82: 50 
Recording 5 traces of 1 types on node 82

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 83: 178 
  Number of connections on node 83: 2701 
  Number of synaptic contacts on node 83: 17978 
  Number of stims on node 83: 50 
Recording 5 traces of 1 types on node 83

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 84: 178 
  Number of connections on node 84: 2831 
  Number of synaptic contacts on node 84: 18769 
  Number of stims on node 84: 60 
Recording 6 traces of 1 types on node 84

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 85: 178 
  Number of connections on node 85: 2699 
  Number of synaptic contacts on node 85: 17705 
  Number of stims on node 85: 60 
Recording 6 traces of 1 types on node 85

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 86: 178 
  Number of connections on node 86: 2709 
  Number of synaptic contacts on node 86: 17631 
  Number of stims on node 86: 60 
Recording 6 traces of 1 types on node 86

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 88: 178 
  Number of connections on node 88: 2615 
  Number of synaptic contacts on node 88: 17149 
  Number of stims on node 88: 60 
Recording 6 traces of 1 types on node 88

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 89: 178 
  Number of connections on node 89: 2589 
  Number of synaptic contacts on node 89: 16467 
  Number of stims on node 89: 60 
Recording 6 traces of 1 types on node 89

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 90: 178 
  Number of connections on node 90: 2638 
  Number of synaptic contacts on node 90: 16916 
  Number of stims on node 90: 60 
Recording 6 traces of 1 types on node 90

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 91: 178 
  Number of connections on node 91: 2709 
  Number of synaptic contacts on node 91: 17202 
  Number of stims on node 91: 60 
Recording 6 traces of 1 types on node 91

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 92: 178 
  Number of connections on node 92: 2604 
  Number of synaptic contacts on node 92: 16701 
  Number of stims on node 92: 60 
Recording 6 traces of 1 types on node 92

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 93: 178 
  Number of connections on node 93: 2622 
  Number of synaptic contacts on node 93: 16900 
  Number of stims on node 93: 60 
Recording 6 traces of 1 types on node 93

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 94: 178 
  Number of connections on node 94: 2563 
  Number of synaptic contacts on node 94: 16277 
  Number of stims on node 94: 60 
Recording 6 traces of 1 types on node 94

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 95: 178 
  Number of connections on node 95: 2867 
  Number of synaptic contacts on node 95: 17581 
  Number of stims on node 95: 60 
Recording 6 traces of 1 types on node 95

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 96: 178 
  Number of connections on node 96: 2599 
  Number of synaptic contacts on node 96: 16748 
  Number of stims on node 96: 60 
Recording 6 traces of 1 types on node 96

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 98: 178 
  Number of connections on node 98: 2651 
  Number of synaptic contacts on node 98: 17055 
  Number of stims on node 98: 60 
Recording 6 traces of 1 types on node 98

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 99: 178 
  Number of connections on node 99: 2810 
  Number of synaptic contacts on node 99: 17436 
  Number of stims on node 99: 60 
Recording 6 traces of 1 types on node 99

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 100: 178 
  Number of connections on node 100: 2926 
  Number of synaptic contacts on node 100: 17927 
  Number of stims on node 100: 60 
Recording 6 traces of 1 types on node 100

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 101: 178 
  Number of connections on node 101: 2841 
  Number of synaptic contacts on node 101: 17850 
  Number of stims on node 101: 60 
Recording 6 traces of 1 types on node 101

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 102: 178 
  Number of connections on node 102: 2771 
  Number of synaptic contacts on node 102: 16999 
  Number of stims on node 102: 60 
Recording 6 traces of 1 types on node 102

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 103: 178 
  Number of connections on node 103: 3005 
  Number of synaptic contacts on node 103: 19126 
  Number of stims on node 103: 60 
Recording 6 traces of 1 types on node 103

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 104: 178 
  Number of connections on node 104: 2895 
  Number of synaptic contacts on node 104: 18048 
  Number of stims on node 104: 60 
Recording 6 traces of 1 types on node 104

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 105: 178 
  Number of connections on node 105: 2930 
  Number of synaptic contacts on node 105: 18908 
  Number of stims on node 105: 60 
Recording 6 traces of 1 types on node 105

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 106: 178 
  Number of connections on node 106: 2912 
  Number of synaptic contacts on node 106: 18312 
  Number of stims on node 106: 60 
Recording 6 traces of 1 types on node 106

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 107: 178 
  Number of connections on node 107: 2987 
  Number of synaptic contacts on node 107: 19067 
  Number of stims on node 107: 60 
Recording 6 traces of 1 types on node 107

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 108: 178 
  Number of connections on node 108: 3000 
  Number of synaptic contacts on node 108: 19124 
  Number of stims on node 108: 60 
Recording 6 traces of 1 types on node 108

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 109: 178 
  Number of connections on node 109: 3024 
  Number of synaptic contacts on node 109: 19405 
  Number of stims on node 109: 60 
Recording 6 traces of 1 types on node 109

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 110: 178 
  Number of connections on node 110: 3075 
  Number of synaptic contacts on node 110: 19999 
  Number of stims on node 110: 60 
Recording 6 traces of 1 types on node 110

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 111: 178 
  Number of connections on node 111: 3024 
  Number of synaptic contacts on node 111: 19416 
  Number of stims on node 111: 60 
Recording 6 traces of 1 types on node 111

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 112: 178 
  Number of connections on node 112: 3074 
  Number of synaptic contacts on node 112: 19338 
  Number of stims on node 112: 60 
Recording 6 traces of 1 types on node 112

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 113: 178 
  Number of connections on node 113: 3148 
  Number of synaptic contacts on node 113: 19950 
  Number of stims on node 113: 60 
Recording 6 traces of 1 types on node 113

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 114: 178 
  Number of connections on node 114: 3014 
  Number of synaptic contacts on node 114: 19029 
  Number of stims on node 114: 60 
Recording 6 traces of 1 types on node 114

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 115: 178 
  Number of connections on node 115: 3089 
  Number of synaptic contacts on node 115: 19272 
  Number of stims on node 115: 60 
Recording 6 traces of 1 types on node 115

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 116: 178 
  Number of connections on node 116: 3087 
  Number of synaptic contacts on node 116: 19327 
  Number of stims on node 116: 60 
Recording 6 traces of 1 types on node 116

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 118: 178 
  Number of connections on node 118: 3044 
  Number of synaptic contacts on node 118: 19201 
  Number of stims on node 118: 60 
Recording 6 traces of 1 types on node 118

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 119: 178 
  Number of connections on node 119: 3102 
  Number of synaptic contacts on node 119: 19270 
  Number of stims on node 119: 60 
Recording 6 traces of 1 types on node 119

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 120: 178 
  Number of connections on node 120: 3028 
  Number of synaptic contacts on node 120: 18779 
  Number of stims on node 120: 60 
Recording 6 traces of 1 types on node 120

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 121: 178 
  Number of connections on node 121: 2969 
  Number of synaptic contacts on node 121: 18416 
  Number of stims on node 121: 60 
Recording 6 traces of 1 types on node 121

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 122: 178 
  Number of connections on node 122: 2998 
  Number of synaptic contacts on node 122: 18848 
  Number of stims on node 122: 60 
Recording 6 traces of 1 types on node 122

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 123: 178 
  Number of connections on node 123: 3036 
  Number of synaptic contacts on node 123: 18975 
  Number of stims on node 123: 60 
Recording 6 traces of 1 types on node 123

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 124: 178 
  Number of connections on node 124: 2970 
  Number of synaptic contacts on node 124: 18447 
  Number of stims on node 124: 60 
Recording 6 traces of 1 types on node 124

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 125: 178 
  Number of connections on node 125: 3057 
  Number of synaptic contacts on node 125: 19125 
  Number of stims on node 125: 60 
Recording 6 traces of 1 types on node 125

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 126: 178 
  Number of connections on node 126: 3066 
  Number of synaptic contacts on node 126: 18817 
  Number of stims on node 126: 60 
Recording 6 traces of 1 types on node 126

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 127: 178 
  Number of connections on node 127: 3101 
  Number of synaptic contacts on node 127: 19486 
  Number of stims on node 127: 60 
Recording 6 traces of 1 types on node 127

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 1: 179 
  Number of connections on node 1: 3416 
  Number of synaptic contacts on node 1: 19573 
  Number of stims on node 1: 60 
Recording 6 traces of 1 types on node 1

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 2: 179 
  Number of connections on node 2: 3404 
  Number of synaptic contacts on node 2: 19501 
  Number of stims on node 2: 60 
Recording 6 traces of 1 types on node 2

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 3: 179 
  Number of connections on node 3: 3366 
  Number of synaptic contacts on node 3: 19298 
  Number of stims on node 3: 60 
Recording 6 traces of 1 types on node 3

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 4: 178 
  Number of connections on node 4: 2757 
  Number of synaptic contacts on node 4: 16754 
  Number of stims on node 4: 50 
Recording 5 traces of 1 types on node 4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 5: 178 
  Number of connections on node 5: 2686 
  Number of synaptic contacts on node 5: 16207 
  Number of stims on node 5: 50 
Recording 5 traces of 1 types on node 5

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 6: 178 
  Number of connections on node 6: 2749 
  Number of synaptic contacts on node 6: 16740 
  Number of stims on node 6: 50 
Recording 5 traces of 1 types on node 6

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 8: 178 
  Number of connections on node 8: 2744 
  Number of synaptic contacts on node 8: 16465 
  Number of stims on node 8: 50 
Recording 5 traces of 1 types on node 8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 10: 178 
  Number of connections on node 10: 2667 
  Number of synaptic contacts on node 10: 16888 
  Number of stims on node 10: 50 
Recording 5 traces of 1 types on node 10

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 12: 178 
  Number of connections on node 12: 2818 
  Number of synaptic contacts on node 12: 17982 
  Number of stims on node 12: 50 
Recording 5 traces of 1 types on node 12

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 14: 178 
  Number of connections on node 14: 2792 
  Number of synaptic contacts on node 14: 17629 
  Number of stims on node 14: 50 
Recording 5 traces of 1 types on node 14

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 15: 178 
  Number of connections on node 15: 2729 
  Number of synaptic contacts on node 15: 17089 
  Number of stims on node 15: 50 
Recording 5 traces of 1 types on node 15

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 18: 178 
  Number of connections on node 18: 2703 
  Number of synaptic contacts on node 18: 17677 
  Number of stims on node 18: 50 
Recording 5 traces of 1 types on node 18

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 19: 178 
  Number of connections on node 19: 2867 
  Number of synaptic contacts on node 19: 18207 
  Number of stims on node 19: 50 
Recording 5 traces of 1 types on node 19

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 20: 178 
  Number of connections on node 20: 2769 
  Number of synaptic contacts on node 20: 17555 
  Number of stims on node 20: 50 
Recording 5 traces of 1 types on node 20

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 21: 178 
  Number of connections on node 21: 2756 
  Number of synaptic contacts on node 21: 17657 
  Number of stims on node 21: 50 
Recording 5 traces of 1 types on node 21

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 22: 178 
  Number of connections on node 22: 2776 
  Number of synaptic contacts on node 22: 17889 
  Number of stims on node 22: 50 
Recording 5 traces of 1 types on node 22

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 23: 178 
  Number of connections on node 23: 2695 
  Number of synaptic contacts on node 23: 17402 
  Number of stims on node 23: 50 
Recording 5 traces of 1 types on node 23

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 25: 178 
  Number of connections on node 25: 2818 
  Number of synaptic contacts on node 25: 17554 
  Number of stims on node 25: 50 
Recording 5 traces of 1 types on node 25

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 26: 178 
  Number of connections on node 26: 2785 
  Number of synaptic contacts on node 26: 17493 
  Number of stims on node 26: 50 
Recording 5 traces of 1 types on node 26

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 27: 178 
  Number of connections on node 27: 2765 
  Number of synaptic contacts on node 27: 17646 
  Number of stims on node 27: 50 
Recording 5 traces of 1 types on node 27

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 29: 178 
  Number of connections on node 29: 2756 
  Number of synaptic contacts on node 29: 17433 
  Number of stims on node 29: 50 
Recording 5 traces of 1 types on node 29

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 34: 178 
  Number of connections on node 34: 2733 
  Number of synaptic contacts on node 34: 17149 
  Number of stims on node 34: 50 
Recording 5 traces of 1 types on node 34

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 37: 178 
  Number of connections on node 37: 2740 
  Number of synaptic contacts on node 37: 17146 
  Number of stims on node 37: 50 
Recording 5 traces of 1 types on node 37

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 38: 178 
  Number of connections on node 38: 2747 
  Number of synaptic contacts on node 38: 17200 
  Number of stims on node 38: 50 
Recording 5 traces of 1 types on node 38

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 40: 178 
  Number of connections on node 40: 2768 
  Number of synaptic contacts on node 40: 17094 
  Number of stims on node 40: 50 
Recording 5 traces of 1 types on node 40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 44: 178 
  Number of connections on node 44: 2806 
  Number of synaptic contacts on node 44: 17489 
  Number of stims on node 44: 50 
Recording 5 traces of 1 types on node 44

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 45: 178 
  Number of connections on node 45: 2536 
  Number of synaptic contacts on node 45: 15918 
  Number of stims on node 45: 50 
Recording 5 traces of 1 types on node 45

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 46: 178 
  Number of connections on node 46: 2625 
  Number of synaptic contacts on node 46: 16374 
  Number of stims on node 46: 50 
Recording 5 traces of 1 types on node 46

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 47: 178 
  Number of connections on node 47: 2617 
  Number of synaptic contacts on node 47: 16577 
  Number of stims on node 47: 50 
Recording 5 traces of 1 types on node 47

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 52: 178 
  Number of connections on node 52: 3092 
  Number of synaptic contacts on node 52: 18359 
  Number of stims on node 52: 50 
Recording 5 traces of 1 types on node 52

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 53: 178 
  Number of connections on node 53: 3004 
  Number of synaptic contacts on node 53: 17962 
  Number of stims on node 53: 50 
Recording 5 traces of 1 types on node 53

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 55: 178 
  Number of connections on node 55: 3010 
  Number of synaptic contacts on node 55: 18047 
  Number of stims on node 55: 50 
Recording 5 traces of 1 types on node 55

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 56: 178 
  Number of connections on node 56: 3062 
  Number of synaptic contacts on node 56: 18235 
  Number of stims on node 56: 50 
Recording 5 traces of 1 types on node 56

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 57: 178 
  Number of connections on node 57: 3039 
  Number of synaptic contacts on node 57: 17992 
  Number of stims on node 57: 50 
Recording 5 traces of 1 types on node 57

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 60: 178 
  Number of connections on node 60: 3038 
  Number of synaptic contacts on node 60: 18278 
  Number of stims on node 60: 50 
Recording 5 traces of 1 types on node 60

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 61: 178 
  Number of connections on node 61: 3005 
  Number of synaptic contacts on node 61: 17559 
  Number of stims on node 61: 50 
Recording 5 traces of 1 types on node 61

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 66: 178 
  Number of connections on node 66: 3043 
  Number of synaptic contacts on node 66: 18461 
  Number of stims on node 66: 50 
Recording 5 traces of 1 types on node 66

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 78: 178 
  Number of connections on node 78: 2577 
  Number of synaptic contacts on node 78: 16491 
  Number of stims on node 78: 50 
Recording 5 traces of 1 types on node 78

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 87: 178 
  Number of connections on node 87: 2621 
  Number of synaptic contacts on node 87: 17187 
  Number of stims on node 87: 60 
Recording 6 traces of 1 types on node 87

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 97: 178 
  Number of connections on node 97: 2596 
  Number of synaptic contacts on node 97: 16747 
  Number of stims on node 97: 60 
Recording 6 traces of 1 types on node 97

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 117: 178 
  Number of connections on node 117: 2966 
  Number of synaptic contacts on node 117: 18685 
  Number of stims on node 117: 60 
Recording 6 traces of 1 types on node 117

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 192: 178 
  Number of connections on node 192: 2796 
  Number of synaptic contacts on node 192: 16936 
  Number of stims on node 192: 60 
Recording 6 traces of 1 types on node 192

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 193: 178 
  Number of connections on node 193: 2851 
  Number of synaptic contacts on node 193: 17101 
  Number of stims on node 193: 60 
Recording 6 traces of 1 types on node 193

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 194: 178 
  Number of connections on node 194: 2737 
  Number of synaptic contacts on node 194: 16397 
  Number of stims on node 194: 60 
Recording 6 traces of 1 types on node 194

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 195: 178 
  Number of connections on node 195: 2814 
  Number of synaptic contacts on node 195: 16956 
  Number of stims on node 195: 60 
Recording 6 traces of 1 types on node 195

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 196: 178 
  Number of connections on node 196: 2823 
  Number of synaptic contacts on node 196: 16816 
  Number of stims on node 196: 60 
Recording 6 traces of 1 types on node 196

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 197: 178 
  Number of connections on node 197: 2747 
  Number of synaptic contacts on node 197: 16692 
  Number of stims on node 197: 60 
Recording 6 traces of 1 types on node 197

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 198: 178 
  Number of connections on node 198: 2919 
  Number of synaptic contacts on node 198: 17697 
  Number of stims on node 198: 60 
Recording 6 traces of 1 types on node 198

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 199: 178 
  Number of connections on node 199: 2889 
  Number of synaptic contacts on node 199: 17792 
  Number of stims on node 199: 60 
Recording 6 traces of 1 types on node 199

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 200: 178 
  Number of connections on node 200: 2846 
  Number of synaptic contacts on node 200: 17504 
  Number of stims on node 200: 60 
Recording 6 traces of 1 types on node 200

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 201: 178 
  Number of connections on node 201: 2904 
  Number of synaptic contacts on node 201: 17641 
  Number of stims on node 201: 60 
Recording 6 traces of 1 types on node 201

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 202: 178 
  Number of connections on node 202: 2897 
  Number of synaptic contacts on node 202: 17699 
  Number of stims on node 202: 60 
Recording 6 traces of 1 types on node 202

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 203: 178 
  Number of connections on node 203: 2895 
  Number of synaptic contacts on node 203: 17582 
  Number of stims on node 203: 60 
Recording 6 traces of 1 types on node 203

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 204: 178 
  Number of connections on node 204: 2917 
  Number of synaptic contacts on node 204: 17362 
  Number of stims on node 204: 60 
Recording 6 traces of 1 types on node 204

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 205: 178 
  Number of connections on node 205: 2902 
  Number of synaptic contacts on node 205: 17615 
  Number of stims on node 205: 60 
Recording 6 traces of 1 types on node 205

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 206: 178 
  Number of connections on node 206: 2950 
  Number of synaptic contacts on node 206: 17963 
  Number of stims on node 206: 60 
Recording 6 traces of 1 types on node 206

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 207: 178 
  Number of connections on node 207: 2891 
  Number of synaptic contacts on node 207: 17622 
  Number of stims on node 207: 60 
Recording 6 traces of 1 types on node 207

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 208: 178 
  Number of connections on node 208: 2938 
  Number of synaptic contacts on node 208: 17689 
  Number of stims on node 208: 60 
Recording 6 traces of 1 types on node 208

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 209: 178 
  Number of connections on node 209: 2936 
  Number of synaptic contacts on node 209: 17771 
  Number of stims on node 209: 60 
Recording 6 traces of 1 types on node 209

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 210: 178 
  Number of connections on node 210: 2980 
  Number of synaptic contacts on node 210: 17911 
  Number of stims on node 210: 60 
Recording 6 traces of 1 types on node 210

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 211: 178 
  Number of connections on node 211: 2924 
  Number of synaptic contacts on node 211: 17853 
  Number of stims on node 211: 60 
Recording 6 traces of 1 types on node 211

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 212: 178 
  Number of connections on node 212: 2873 
  Number of synaptic contacts on node 212: 17057 
  Number of stims on node 212: 60 
Recording 6 traces of 1 types on node 212

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 213: 178 
  Number of connections on node 213: 2967 
  Number of synaptic contacts on node 213: 17651 
  Number of stims on node 213: 60 
Recording 6 traces of 1 types on node 213

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 214: 178 
  Number of connections on node 214: 2993 
  Number of synaptic contacts on node 214: 17601 
  Number of stims on node 214: 60 
Recording 6 traces of 1 types on node 214

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 215: 178 
  Number of connections on node 215: 2768 
  Number of synaptic contacts on node 215: 16382 
  Number of stims on node 215: 60 
Recording 6 traces of 1 types on node 215

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 216: 178 
  Number of connections on node 216: 2786 
  Number of synaptic contacts on node 216: 16420 
  Number of stims on node 216: 60 
Recording 6 traces of 1 types on node 216

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 217: 178 
  Number of connections on node 217: 2756 
  Number of synaptic contacts on node 217: 16374 
  Number of stims on node 217: 60 
Recording 6 traces of 1 types on node 217

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 218: 178 
  Number of connections on node 218: 2601 
  Number of synaptic contacts on node 218: 15375 
  Number of stims on node 218: 60 
Recording 6 traces of 1 types on node 218

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 219: 178 
  Number of connections on node 219: 2858 
  Number of synaptic contacts on node 219: 16632 
  Number of stims on node 219: 60 
Recording 6 traces of 1 types on node 219

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 220: 178 
  Number of connections on node 220: 2893 
  Number of synaptic contacts on node 220: 16857 
  Number of stims on node 220: 60 
Recording 6 traces of 1 types on node 220

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 221: 178 
  Number of connections on node 221: 2737 
  Number of synaptic contacts on node 221: 16343 
  Number of stims on node 221: 60 
Recording 6 traces of 1 types on node 221

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 222: 178 
  Number of connections on node 222: 3396 
  Number of synaptic contacts on node 222: 19914 
  Number of stims on node 222: 60 
Recording 6 traces of 1 types on node 222

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 223: 178 
  Number of connections on node 223: 3459 
  Number of synaptic contacts on node 223: 20237 
  Number of stims on node 223: 60 
Recording 6 traces of 1 types on node 223

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 129: 178 
  Number of connections on node 129: 3088 
  Number of synaptic contacts on node 129: 19899 
  Number of stims on node 129: 60 
Recording 6 traces of 1 types on node 129

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 130: 178 
  Number of connections on node 130: 3057 
  Number of synaptic contacts on node 130: 19418 
  Number of stims on node 130: 60 
Recording 6 traces of 1 types on node 130

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 131: 178 
  Number of connections on node 131: 3043 
  Number of synaptic contacts on node 131: 19307 
  Number of stims on node 131: 60 
Recording 6 traces of 1 types on node 131

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 134: 178 
  Number of connections on node 134: 3034 
  Number of synaptic contacts on node 134: 19429 
  Number of stims on node 134: 60 
Recording 6 traces of 1 types on node 134

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 136: 178 
  Number of connections on node 136: 3037 
  Number of synaptic contacts on node 136: 19049 
  Number of stims on node 136: 60 
Recording 6 traces of 1 types on node 136

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 137: 178 
  Number of connections on node 137: 3047 
  Number of synaptic contacts on node 137: 19255 
  Number of stims on node 137: 60 
Recording 6 traces of 1 types on node 137

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 139: 178 
  Number of connections on node 139: 3144 
  Number of synaptic contacts on node 139: 19828 
  Number of stims on node 139: 60 
Recording 6 traces of 1 types on node 139

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 140: 178 
  Number of connections on node 140: 3113 
  Number of synaptic contacts on node 140: 19764 
  Number of stims on node 140: 60 
Recording 6 traces of 1 types on node 140

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 142: 178 
  Number of connections on node 142: 3073 
  Number of synaptic contacts on node 142: 19269 
  Number of stims on node 142: 60 
Recording 6 traces of 1 types on node 142

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 144: 178 
  Number of connections on node 144: 3089 
  Number of synaptic contacts on node 144: 19356 
  Number of stims on node 144: 60 
Recording 6 traces of 1 types on node 144

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 145: 178 
  Number of connections on node 145: 3150 
  Number of synaptic contacts on node 145: 19823 
  Number of stims on node 145: 60 
Recording 6 traces of 1 types on node 145

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 154: 178 
  Number of connections on node 154: 2910 
  Number of synaptic contacts on node 154: 18933 
  Number of stims on node 154: 60 
Recording 6 traces of 1 types on node 154

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 158: 178 
  Number of connections on node 158: 2868 
  Number of synaptic contacts on node 158: 18415 
  Number of stims on node 158: 60 
Recording 6 traces of 1 types on node 158

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 159: 178 
  Number of connections on node 159: 2965 
  Number of synaptic contacts on node 159: 19274 
  Number of stims on node 159: 60 
Recording 6 traces of 1 types on node 159

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 160: 178 
  Number of connections on node 160: 2988 
  Number of synaptic contacts on node 160: 19959 
  Number of stims on node 160: 60 
Recording 6 traces of 1 types on node 160

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 161: 178 
  Number of connections on node 161: 3013 
  Number of synaptic contacts on node 161: 20094 
  Number of stims on node 161: 60 
Recording 6 traces of 1 types on node 161

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 162: 178 
  Number of connections on node 162: 2944 
  Number of synaptic contacts on node 162: 19695 
  Number of stims on node 162: 60 
Recording 6 traces of 1 types on node 162

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 163: 178 
  Number of connections on node 163: 3020 
  Number of synaptic contacts on node 163: 19921 
  Number of stims on node 163: 60 
Recording 6 traces of 1 types on node 163

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 167: 178 
  Number of connections on node 167: 2896 
  Number of synaptic contacts on node 167: 18125 
  Number of stims on node 167: 60 
Recording 6 traces of 1 types on node 167

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 169: 178 
  Number of connections on node 169: 2882 
  Number of synaptic contacts on node 169: 18301 
  Number of stims on node 169: 60 
Recording 6 traces of 1 types on node 169

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 170: 178 
  Number of connections on node 170: 2850 
  Number of synaptic contacts on node 170: 17264 
  Number of stims on node 170: 60 
Recording 6 traces of 1 types on node 170

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 171: 178 
  Number of connections on node 171: 2822 
  Number of synaptic contacts on node 171: 17148 
  Number of stims on node 171: 60 
Recording 6 traces of 1 types on node 171

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 172: 178 
  Number of connections on node 172: 2796 
  Number of synaptic contacts on node 172: 16789 
  Number of stims on node 172: 60 
Recording 6 traces of 1 types on node 172

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 173: 178 
  Number of connections on node 173: 2749 
  Number of synaptic contacts on node 173: 16708 
  Number of stims on node 173: 60 
Recording 6 traces of 1 types on node 173

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 174: 178 
  Number of connections on node 174: 2741 
  Number of synaptic contacts on node 174: 16944 
  Number of stims on node 174: 60 
Recording 6 traces of 1 types on node 174

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 175: 178 
  Number of connections on node 175: 2786 
  Number of synaptic contacts on node 175: 17353 
  Number of stims on node 175: 60 
Recording 6 traces of 1 types on node 175

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 176: 178 
  Number of connections on node 176: 2749 
  Number of synaptic contacts on node 176: 17117 
  Number of stims on node 176: 60 
Recording 6 traces of 1 types on node 176

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 177: 178 
  Number of connections on node 177: 2781 
  Number of synaptic contacts on node 177: 17189 
  Number of stims on node 177: 60 
Recording 6 traces of 1 types on node 177

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 178: 178 
  Number of connections on node 178: 2796 
  Number of synaptic contacts on node 178: 17429 
  Number of stims on node 178: 60 
Recording 6 traces of 1 types on node 178

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 179: 178 
  Number of connections on node 179: 2859 
  Number of synaptic contacts on node 179: 17583 
  Number of stims on node 179: 60 
Recording 6 traces of 1 types on node 179

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 180: 178 
  Number of connections on node 180: 2782 
  Number of synaptic contacts on node 180: 17284 
  Number of stims on node 180: 60 
Recording 6 traces of 1 types on node 180

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 182: 178 
  Number of connections on node 182: 2854 
  Number of synaptic contacts on node 182: 17996 
  Number of stims on node 182: 60 
Recording 6 traces of 1 types on node 182

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 184: 178 
  Number of connections on node 184: 2790 
  Number of synaptic contacts on node 184: 16908 
  Number of stims on node 184: 60 
Recording 6 traces of 1 types on node 184

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 186: 178 
  Number of connections on node 186: 2898 
  Number of synaptic contacts on node 186: 17583 
  Number of stims on node 186: 60 
Recording 6 traces of 1 types on node 186

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 187: 178 
  Number of connections on node 187: 2824 
  Number of synaptic contacts on node 187: 17325 
  Number of stims on node 187: 60 
Recording 6 traces of 1 types on node 187

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 188: 178 
  Number of connections on node 188: 3008 
  Number of synaptic contacts on node 188: 18354 
  Number of stims on node 188: 60 
Recording 6 traces of 1 types on node 188

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 189: 178 
  Number of connections on node 189: 2910 
  Number of synaptic contacts on node 189: 17549 
  Number of stims on node 189: 60 
Recording 6 traces of 1 types on node 189

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 191: 178 
  Number of connections on node 191: 2761 
  Number of synaptic contacts on node 191: 16696 
  Number of stims on node 191: 60 
Recording 6 traces of 1 types on node 191

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 128: 178 
  Number of connections on node 128: 3145 
  Number of synaptic contacts on node 128: 19597 
  Number of stims on node 128: 60 
Recording 6 traces of 1 types on node 128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 132: 178 
  Number of connections on node 132: 3106 
  Number of synaptic contacts on node 132: 19645 
  Number of stims on node 132: 60 
Recording 6 traces of 1 types on node 132

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 133: 178 
  Number of connections on node 133: 3085 
  Number of synaptic contacts on node 133: 19433 
  Number of stims on node 133: 60 
Recording 6 traces of 1 types on node 133

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 135: 178 
  Number of connections on node 135: 3010 
  Number of synaptic contacts on node 135: 19303 
  Number of stims on node 135: 60 
Recording 6 traces of 1 types on node 135

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 138: 178 
  Number of connections on node 138: 3123 
  Number of synaptic contacts on node 138: 19541 
  Number of stims on node 138: 60 
Recording 6 traces of 1 types on node 138

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 143: 178 
  Number of connections on node 143: 3128 
  Number of synaptic contacts on node 143: 19971 
  Number of stims on node 143: 60 
Recording 6 traces of 1 types on node 143

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 146: 178 
  Number of connections on node 146: 3128 
  Number of synaptic contacts on node 146: 19474 
  Number of stims on node 146: 60 
Recording 6 traces of 1 types on node 146

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 147: 178 
  Number of connections on node 147: 3149 
  Number of synaptic contacts on node 147: 19601 
  Number of stims on node 147: 60 
Recording 6 traces of 1 types on node 147

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 148: 178 
  Number of connections on node 148: 3179 
  Number of synaptic contacts on node 148: 20042 
  Number of stims on node 148: 60 
Recording 6 traces of 1 types on node 148

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 149: 178 
  Number of connections on node 149: 3208 
  Number of synaptic contacts on node 149: 20300 
  Number of stims on node 149: 60 
Recording 6 traces of 1 types on node 149

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 150: 178 
  Number of connections on node 150: 3116 
  Number of synaptic contacts on node 150: 19587 
  Number of stims on node 150: 60 
Recording 6 traces of 1 types on node 150

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 151: 178 
  Number of connections on node 151: 3138 
  Number of synaptic contacts on node 151: 19729 
  Number of stims on node 151: 60 
Recording 6 traces of 1 types on node 151

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 152: 178 
  Number of connections on node 152: 3101 
  Number of synaptic contacts on node 152: 19390 
  Number of stims on node 152: 60 
Recording 6 traces of 1 types on node 152

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 153: 178 
  Number of connections on node 153: 3254 
  Number of synaptic contacts on node 153: 20649 
  Number of stims on node 153: 60 
Recording 6 traces of 1 types on node 153

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 155: 178 
  Number of connections on node 155: 2898 
  Number of synaptic contacts on node 155: 18593 
  Number of stims on node 155: 60 
Recording 6 traces of 1 types on node 155

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 156: 178 
  Number of connections on node 156: 2817 
  Number of synaptic contacts on node 156: 18269 
  Number of stims on node 156: 60 
Recording 6 traces of 1 types on node 156

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 157: 178 
  Number of connections on node 157: 2912 
  Number of synaptic contacts on node 157: 18947 
  Number of stims on node 157: 60 
Recording 6 traces of 1 types on node 157

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 164: 178 
  Number of connections on node 164: 2938 
  Number of synaptic contacts on node 164: 19296 
  Number of stims on node 164: 60 
Recording 6 traces of 1 types on node 164

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 165: 178 
  Number of connections on node 165: 3141 
  Number of synaptic contacts on node 165: 20157 
  Number of stims on node 165: 60 
Recording 6 traces of 1 types on node 165

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 166: 178 
  Number of connections on node 166: 2973 
  Number of synaptic contacts on node 166: 18915 
  Number of stims on node 166: 60 
Recording 6 traces of 1 types on node 166

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 168: 178 
  Number of connections on node 168: 2961 
  Number of synaptic contacts on node 168: 18902 
  Number of stims on node 168: 60 
Recording 6 traces of 1 types on node 168

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 181: 178 
  Number of connections on node 181: 2833 
  Number of synaptic contacts on node 181: 17812 
  Number of stims on node 181: 60 
Recording 6 traces of 1 types on node 181

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 183: 178 
  Number of connections on node 183: 2842 
  Number of synaptic contacts on node 183: 17626 
  Number of stims on node 183: 60 
Recording 6 traces of 1 types on node 183

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 185: 178 
  Number of connections on node 185: 2865 
  Number of synaptic contacts on node 185: 17278 
  Number of stims on node 185: 60 
Recording 6 traces of 1 types on node 185

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 190: 178 
  Number of connections on node 190: 2921 
  Number of synaptic contacts on node 190: 17648 
  Number of stims on node 190: 60 
Recording 6 traces of 1 types on node 190

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py
  Number of cells on node 141: 178 
  Number of connections on node 141: 3061 
  Number of synaptic contacts on node 141: 19087 
  Number of stims on node 141: 60 
Recording 6 traces of 1 types on node 141

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch4/v8_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch4/v8_batch4_netParams.py

Start time:  2022-04-23 22:03:55.626413

Creating network of 420 cell populations on 224 hosts...
  Number of cells on node 0: 179 
  Done; cell creation time = 12.03 s.
Making connections...
  Number of connections on node 0: 3456 
  Number of synaptic contacts on node 0: 19826 
  Done; cell connection time = 1894.10 s.
Adding stims...
  Number of stims on node 0: 60 
  Done; cell stims creation time = 27.59 s.
Recording 6 traces of 1 types on node 0
0.0s

Running simulation using NEURON for 11000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
  Done; run time = 12064.63 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 73.07 s.

Analyzing...
  Cells: 39876
  Connections: 0 (0.00 per cell)
  Spikes: 2399374 (5.47 Hz)
  Simulated time: 11.0 s; 224 workers
  Run time: 12064.63 s
   presyn_L1_DAC_bNA : 0.029 Hz
   presyn_L1_DAC_cNA : 0.042 Hz
   presyn_L1_DLAC_cNA : 0.030 Hz
   presyn_L1_HAC_bNA : 0.024 Hz
   presyn_L1_HAC_cIR : 0.018 Hz
   presyn_L1_HAC_cNA : 0.029 Hz
   presyn_L1_NGC-DA_bNA : 0.057 Hz
   presyn_L1_NGC-DA_cAC : 0.034 Hz
   presyn_L1_NGC-DA_cNA : 0.095 Hz
   presyn_L1_NGC-DA_cST : 0.057 Hz
   presyn_L1_NGC-SA_cNA : 0.105 Hz
   presyn_L1_SLAC_bNA : 0.175 Hz
   presyn_L1_SLAC_cAC : 0.034 Hz
   presyn_L1_SLAC_cNA : 0.043 Hz
   presyn_L23_BP_bAC : 2.606 Hz
   presyn_L23_BP_bIR : 2.477 Hz
   presyn_L23_BP_bNA : 5.026 Hz
   presyn_L23_BP_cAC : 4.558 Hz
   presyn_L23_BP_cNA : 7.205 Hz
   presyn_L23_BP_dST : 4.788 Hz
   presyn_L23_BTC_bAC : 0.248 Hz
   presyn_L23_BTC_bIR : 0.104 Hz
   presyn_L23_BTC_bNA : 0.415 Hz
   presyn_L23_BTC_cAC : 0.284 Hz
   presyn_L23_BTC_cNA : 0.677 Hz
   presyn_L23_ChC_cAC : 2.411 Hz
   presyn_L23_ChC_cNA : 1.941 Hz
   presyn_L23_ChC_dNA : 0.376 Hz
   presyn_L23_DBC_bAC : 2.030 Hz
   presyn_L23_DBC_bIR : 0.562 Hz
   presyn_L23_DBC_bNA : 2.981 Hz
   presyn_L23_DBC_cAC : 2.459 Hz
   presyn_L23_LBC_bAC : 0.314 Hz
   presyn_L23_LBC_bNA : 6.515 Hz
   presyn_L23_LBC_cAC : 1.908 Hz
   presyn_L23_LBC_cNA : 3.008 Hz
   presyn_L23_LBC_cST : 3.322 Hz
   presyn_L23_LBC_dNA : 5.397 Hz
   presyn_L23_MC_bAC : 0.009 Hz
   presyn_L23_MC_bNA : 0.455 Hz
   presyn_L23_MC_cAC : 0.053 Hz
   presyn_L23_MC_cNA : 0.083 Hz
   presyn_L23_MC_dNA : 0.000 Hz
   presyn_L23_NBC_bAC : 0.208 Hz
   presyn_L23_NBC_bNA : 3.076 Hz
   presyn_L23_NBC_cAC : 0.790 Hz
   presyn_L23_NBC_cIR : 0.076 Hz
   presyn_L23_NBC_cNA : 0.727 Hz
   presyn_L23_NBC_dNA : 1.194 Hz
   presyn_L23_NGC_bNA : 0.455 Hz
   presyn_L23_NGC_cAC : 0.327 Hz
   presyn_L23_NGC_cNA : 0.636 Hz
   presyn_L23_NGC_cST : 0.091 Hz
   presyn_L23_PC_cAD : 0.510 Hz
   presyn_L23_SBC_bNA : 5.571 Hz
   presyn_L23_SBC_cAC : 4.665 Hz
   presyn_L23_SBC_dNA : 3.522 Hz
   presyn_L4_BP_bAC : 8.545 Hz
   presyn_L4_BP_bIR : 6.091 Hz
   presyn_L4_BP_bNA : 8.091 Hz
   presyn_L4_BP_cAC : 4.773 Hz
   presyn_L4_BP_cNA : 16.727 Hz
   presyn_L4_BP_dST : 0.182 Hz
   presyn_L4_BTC_bAC : 4.545 Hz
   presyn_L4_BTC_bIR : 1.045 Hz
   presyn_L4_BTC_bST : 5.227 Hz
   presyn_L4_BTC_cAC : 6.879 Hz
   presyn_L4_BTC_cNA : 11.061 Hz
   presyn_L4_BTC_dNA : 2.955 Hz
   presyn_L4_ChC_cAC : 18.788 Hz
   presyn_L4_ChC_cNA : 20.667 Hz
   presyn_L4_ChC_dNA : 3.227 Hz
   presyn_L4_DBC_bAC : 5.091 Hz
   presyn_L4_DBC_bIR : 0.301 Hz
   presyn_L4_DBC_bNA : 3.273 Hz
   presyn_L4_DBC_bST : 0.182 Hz
   presyn_L4_DBC_cAC : 3.864 Hz
   presyn_L4_DBC_cIR : 0.584 Hz
   presyn_L4_DBC_cNA : 4.795 Hz
   presyn_L4_LBC_cAC : 14.434 Hz
   presyn_L4_LBC_cNA : 23.890 Hz
   presyn_L4_LBC_cST : 17.836 Hz
   presyn_L4_LBC_dNA : 26.771 Hz
   presyn_L4_LBC_dST : 20.222 Hz
   presyn_L4_MC_bAC : 0.050 Hz
   presyn_L4_MC_bNA : 0.318 Hz
   presyn_L4_MC_cAC : 0.292 Hz
   presyn_L4_MC_cNA : 0.495 Hz
   presyn_L4_MC_dNA : 0.045 Hz
   presyn_L4_NBC_cAC : 13.891 Hz
   presyn_L4_NBC_cIR : 9.436 Hz
   presyn_L4_NBC_cNA : 28.440 Hz
   presyn_L4_NBC_dNA : 22.795 Hz
   presyn_L4_NGC_bNA : 6.909 Hz
   presyn_L4_NGC_cAC : 5.455 Hz
   presyn_L4_NGC_cNA : 6.455 Hz
   presyn_L4_NGC_cST : 0.455 Hz
   presyn_L4_PC_cAD : 3.419 Hz
   presyn_L4_SBC_bNA : 25.519 Hz
   presyn_L4_SBC_cAC : 15.335 Hz
   presyn_L4_SBC_dNA : 26.102 Hz
   presyn_L4_SP_cAD : 4.502 Hz
   presyn_L4_SS_cAD : 4.835 Hz
   presyn_L5_BP_bAC : 9.939 Hz
   presyn_L5_BP_bIR : 4.200 Hz
   presyn_L5_BP_bNA : 26.697 Hz
   presyn_L5_BP_cAC : 15.909 Hz
   presyn_L5_BP_cNA : 34.509 Hz
   presyn_L5_BP_dST : 3.091 Hz
   presyn_L5_BTC_bAC : 9.888 Hz
   presyn_L5_BTC_cAC : 13.093 Hz
   presyn_L5_BTC_cNA : 22.378 Hz
   presyn_L5_ChC_cAC : 25.468 Hz
   presyn_L5_ChC_cNA : 37.597 Hz
   presyn_L5_ChC_dNA : 36.109 Hz
   presyn_L5_DBC_bAC : 5.636 Hz
   presyn_L5_DBC_bIR : 1.380 Hz
   presyn_L5_DBC_bNA : 10.040 Hz
   presyn_L5_DBC_bST : 4.374 Hz
   presyn_L5_DBC_cAC : 10.354 Hz
   presyn_L5_DBC_cIR : 3.230 Hz
   presyn_L5_DBC_cNA : 15.909 Hz
   presyn_L5_LBC_bAC : 10.735 Hz
   presyn_L5_LBC_cAC : 20.149 Hz
   presyn_L5_LBC_cIR : 7.378 Hz
   presyn_L5_LBC_cNA : 43.592 Hz
   presyn_L5_LBC_cST : 32.882 Hz
   presyn_L5_LBC_dNA : 40.162 Hz
   presyn_L5_LBC_dST : 27.659 Hz
   presyn_L5_MC_bAC : 2.791 Hz
   presyn_L5_MC_bIR : 0.742 Hz
   presyn_L5_MC_bST : 1.619 Hz
   presyn_L5_MC_cAC : 4.843 Hz
   presyn_L5_MC_cNA : 4.420 Hz
   presyn_L5_MC_cST : 0.557 Hz
   presyn_L5_MC_dNA : 1.000 Hz
   presyn_L5_NBC_bAC : 8.838 Hz
   presyn_L5_NBC_bIR : 4.968 Hz
   presyn_L5_NBC_bST : 26.276 Hz
   presyn_L5_NBC_cAC : 24.048 Hz
   presyn_L5_NBC_cIR : 14.162 Hz
   presyn_L5_NBC_cNA : 38.408 Hz
   presyn_L5_NBC_cST : 28.409 Hz
   presyn_L5_NBC_dST : 30.895 Hz
   presyn_L5_NGC_bNA : 0.091 Hz
   presyn_L5_NGC_cAC : 14.818 Hz
   presyn_L5_NGC_cNA : 23.727 Hz
   presyn_L5_NGC_cST : 4.364 Hz
   presyn_L5_SBC_bNA : 28.424 Hz
   presyn_L5_SBC_cAC : 14.525 Hz
   presyn_L5_SBC_dNA : 48.766 Hz
   presyn_L5_STPC_cAD : 7.458 Hz
   presyn_L5_TTPC1_cAD : 7.672 Hz
   presyn_L5_TTPC2_cAD : 7.964 Hz
   presyn_L5_UTPC_cAD : 10.633 Hz
   presyn_L6_BPC_cAD : 4.636 Hz
   presyn_L6_BP_bAC : 7.515 Hz
   presyn_L6_BP_bIR : 2.745 Hz
   presyn_L6_BP_bNA : 16.512 Hz
   presyn_L6_BP_cAC : 14.105 Hz
   presyn_L6_BP_cNA : 25.355 Hz
   presyn_L6_BP_dST : 1.485 Hz
   presyn_L6_BTC_bAC : 7.164 Hz
   presyn_L6_BTC_cAC : 11.088 Hz
   presyn_L6_BTC_cNA : 22.745 Hz
   presyn_L6_ChC_cAC : 10.515 Hz
   presyn_L6_ChC_cNA : 52.091 Hz
   presyn_L6_ChC_dNA : 32.864 Hz
   presyn_L6_DBC_bAC : 8.000 Hz
   presyn_L6_DBC_bIR : 1.373 Hz
   presyn_L6_DBC_bNA : 7.576 Hz
   presyn_L6_DBC_bST : 3.606 Hz
   presyn_L6_DBC_cAC : 10.303 Hz
   presyn_L6_DBC_cIR : 4.273 Hz
   presyn_L6_DBC_cNA : 7.242 Hz
   presyn_L6_IPC_cAD : 4.365 Hz
   presyn_L6_LBC_bAC : 6.997 Hz
   presyn_L6_LBC_bIR : 4.024 Hz
   presyn_L6_LBC_bNA : 55.414 Hz
   presyn_L6_LBC_bST : 29.492 Hz
   presyn_L6_LBC_cNA : 43.926 Hz
   presyn_L6_LBC_cST : 25.427 Hz
   presyn_L6_MC_bAC : 1.089 Hz
   presyn_L6_MC_bIR : 0.122 Hz
   presyn_L6_MC_bNA : 2.208 Hz
   presyn_L6_MC_bST : 0.487 Hz
   presyn_L6_MC_cAC : 3.100 Hz
   presyn_L6_MC_cIR : 0.078 Hz
   presyn_L6_MC_cNA : 2.357 Hz
   presyn_L6_NBC_bAC : 8.084 Hz
   presyn_L6_NBC_bIR : 5.019 Hz
   presyn_L6_NBC_bST : 37.256 Hz
   presyn_L6_NBC_cAC : 13.802 Hz
   presyn_L6_NBC_cIR : 6.318 Hz
   presyn_L6_NBC_cNA : 32.189 Hz
   presyn_L6_NBC_cST : 28.028 Hz
   presyn_L6_NBC_dST : 32.838 Hz
   presyn_L6_NGC_bNA : 15.182 Hz
   presyn_L6_NGC_cAC : 13.773 Hz
   presyn_L6_NGC_cNA : 25.612 Hz
   presyn_L6_NGC_cST : 4.591 Hz
   presyn_L6_SBC_bNA : 40.625 Hz
   presyn_L6_SBC_cAC : 24.072 Hz
   presyn_L6_SBC_dNA : 29.431 Hz
   presyn_L6_TPC_L1_cAD : 4.653 Hz
   presyn_L6_TPC_L4_cAD : 5.518 Hz
   presyn_L6_UTPC_cAD : 5.972 Hz
   presyn_ss_RTN_o : 11.503 Hz
   presyn_ss_RTN_m : 12.162 Hz
   presyn_ss_RTN_i : 11.073 Hz
   presyn_VPL_sTC : 2.584 Hz
   presyn_VPM_sTC : 2.820 Hz
   presyn_POm_sTC_s1 : 3.476 Hz
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.045 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.030 Hz
   L1_NGC-DA_bNA : 0.091 Hz
   L1_NGC-DA_cAC : 1.182 Hz
   L1_NGC-DA_cNA : 0.091 Hz
   L1_NGC-DA_cST : 0.182 Hz
   L1_NGC-SA_cNA : 0.045 Hz
   L1_SLAC_bNA : 0.091 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 5.455 Hz
   L23_BP_bIR : 5.364 Hz
   L23_BP_bNA : 25.273 Hz
   L23_BP_cAC : 8.455 Hz
   L23_BP_cNA : 23.909 Hz
   L23_BP_dST : 18.636 Hz
   L23_BTC_bAC : 4.818 Hz
   L23_BTC_bIR : 1.273 Hz
   L23_BTC_bNA : 6.636 Hz
   L23_BTC_cAC : 5.682 Hz
   L23_BTC_cNA : 5.636 Hz
   L23_ChC_cAC : 8.545 Hz
   L23_ChC_cNA : 8.273 Hz
   L23_ChC_dNA : 8.091 Hz
   L23_DBC_bAC : 7.273 Hz
   L23_DBC_bIR : 4.227 Hz
   L23_DBC_bNA : 16.939 Hz
   L23_DBC_cAC : 7.667 Hz
   L23_LBC_bAC : 3.773 Hz
   L23_LBC_bNA : 11.727 Hz
   L23_LBC_cAC : 6.818 Hz
   L23_LBC_cNA : 10.303 Hz
   L23_LBC_cST : 4.818 Hz
   L23_LBC_dNA : 14.130 Hz
   L23_MC_bAC : 1.545 Hz
   L23_MC_bNA : 5.636 Hz
   L23_MC_cAC : 3.673 Hz
   L23_MC_cNA : 5.591 Hz
   L23_MC_dNA : 1.364 Hz
   L23_NBC_bAC : 0.909 Hz
   L23_NBC_bNA : 6.364 Hz
   L23_NBC_cAC : 7.121 Hz
   L23_NBC_cIR : 5.091 Hz
   L23_NBC_cNA : 8.970 Hz
   L23_NBC_dNA : 6.886 Hz
   L23_NGC_bNA : 9.545 Hz
   L23_NGC_cAC : 6.636 Hz
   L23_NGC_cNA : 9.864 Hz
   L23_NGC_cST : 3.727 Hz
   L23_PC_cAD : 1.839 Hz
   L23_SBC_bNA : 15.182 Hz
   L23_SBC_cAC : 9.364 Hz
   L23_SBC_dNA : 9.909 Hz
   L4_BP_bAC : 8.909 Hz
   L4_BP_bIR : 6.818 Hz
   L4_BP_bNA : 23.636 Hz
   L4_BP_cAC : 6.091 Hz
   L4_BP_cNA : 23.000 Hz
   L4_BP_dST : 9.273 Hz
   L4_BTC_bAC : 8.455 Hz
   L4_BTC_bIR : 6.727 Hz
   L4_BTC_bST : 9.182 Hz
   L4_BTC_cAC : 10.182 Hz
   L4_BTC_cNA : 29.364 Hz
   L4_BTC_dNA : 15.909 Hz
   L4_ChC_cAC : 34.636 Hz
   L4_ChC_cNA : 85.545 Hz
   L4_ChC_dNA : 8.000 Hz
   L4_DBC_bAC : 13.909 Hz
   L4_DBC_bIR : 5.909 Hz
   L4_DBC_bNA : 14.727 Hz
   L4_DBC_bST : 5.182 Hz
   L4_DBC_cAC : 13.182 Hz
   L4_DBC_cIR : 6.545 Hz
   L4_DBC_cNA : 21.273 Hz
   L4_LBC_cAC : 21.909 Hz
   L4_LBC_cNA : 34.000 Hz
   L4_LBC_cST : 14.591 Hz
   L4_LBC_dNA : 81.045 Hz
   L4_LBC_dST : 35.636 Hz
   L4_MC_bAC : 2.000 Hz
   L4_MC_bNA : 1.273 Hz
   L4_MC_cAC : 3.030 Hz
   L4_MC_cNA : 7.818 Hz
   L4_MC_dNA : 7.091 Hz
   L4_NBC_cAC : 30.273 Hz
   L4_NBC_cIR : 8.091 Hz
   L4_NBC_cNA : 21.636 Hz
   L4_NBC_dNA : 57.500 Hz
   L4_NGC_bNA : 9.636 Hz
   L4_NGC_cAC : 11.636 Hz
   L4_NGC_cNA : 18.364 Hz
   L4_NGC_cST : 6.727 Hz
   L4_PC_cAD : 4.047 Hz
   L4_SBC_bNA : 53.636 Hz
   L4_SBC_cAC : 18.545 Hz
   L4_SBC_dNA : 52.455 Hz
   L4_SP_cAD : 6.318 Hz
   L4_SS_cAD : 5.133 Hz
   L5_BP_bAC : 14.091 Hz
   L5_BP_bIR : 7.364 Hz
   L5_BP_bNA : 35.000 Hz
   L5_BP_cAC : 28.000 Hz
   L5_BP_cNA : 60.545 Hz
   L5_BP_dST : 13.727 Hz
   L5_BTC_bAC : 12.364 Hz
   L5_BTC_cAC : 16.364 Hz
   L5_BTC_cNA : 56.364 Hz
   L5_ChC_cAC : 26.182 Hz
   L5_ChC_cNA : 51.727 Hz
   L5_ChC_dNA : 16.818 Hz
   L5_DBC_bAC : 10.545 Hz
   L5_DBC_bIR : 3.500 Hz
   L5_DBC_bNA : 13.273 Hz
   L5_DBC_bST : 10.000 Hz
   L5_DBC_cAC : 13.182 Hz
   L5_DBC_cIR : 8.636 Hz
   L5_DBC_cNA : 15.091 Hz
   L5_LBC_bAC : 10.727 Hz
   L5_LBC_cAC : 10.364 Hz
   L5_LBC_cIR : 6.000 Hz
   L5_LBC_cNA : 26.227 Hz
   L5_LBC_cST : 57.364 Hz
   L5_LBC_dNA : 86.636 Hz
   L5_LBC_dST : 10.636 Hz
   L5_MC_bAC : 7.394 Hz
   L5_MC_bIR : 1.909 Hz
   L5_MC_bST : 0.091 Hz
   L5_MC_cAC : 6.773 Hz
   L5_MC_cNA : 11.273 Hz
   L5_MC_cST : 3.364 Hz
   L5_MC_dNA : 3.182 Hz
   L5_NBC_bAC : 14.818 Hz
   L5_NBC_bIR : 7.818 Hz
   L5_NBC_bST : 108.455 Hz
   L5_NBC_cAC : 21.864 Hz
   L5_NBC_cIR : 5.636 Hz
   L5_NBC_cNA : 25.727 Hz
   L5_NBC_cST : 34.864 Hz
   L5_NBC_dST : 9.091 Hz
   L5_NGC_bNA : 0.091 Hz
   L5_NGC_cAC : 0.182 Hz
   L5_NGC_cNA : 0.091 Hz
   L5_NGC_cST : 0.091 Hz
   L5_SBC_bNA : 50.273 Hz
   L5_SBC_cAC : 28.727 Hz
   L5_SBC_dNA : 36.091 Hz
   L5_STPC_cAD : 5.140 Hz
   L5_TTPC1_cAD : 7.949 Hz
   L5_TTPC2_cAD : 9.877 Hz
   L5_UTPC_cAD : 13.923 Hz
   L6_BPC_cAD : 5.133 Hz
   L6_BP_bAC : 12.636 Hz
   L6_BP_bIR : 6.545 Hz
   L6_BP_bNA : 40.182 Hz
   L6_BP_cAC : 25.364 Hz
   L6_BP_cNA : 40.636 Hz
   L6_BP_dST : 13.636 Hz
   L6_BTC_bAC : 8.182 Hz
   L6_BTC_cAC : 10.091 Hz
   L6_BTC_cNA : 65.273 Hz
   L6_ChC_cAC : 0.273 Hz
   L6_ChC_cNA : 46.455 Hz
   L6_ChC_dNA : 111.364 Hz
   L6_DBC_bAC : 11.000 Hz
   L6_DBC_bIR : 4.727 Hz
   L6_DBC_bNA : 21.455 Hz
   L6_DBC_bST : 6.000 Hz
   L6_DBC_cAC : 25.818 Hz
   L6_DBC_cIR : 11.000 Hz
   L6_DBC_cNA : 28.455 Hz
   L6_IPC_cAD : 5.326 Hz
   L6_LBC_bAC : 7.432 Hz
   L6_LBC_bIR : 7.491 Hz
   L6_LBC_bNA : 41.909 Hz
   L6_LBC_bST : 38.218 Hz
   L6_LBC_cNA : 62.500 Hz
   L6_LBC_cST : 14.500 Hz
   L6_MC_bAC : 5.818 Hz
   L6_MC_bIR : 1.894 Hz
   L6_MC_bNA : 14.455 Hz
   L6_MC_bST : 2.636 Hz
   L6_MC_cAC : 9.273 Hz
   L6_MC_cIR : 5.273 Hz
   L6_MC_cNA : 10.000 Hz
   L6_NBC_bAC : 10.727 Hz
   L6_NBC_bIR : 11.636 Hz
   L6_NBC_bST : 43.364 Hz
   L6_NBC_cAC : 39.864 Hz
   L6_NBC_cIR : 5.455 Hz
   L6_NBC_cNA : 82.136 Hz
   L6_NBC_cST : 68.545 Hz
   L6_NBC_dST : 7.455 Hz
   L6_NGC_bNA : 0.091 Hz
   L6_NGC_cAC : 0.364 Hz
   L6_NGC_cNA : 0.091 Hz
   L6_NGC_cST : 14.455 Hz
   L6_SBC_bNA : 0.091 Hz
   L6_SBC_cAC : 27.818 Hz
   L6_SBC_dNA : 0.182 Hz
   L6_TPC_L1_cAD : 5.467 Hz
   L6_TPC_L4_cAD : 5.026 Hz
   L6_UTPC_cAD : 6.100 Hz
Saving output as ../data/v8_batch4/v8_batch4_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 58.98 s.
Preparing spike data...
Plotting raster...
  Done; plotting time = 223.94 s

Total time = 14880.87 s

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 55231 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 55232 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 55233 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 55234 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 55235 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 55236 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 6 PID 55237 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 7 PID 55238 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 8 PID 55239 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 9 PID 55240 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 10 PID 55241 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 11 PID 55242 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 12 PID 55243 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 13 PID 55244 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 14 PID 55245 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 15 PID 55246 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 16 PID 55247 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 17 PID 55248 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 18 PID 55249 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 19 PID 55250 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 20 PID 55251 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 21 PID 55252 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 22 PID 55253 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 23 PID 55254 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 24 PID 55255 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 25 PID 55256 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 26 PID 55257 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 27 PID 55258 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 28 PID 55259 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 29 PID 55260 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 30 PID 55261 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 31 PID 55262 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 32 PID 55263 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 33 PID 55264 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 34 PID 55265 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 35 PID 55266 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 36 PID 55267 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 37 PID 55268 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 38 PID 55269 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 39 PID 55270 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 40 PID 55271 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 41 PID 55272 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 42 PID 55273 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 43 PID 55274 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 44 PID 55275 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 45 PID 55276 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 46 PID 55277 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 47 PID 55278 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 48 PID 55279 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 49 PID 55280 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 50 PID 55281 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 51 PID 55282 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 52 PID 55283 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 53 PID 55284 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 54 PID 55285 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 55 PID 55286 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 56 PID 55287 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 57 PID 55288 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 58 PID 55289 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 59 PID 55290 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 60 PID 55291 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 61 PID 55292 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 62 PID 55293 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 63 PID 55294 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 64 PID 55295 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 65 PID 55296 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 66 PID 55297 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 67 PID 55298 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 68 PID 55299 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 69 PID 55300 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 70 PID 55301 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 71 PID 55302 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 72 PID 55303 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 73 PID 55304 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 74 PID 55305 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 75 PID 55306 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 76 PID 55307 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 77 PID 55308 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 78 PID 55309 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 79 PID 55310 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 80 PID 55311 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 81 PID 55312 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 82 PID 55313 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 83 PID 55314 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 84 PID 55315 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 85 PID 55316 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 86 PID 55317 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 87 PID 55318 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 88 PID 55319 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 89 PID 55320 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 90 PID 55321 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 91 PID 55322 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 92 PID 55323 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 93 PID 55324 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 94 PID 55325 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 95 PID 55326 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 96 PID 55327 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 97 PID 55328 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 98 PID 55329 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 99 PID 55330 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 100 PID 55331 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 101 PID 55332 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 102 PID 55333 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 103 PID 55334 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 104 PID 55335 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 105 PID 55336 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 106 PID 55337 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 107 PID 55338 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 108 PID 55339 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 109 PID 55340 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 110 PID 55341 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 111 PID 55342 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 112 PID 55343 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 113 PID 55344 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 114 PID 55345 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 115 PID 55346 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 116 PID 55347 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 117 PID 55348 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 118 PID 55349 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 119 PID 55350 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 120 PID 55351 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 121 PID 55352 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 122 PID 55353 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 123 PID 55354 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 124 PID 55355 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 125 PID 55356 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 126 PID 55357 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 127 PID 55358 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 128 PID 55359 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 129 PID 55360 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 130 PID 55361 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 131 PID 55362 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 132 PID 55363 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 133 PID 55364 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 134 PID 55365 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 135 PID 55366 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 136 PID 55367 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 137 PID 55368 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 138 PID 55369 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 139 PID 55370 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 140 PID 55371 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 141 PID 55372 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 142 PID 55373 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 143 PID 55374 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 144 PID 55375 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 145 PID 55376 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 146 PID 55377 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 147 PID 55378 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 148 PID 55379 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 149 PID 55380 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 150 PID 55381 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 151 PID 55382 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 152 PID 55383 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 153 PID 55384 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 154 PID 55385 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 155 PID 55386 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 156 PID 55387 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 157 PID 55388 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 158 PID 55389 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 159 PID 55390 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 160 PID 55391 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 161 PID 55392 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 162 PID 55393 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 163 PID 55394 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 164 PID 55395 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 165 PID 55396 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 166 PID 55397 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 167 PID 55398 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 168 PID 55399 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 169 PID 55400 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 170 PID 55401 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 171 PID 55402 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 172 PID 55403 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 173 PID 55404 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 174 PID 55405 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 175 PID 55406 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 176 PID 55407 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 177 PID 55408 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 178 PID 55409 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 179 PID 55410 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 180 PID 55411 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 181 PID 55412 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 182 PID 55413 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 183 PID 55414 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 184 PID 55415 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 185 PID 55416 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 186 PID 55417 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 187 PID 55418 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 188 PID 55419 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 189 PID 55420 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 190 PID 55421 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 191 PID 55422 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 192 PID 55423 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 193 PID 55424 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 194 PID 55425 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 195 PID 55426 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 196 PID 55427 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 197 PID 55428 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 198 PID 55429 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 199 PID 55430 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 200 PID 55431 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 201 PID 55432 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 202 PID 55433 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 203 PID 55434 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 204 PID 55435 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 205 PID 55436 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 206 PID 55437 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 207 PID 55438 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 208 PID 55439 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 209 PID 55440 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 210 PID 55441 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 211 PID 55442 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 212 PID 55443 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 213 PID 55444 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 214 PID 55445 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 215 PID 55446 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 216 PID 55447 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 217 PID 55448 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 218 PID 55449 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 219 PID 55450 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 220 PID 55451 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 221 PID 55452 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 222 PID 55453 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 223 PID 55454 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================
