numprocs=80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch5/v5_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py

Start time:  2021-07-11 23:48:17.495644
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py
Importing netParams from ../data/v5_batch5/v5_batch5_netParams.py

Creating network of 61 cell populations on 80 hosts...
  Number of cells on node 65: 482 
  Number of cells on node 6: 483 
  Number of cells on node 58: 482 
  Number of cells on node 7: 483 
  Number of cells on node 71: 482 
  Number of cells on node 5: 483 
  Number of cells on node 50: 483 
  Number of cells on node 57: 482 
  Number of cells on node 24: 483 
  Number of cells on node 9: 483 
  Number of cells on node 72: 482 
  Number of cells on node 74: 482 
  Number of cells on node 17: 483 
  Number of cells on node 77: 482 
  Number of cells on node 14: 483 
  Number of cells on node 25: 483 
  Number of cells on node 8: 483 
  Number of cells on node 63: 482 
  Number of cells on node 60: 482 
  Number of cells on node 22: 483 
  Number of cells on node 29: 483 
  Number of cells on node 62: 482 
  Number of cells on node 39: 483 
  Number of cells on node 36: 483 
  Number of cells on node 79: 482 
  Number of cells on node 64: 482 
  Number of cells on node 13: 483 
  Number of cells on node 78: 482 
  Number of cells on node 26: 483 
  Number of cells on node 30: 483 
  Number of cells on node 66: 482 
  Number of cells on node 45: 483 
  Number of cells on node 33: 483 
  Number of cells on node 12: 483 
  Number of cells on node 15: 483 
  Number of cells on node 49: 483 
  Number of cells on node 52: 482 
  Number of cells on node 18: 483 
  Number of cells on node 4: 483 
  Number of cells on node 69: 482 
  Number of cells on node 48: 483 
  Number of cells on node 0: 483 
  Done; cell creation time = 29.72 s.
Making connections...
  Number of cells on node 54: 482 
  Number of cells on node 53: 482 
  Number of cells on node 3: 483 
  Number of cells on node 44: 483 
  Number of cells on node 51: 483 
  Number of cells on node 23: 483 
  Number of cells on node 19: 483 
  Number of cells on node 2: 483 
  Number of cells on node 1: 483 
  Number of cells on node 37: 483 
  Number of cells on node 20: 483 
  Number of cells on node 16: 483 
  Number of cells on node 76: 482 
  Number of cells on node 67: 482 
  Number of cells on node 61: 482 
  Number of cells on node 59: 482 
  Number of cells on node 70: 482 
  Number of cells on node 34: 483 
  Number of cells on node 31: 483 
  Number of cells on node 68: 482 
  Number of cells on node 56: 482 
  Number of cells on node 38: 483 
  Number of cells on node 47: 483 
  Number of cells on node 27: 483 
  Number of cells on node 55: 482 
  Number of cells on node 75: 482 
  Number of cells on node 28: 483 
  Number of cells on node 41: 483 
  Number of cells on node 43: 483 
  Number of cells on node 21: 483 
  Number of cells on node 40: 483 
  Number of cells on node 35: 483 
  Number of cells on node 11: 483 
  Number of cells on node 42: 483 
  Number of cells on node 46: 483 
  Number of cells on node 73: 482 
  Number of cells on node 32: 483 
  Number of cells on node 10: 483 
  Number of connections on node 20: 101224 
  Number of synaptic contacts on node 20: 949967 
  Number of connections on node 75: 104187 
  Number of synaptic contacts on node 75: 983703 
  Number of connections on node 66: 101461 
  Number of synaptic contacts on node 66: 950087 
  Number of connections on node 1: 102397 
  Number of synaptic contacts on node 1: 965355 
  Number of connections on node 23: 102991 
  Number of synaptic contacts on node 23: 971504 
  Number of connections on node 10: 102612 
  Number of synaptic contacts on node 10: 967896 
  Number of connections on node 8: 102636 
  Number of synaptic contacts on node 8: 966990 
  Number of connections on node 18: 102136 
  Number of synaptic contacts on node 18: 953505 
  Number of connections on node 63: 103141 
  Number of synaptic contacts on node 63: 968173 
  Number of connections on node 27: 101783 
  Number of synaptic contacts on node 27: 963558 
  Number of connections on node 47: 103075 
  Number of synaptic contacts on node 47: 973171 
  Number of connections on node 36: 103016 
  Number of synaptic contacts on node 36: 975470 
  Number of connections on node 32: 99846 
  Number of synaptic contacts on node 32: 936720 
  Number of connections on node 56: 102234 
  Number of synaptic contacts on node 56: 963176 
  Number of connections on node 28: 102057 
  Number of synaptic contacts on node 28: 959677 
  Number of connections on node 78: 102119 
  Number of synaptic contacts on node 78: 961162 
  Number of connections on node 48: 101771 
  Number of synaptic contacts on node 48: 965833 
  Number of connections on node 71: 99813 
  Number of synaptic contacts on node 71: 937142 
  Number of connections on node 7: 103032 
  Number of synaptic contacts on node 7: 971134 
  Number of connections on node 4: 102443 
  Number of synaptic contacts on node 4: 967078 
  Number of connections on node 0: 102131 
  Number of synaptic contacts on node 0: 964774 
  Number of connections on node 6: 101188 
  Number of synaptic contacts on node 6: 957230 
  Number of connections on node 45: 102902 
  Number of synaptic contacts on node 45: 974048 
  Number of connections on node 68: 102832 
  Number of synaptic contacts on node 68: 962734 
  Number of connections on node 60: 101913 
  Number of synaptic contacts on node 60: 962160 
  Number of connections on node 34: 101751 
  Number of synaptic contacts on node 34: 962897 
  Number of connections on node 5: 99893 
  Number of synaptic contacts on node 5: 941074 
  Number of connections on node 74: 102920 
  Number of synaptic contacts on node 74: 963833 
  Number of connections on node 76: 104435 
  Number of synaptic contacts on node 76: 983758 
  Number of connections on node 11: 102800 
  Number of synaptic contacts on node 11: 967228 
  Number of connections on node 17: 102045 
  Number of synaptic contacts on node 17: 956485 
  Number of connections on node 49: 101637 
  Number of synaptic contacts on node 49: 962925 
  Number of connections on node 12: 101857 
  Number of synaptic contacts on node 12: 960103 
  Number of connections on node 30: 101357 
  Number of synaptic contacts on node 30: 959730 
  Number of connections on node 54: 103153 
  Number of synaptic contacts on node 54: 975306 
  Number of connections on node 24: 103605 
  Number of synaptic contacts on node 24: 982180 
  Number of connections on node 77: 103954 
  Number of synaptic contacts on node 77: 982606 
  Number of connections on node 35: 100635 
  Number of synaptic contacts on node 35: 945844 
  Number of connections on node 59: 103208 
  Number of synaptic contacts on node 59: 973664 
  Number of connections on node 52: 102912 
  Number of synaptic contacts on node 52: 970063 
  Number of connections on node 19: 101882 
  Number of synaptic contacts on node 19: 955734 
  Number of connections on node 72: 102331 
  Number of synaptic contacts on node 72: 963504 
  Number of connections on node 50: 100232 
  Number of synaptic contacts on node 50: 950727 
  Number of connections on node 58: 102954 
  Number of synaptic contacts on node 58: 970255 
  Number of connections on node 62: 101389 
  Number of synaptic contacts on node 62: 952905 
  Number of connections on node 79: 102496 
  Number of synaptic contacts on node 79: 964927 
  Number of connections on node 2: 101981 
  Number of synaptic contacts on node 2: 963231 
  Number of connections on node 51: 103005 
  Number of synaptic contacts on node 51: 967967 
  Number of connections on node 22: 100174 
  Number of synaptic contacts on node 22: 948210 
  Number of connections on node 16: 102112 
  Number of synaptic contacts on node 16: 960230 
  Number of connections on node 55: 102415 
  Number of synaptic contacts on node 55: 965016 
  Number of connections on node 41: 102390 
  Number of synaptic contacts on node 41: 968039 
  Number of connections on node 21: 103112 
  Number of synaptic contacts on node 21: 969376 
  Number of connections on node 38: 101357 
  Number of synaptic contacts on node 38: 957640 
  Number of connections on node 26: 100899 
  Number of synaptic contacts on node 26: 958943 
  Number of connections on node 42: 102462 
  Number of synaptic contacts on node 42: 962948 
  Number of connections on node 13: 101332 
  Number of synaptic contacts on node 13: 952416 
  Number of connections on node 46: 100734 
  Number of synaptic contacts on node 46: 955373 
  Number of connections on node 40: 103481 
  Number of synaptic contacts on node 40: 977135 
  Number of connections on node 64: 103171 
  Number of synaptic contacts on node 64: 973544 
  Number of connections on node 69: 101059 
  Number of synaptic contacts on node 69: 949275 
  Number of connections on node 57: 103664 
  Number of synaptic contacts on node 57: 982817 
  Number of connections on node 29: 102255 
  Number of synaptic contacts on node 29: 963897 
  Number of connections on node 14: 101905 
  Number of synaptic contacts on node 14: 964344 
  Number of connections on node 53: 102906 
  Number of synaptic contacts on node 53: 971941 
  Number of connections on node 39: 101320 
  Number of synaptic contacts on node 39: 952252 
  Number of connections on node 15: 101565 
  Number of synaptic contacts on node 15: 955864 
  Number of connections on node 44: 102797 
  Number of synaptic contacts on node 44: 970599 
  Number of connections on node 70: 102753 
  Number of synaptic contacts on node 70: 970492 
  Number of connections on node 25: 102279 
  Number of synaptic contacts on node 25: 970542 
  Number of connections on node 9: 102441 
  Number of synaptic contacts on node 9: 964139 
  Number of connections on node 61: 101880 
  Number of synaptic contacts on node 61: 954909 
  Number of connections on node 73: 103523 
  Number of synaptic contacts on node 73: 982927 
  Number of connections on node 31: 100942 
  Number of synaptic contacts on node 31: 951082 
  Number of connections on node 67: 104215 
  Number of synaptic contacts on node 67: 978681 
  Number of connections on node 43: 102898 
  Number of synaptic contacts on node 43: 970746 
  Number of connections on node 65: 101635 
  Number of synaptic contacts on node 65: 953173 
  Number of connections on node 33: 102404 
  Number of synaptic contacts on node 33: 968926 
  Number of connections on node 3: 100496 
  Number of synaptic contacts on node 3: 944783 
  Number of connections on node 37: 103855 
  Number of synaptic contacts on node 37: 982273 
  Done; cell connection time = 19867.81 s.
Adding stims...
  Number of stims on node 10: 3973 
  Number of stims on node 0: 3973 
  Number of stims on node 30: 3974 
  Number of stims on node 34: 3974 
  Number of stims on node 74: 3963 
  Number of stims on node 29: 3974 
  Number of stims on node 2: 3973 
  Number of stims on node 66: 3963 
  Number of stims on node 67: 3963 
  Number of stims on node 18: 3973 
  Number of stims on node 63: 3973 
  Number of stims on node 9: 3973 
  Number of stims on node 24: 3974 
  Number of stims on node 78: 3963 
  Number of stims on node 33: 3974 
  Number of stims on node 14: 3973 
  Number of stims on node 60: 3973 
  Number of stims on node 7: 3973 
  Number of stims on node 12: 3973 
  Number of stims on node 28: 3974 
  Number of stims on node 43: 3974 
  Number of stims on node 1: 3973 
  Number of stims on node 73: 3963 
  Number of stims on node 39: 3974 
  Number of stims on node 8: 3973 
  Number of stims on node 44: 3974 
  Number of stims on node 32: 3974 
  Number of stims on node 53: 3973 
  Number of stims on node 41: 3974 
  Number of stims on node 52: 3973 
  Number of stims on node 27: 3974 
  Number of stims on node 45: 3974 
  Number of stims on node 11: 3973 
  Number of stims on node 25: 3974 
  Number of stims on node 19: 3973 
  Number of stims on node 68: 3963 
  Number of stims on node 23: 3974 
  Number of stims on node 76: 3963 
  Number of stims on node 6: 3973 
  Number of stims on node 5: 3973 
  Number of stims on node 51: 3974 
  Number of stims on node 42: 3974 
  Number of stims on node 17: 3973 
  Number of stims on node 56: 3973 
  Number of stims on node 4: 3973 
  Number of stims on node 31: 3974 
  Number of stims on node 35: 3974 
  Number of stims on node 72: 3963 
  Number of stims on node 65: 3973 
  Number of stims on node 21: 3974 
  Number of stims on node 57: 3973 
  Number of stims on node 3: 3973 
  Number of stims on node 46: 3974 
  Number of stims on node 38: 3974 
  Number of stims on node 37: 3974 
  Number of stims on node 26: 3974 
  Number of stims on node 62: 3973 
  Number of stims on node 71: 3963 
  Number of stims on node 64: 3973 
  Number of stims on node 54: 3973 
  Number of stims on node 22: 3974 
  Number of stims on node 55: 3973 
  Number of stims on node 77: 3963 
  Number of stims on node 69: 3963 
  Number of stims on node 16: 3973 
  Number of stims on node 79: 3963 
  Number of stims on node 36: 3974 
  Number of stims on node 47: 3974 
  Number of stims on node 49: 3974 
  Number of stims on node 59: 3973 
  Number of stims on node 50: 3974 
  Number of stims on node 61: 3973 
  Number of stims on node 75: 3963 
  Number of stims on node 15: 3973 
  Number of stims on node 13: 3973 
  Number of stims on node 70: 3963 
  Number of stims on node 58: 3973 
  Number of stims on node 20: 3973 
  Number of stims on node 40: 3974 
  Number of stims on node 48: 3974 
  Done; cell stims creation time = 11.03 s.
Recording 0 traces of 0 types on node 25
Recording 1 traces of 1 types on node 3
Recording 1 traces of 1 types on node 0
Recording 2 traces of 1 types on node 66
Recording 1 traces of 1 types on node 7
Recording 1 traces of 1 types on node 34
Recording 0 traces of 0 types on node 6
Recording 1 traces of 1 types on node 10
Recording 0 traces of 0 types on node 35
Recording 0 traces of 0 types on node 64
Recording 1 traces of 1 types on node 22
Recording 0 traces of 0 types on node 63
Recording 0 traces of 0 types on node 24
Recording 0 traces of 0 types on node 79
Recording 2 traces of 1 types on node 68
Recording 0 traces of 0 types on node 28
Recording 1 traces of 1 types on node 29
Recording 2 traces of 1 types on node 26
Recording 1 traces of 1 types on node 47
Recording 0 traces of 0 types on node 48
Recording 1 traces of 1 types on node 21
Recording 0 traces of 0 types on node 61
Recording 1 traces of 1 types on node 16
Recording 1 traces of 1 types on node 14
Recording 1 traces of 1 types on node 32
Recording 0 traces of 0 types on node 52
Recording 0 traces of 0 types on node 56
Recording 0 traces of 0 types on node 43
Recording 0 traces of 0 types on node 20
Recording 1 traces of 1 types on node 60
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 69
Recording 1 traces of 1 types on node 55
Recording 0 traces of 0 types on node 45
Recording 2 traces of 1 types on node 54
Recording 2 traces of 1 types on node 70
Recording 0 traces of 0 types on node 78
Recording 0 traces of 0 types on node 39
Recording 1 traces of 1 types on node 44
Recording 2 traces of 1 types on node 58
Recording 0 traces of 0 types on node 77
Recording 1 traces of 1 types on node 12
Recording 0 traces of 0 types on node 33
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 41
Recording 2 traces of 1 types on node 13
Recording 2 traces of 1 types on node 42
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 17
Recording 1 traces of 1 types on node 62
Recording 1 traces of 1 types on node 73
Recording 0 traces of 0 types on node 49
Recording 1 traces of 1 types on node 59
Recording 0 traces of 0 types on node 9
Recording 1 traces of 1 types on node 36
Recording 0 traces of 0 types on node 15
Recording 1 traces of 1 types on node 74
Recording 0 traces of 0 types on node 53
Recording 2 traces of 1 types on node 11
Recording 1 traces of 1 types on node 23
Recording 1 traces of 1 types on node 5
Recording 0 traces of 0 types on node 75
Recording 0 traces of 0 types on node 65
Recording 1 traces of 1 types on node 67
Recording 1 traces of 1 types on node 38
Recording 0 traces of 0 types on node 19
Recording 1 traces of 1 types on node 2
Recording 3 traces of 1 types on node 18
Recording 1 traces of 1 types on node 37
Recording 2 traces of 1 types on node 46
Recording 1 traces of 1 types on node 76
Recording 0 traces of 0 types on node 71
Recording 2 traces of 1 types on node 72
Recording 2 traces of 1 types on node 57
Recording 1 traces of 1 types on node 30
Recording 1 traces of 1 types on node 51
Recording 1 traces of 1 types on node 40
Recording 3 traces of 1 types on node 50
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 43243.85 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 13.16 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 177839 (2.30 Hz)
  Simulated time: 2.0 s; 80 workers
  Run time: 43243.85 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.007 Hz
   L1_NGC-SA : 0.029 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.179 Hz
   L23_BTC : 0.062 Hz
   L23_ChC : 0.369 Hz
   L23_DBC : 0.066 Hz
   L23_LBC : 0.719 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.218 Hz
   L23_NGC : 0.027 Hz
   L23_PC : 0.095 Hz
   L23_SBC : 0.783 Hz
   L4_BP : 1.625 Hz
   L4_BTC : 0.675 Hz
   L4_ChC : 0.438 Hz
   L4_DBC : 0.325 Hz
   L4_LBC : 2.566 Hz
   L4_MC : 0.008 Hz
   L4_NBC : 4.000 Hz
   L4_NGC : 0.083 Hz
   L4_PC : 0.492 Hz
   L4_SBC : 3.217 Hz
   L4_SP : 0.707 Hz
   L4_SS : 0.780 Hz
   L5_BP : 4.544 Hz
   L5_BTC : 1.079 Hz
   L5_ChC : 3.711 Hz
   L5_DBC : 0.745 Hz
   L5_LBC : 5.783 Hz
   L5_MC : 0.066 Hz
   L5_NBC : 5.331 Hz
   L5_NGC : 8.188 Hz
   L5_SBC : 5.520 Hz
   L5_STPC : 0.737 Hz
   L5_TTPC1 : 0.886 Hz
   L5_TTPC2 : 0.836 Hz
   L5_UTPC : 0.885 Hz
   L6_BPC : 0.763 Hz
   L6_BP : 3.957 Hz
   L6_BTC : 2.731 Hz
   L6_ChC : 4.156 Hz
   L6_DBC : 1.839 Hz
   L6_IPC : 1.440 Hz
   L6_LBC : 5.713 Hz
   L6_MC : 0.101 Hz
   L6_NBC : 5.657 Hz
   L6_NGC : 7.353 Hz
   L6_SBC : 5.336 Hz
   L6_TPC_L1 : 0.978 Hz
   L6_TPC_L4 : 1.369 Hz
   L6_UTPC : 1.366 Hz
   ss_RTN_o : 10.650 Hz
   ss_RTN_m : 12.173 Hz
   ss_RTN_i : 10.677 Hz
   VPL_sTC : 5.224 Hz
   VPM_sTC : 5.634 Hz
   POm_sTC_s1 : 7.436 Hz
Saving output as ../data/v5_batch5/v5_batch5_0_0.json  ... 
Finished saving!
  Done; saving time = 2.99 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 188.98 s

Total time = 63387.28 s

End time:  2021-07-12 17:24:44.780415
