numprocs=64

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch4/v6_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py

Start time:  2021-12-13 22:14:46.574239
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py
Importing netParams from ../data/v6_batch4/v6_batch4_netParams.py

Creating network of 213 cell populations on 64 hosts...
  Number of cells on node 24: 603 
  Number of cells on node 44: 603 
  Number of cells on node 46: 603 
  Number of cells on node 32: 603 
  Number of cells on node 54: 603 
  Number of cells on node 21: 603 
  Number of cells on node 56: 603 
  Number of cells on node 9: 604 
  Number of cells on node 29: 603 
  Number of cells on node 58: 603 
  Number of cells on node 27: 603 
  Number of cells on node 8: 604 
  Number of cells on node 34: 603 
  Number of cells on node 41: 603 
  Number of cells on node 43: 603 
  Number of cells on node 2: 604 
  Number of cells on node 35: 603 
  Number of cells on node 45: 603 
  Number of cells on node 48: 603 
  Number of cells on node 37: 603 
  Number of cells on node 61: 603 
  Number of cells on node 40: 603 
  Number of cells on node 1: 604 
  Number of cells on node 23: 603 
  Number of cells on node 51: 603 
  Number of cells on node 3: 604 
  Number of cells on node 10: 604 
  Number of cells on node 55: 603 
  Number of cells on node 19: 604 
  Number of cells on node 60: 603 
  Number of cells on node 39: 603 
  Number of cells on node 15: 604 
  Number of cells on node 36: 603 
  Number of cells on node 7: 604 
  Number of cells on node 62: 603 
  Number of cells on node 26: 603 
  Number of cells on node 53: 603 
  Number of cells on node 13: 604 
  Number of cells on node 52: 603 
  Number of cells on node 50: 603 
  Number of cells on node 14: 604 
  Number of cells on node 4: 604 
  Number of cells on node 12: 604 
  Number of cells on node 20: 603 
  Number of cells on node 16: 604 
  Number of cells on node 28: 603 
  Number of cells on node 38: 603 
  Number of cells on node 11: 604 
  Number of cells on node 42: 603 
  Number of cells on node 22: 603 
  Number of cells on node 0: 604 
  Done; cell creation time = 37.57 s.
Making connections...
  Number of cells on node 31: 603 
  Number of cells on node 63: 603 
  Number of cells on node 47: 603 
  Number of cells on node 30: 603 
  Number of cells on node 5: 604 
  Number of cells on node 49: 603 
  Number of cells on node 18: 604 
  Number of cells on node 57: 603 
  Number of cells on node 17: 604 
  Number of cells on node 33: 603 
  Number of cells on node 25: 603 
  Number of cells on node 6: 604 
  Number of cells on node 59: 603 
  Number of connections on node 12: 153092 
  Number of synaptic contacts on node 12: 797592 
  Number of connections on node 38: 152043 
  Number of synaptic contacts on node 38: 785252 
  Number of connections on node 16: 153055 
  Number of synaptic contacts on node 16: 791357 
  Number of connections on node 10: 153073 
  Number of synaptic contacts on node 10: 790831 
  Number of connections on node 2: 154110 
  Number of synaptic contacts on node 2: 799396 
  Number of connections on node 60: 151928 
  Number of synaptic contacts on node 60: 781791 
  Number of connections on node 8: 154867 
  Number of synaptic contacts on node 8: 800454 
  Number of connections on node 6: 154536 
  Number of synaptic contacts on node 6: 798747 
  Number of connections on node 22: 154686 
  Number of synaptic contacts on node 22: 801916 
  Number of connections on node 18: 155332 
  Number of synaptic contacts on node 18: 800234 
  Number of connections on node 44: 154039 
  Number of synaptic contacts on node 44: 795905 
  Number of connections on node 4: 154610 
  Number of synaptic contacts on node 4: 798450 
  Number of connections on node 20: 150296 
  Number of synaptic contacts on node 20: 777883 
  Number of connections on node 42: 156281 
  Number of synaptic contacts on node 42: 805245 
  Number of connections on node 28: 154514 
  Number of synaptic contacts on node 28: 799544 
  Number of connections on node 36: 152517 
  Number of synaptic contacts on node 36: 787493 
  Number of connections on node 46: 152089 
  Number of synaptic contacts on node 46: 785129 
  Number of connections on node 3: 152772 
  Number of synaptic contacts on node 3: 787991 
  Number of connections on node 40: 153066 
  Number of synaptic contacts on node 40: 790507 
  Number of connections on node 58: 155073 
  Number of synaptic contacts on node 58: 804762 
  Number of connections on node 32: 153170 
  Number of synaptic contacts on node 32: 790844 
  Number of connections on node 0: 152290 
  Number of synaptic contacts on node 0: 788849 
  Number of connections on node 14: 152569 
  Number of synaptic contacts on node 14: 789463 
  Number of connections on node 30: 152517 
  Number of synaptic contacts on node 30: 787240 
  Number of connections on node 62: 152409 
  Number of synaptic contacts on node 62: 790150 
  Number of connections on node 54: 152966 
  Number of synaptic contacts on node 54: 789444 
  Number of connections on node 52: 152704 
  Number of synaptic contacts on node 52: 789205 
  Number of connections on node 13: 156790 
  Number of synaptic contacts on node 13: 810034 
  Number of connections on node 7: 153144 
  Number of synaptic contacts on node 7: 791016 
  Number of connections on node 15: 154340 
  Number of synaptic contacts on node 15: 796964 
  Number of connections on node 50: 150790 
  Number of synaptic contacts on node 50: 778377 
  Number of connections on node 24: 152276 
  Number of synaptic contacts on node 24: 786655 
  Number of connections on node 48: 151588 
  Number of synaptic contacts on node 48: 785486 
  Number of connections on node 49: 154369 
  Number of synaptic contacts on node 49: 798280 
  Number of connections on node 51: 151671 
  Number of synaptic contacts on node 51: 782294 
  Number of connections on node 5: 153659 
  Number of synaptic contacts on node 5: 793287 
  Number of connections on node 19: 152371 
  Number of synaptic contacts on node 19: 788280 
  Number of connections on node 41: 153156 
  Number of synaptic contacts on node 41: 789366 
  Number of connections on node 31: 153398 
  Number of synaptic contacts on node 31: 790689 
  Number of connections on node 56: 154614 
  Number of synaptic contacts on node 56: 801244 
  Number of connections on node 47: 152281 
  Number of synaptic contacts on node 47: 786985 
  Number of connections on node 17: 153850 
  Number of synaptic contacts on node 17: 793664 
  Number of connections on node 23: 155598 
  Number of synaptic contacts on node 23: 805446 
  Number of connections on node 34: 156172 
  Number of synaptic contacts on node 34: 809585 
  Number of connections on node 9: 153965 
  Number of synaptic contacts on node 9: 800796 
  Number of connections on node 57: 152495 
  Number of synaptic contacts on node 57: 784102 
  Number of connections on node 1: 154215 
  Number of synaptic contacts on node 1: 797149 
  Number of connections on node 26: 155181 
  Number of synaptic contacts on node 26: 802821 
  Number of connections on node 39: 153948 
  Number of synaptic contacts on node 39: 795220 
  Number of connections on node 61: 153334 
  Number of synaptic contacts on node 61: 793712 
  Number of connections on node 37: 152160 
  Number of synaptic contacts on node 37: 786276 
  Number of connections on node 63: 155109 
  Number of synaptic contacts on node 63: 801196 
  Number of connections on node 53: 154232 
  Number of synaptic contacts on node 53: 797705 
  Number of connections on node 33: 155070 
  Number of synaptic contacts on node 33: 800630 
  Number of connections on node 27: 152472 
  Number of synaptic contacts on node 27: 789780 
  Number of connections on node 43: 151293 
  Number of synaptic contacts on node 43: 779532 
  Number of connections on node 21: 152526 
  Number of synaptic contacts on node 21: 787190 
  Number of connections on node 35: 152523 
  Number of synaptic contacts on node 35: 790045 
  Number of connections on node 55: 153268 
  Number of synaptic contacts on node 55: 794358 
  Number of connections on node 11: 153052 
  Number of synaptic contacts on node 11: 791730 
  Number of connections on node 45: 153410 
  Number of synaptic contacts on node 45: 789362 
  Number of connections on node 59: 155053 
  Number of synaptic contacts on node 59: 800636 
  Number of connections on node 25: 153854 
  Number of synaptic contacts on node 25: 792886 
  Number of connections on node 29: 152623 
  Number of synaptic contacts on node 29: 785166 
  Done; cell connection time = 19335.80 s.
Adding stims...
  Number of stims on node 15: 4967 
  Number of stims on node 22: 4966 
  Number of stims on node 2: 4967 
  Number of stims on node 40: 4967 
  Number of stims on node 4: 4967 
  Number of stims on node 33: 4966 
  Number of stims on node 11: 4967 
  Number of stims on node 17: 4967 
  Number of stims on node 56: 4957 
  Number of stims on node 36: 4966 
  Number of stims on node 25: 4966 
  Number of stims on node 12: 4967 
  Number of stims on node 41: 4967 
  Number of stims on node 63: 4957 
  Number of stims on node 5: 4967 
  Number of stims on node 18: 4967 
  Number of stims on node 16: 4967 
  Number of stims on node 24: 4966 
  Number of stims on node 9: 4967 
  Number of stims on node 34: 4966 
  Number of stims on node 48: 4967 
  Number of stims on node 10: 4967 
  Number of stims on node 54: 4957 
  Number of stims on node 3: 4967 
  Number of stims on node 55: 4957 
  Number of stims on node 46: 4967 
  Number of stims on node 21: 4966 
  Number of stims on node 49: 4967 
  Number of stims on node 44: 4967 
  Number of stims on node 7: 4967 
  Number of stims on node 27: 4966 
  Number of stims on node 1: 4967 
  Number of stims on node 14: 4967 
  Number of stims on node 53: 4957 
  Number of stims on node 62: 4957 
  Number of stims on node 38: 4967 
  Number of stims on node 30: 4966 
  Number of stims on node 51: 4957 
  Number of stims on node 39: 4967 
  Number of stims on node 57: 4957 
  Number of stims on node 29: 4966 
  Number of stims on node 37: 4967 
  Number of stims on node 59: 4957 
  Number of stims on node 20: 4966 
  Number of stims on node 60: 4957 
  Number of stims on node 6: 4967 
  Number of stims on node 8: 4967 
  Number of stims on node 45: 4967 
  Number of stims on node 0: 4967 
  Number of stims on node 43: 4967 
  Number of stims on node 35: 4966 
  Number of stims on node 32: 4966 
  Number of stims on node 26: 4966 
  Number of stims on node 31: 4966 
  Number of stims on node 50: 4957 
  Number of stims on node 28: 4966 
  Number of stims on node 58: 4957 
  Number of stims on node 19: 4967 
  Number of stims on node 23: 4966 
  Number of stims on node 61: 4957 
  Number of stims on node 47: 4967 
  Number of stims on node 52: 4957 
  Number of stims on node 13: 4967 
  Number of stims on node 42: 4967 
  Done; cell stims creation time = 11.97 s.
Recording 11 traces of 1 types on node 17
Recording 13 traces of 1 types on node 31
Recording 16 traces of 1 types on node 24
Recording 14 traces of 1 types on node 2
Recording 16 traces of 1 types on node 29
Recording 11 traces of 1 types on node 25
Recording 14 traces of 1 types on node 1
Recording 12 traces of 1 types on node 5
Recording 15 traces of 1 types on node 36
Recording 15 traces of 1 types on node 14
Recording 12 traces of 1 types on node 34
Recording 16 traces of 1 types on node 61
Recording 16 traces of 1 types on node 43
Recording 14 traces of 1 types on node 42
Recording 16 traces of 1 types on node 41
Recording 13 traces of 1 types on node 46
Recording 20 traces of 1 types on node 52
Recording 9 traces of 1 types on node 58
Recording 13 traces of 1 types on node 21
Recording 14 traces of 1 types on node 59
Recording 18 traces of 1 types on node 22
Recording 16 traces of 1 types on node 44
Recording 13 traces of 1 types on node 40
Recording 13 traces of 1 types on node 56
Recording 17 traces of 1 types on node 11
Recording 18 traces of 1 types on node 10
Recording 12 traces of 1 types on node 13
Recording 12 traces of 1 types on node 3
Recording 12 traces of 1 types on node 9
Recording 16 traces of 1 types on node 53
Recording 12 traces of 1 types on node 33
Recording 14 traces of 1 types on node 49
Recording 21 traces of 1 types on node 45
Recording 15 traces of 1 types on node 35
Recording 20 traces of 1 types on node 51
Recording 15 traces of 1 types on node 55
Recording 17 traces of 1 types on node 16
Recording 17 traces of 1 types on node 18
Recording 19 traces of 1 types on node 19
Recording 19 traces of 1 types on node 4
Recording 12 traces of 1 types on node 47
Recording 12 traces of 1 types on node 39
Recording 15 traces of 1 types on node 38
Recording 18 traces of 1 types on node 62
Recording 21 traces of 1 types on node 27
Recording 14 traces of 1 types on node 7
Recording 12 traces of 1 types on node 30
Recording 20 traces of 1 types on node 54
Recording 13 traces of 1 types on node 15
Recording 17 traces of 1 types on node 50
Recording 15 traces of 1 types on node 26
Recording 13 traces of 1 types on node 6
Recording 18 traces of 1 types on node 57
Recording 13 traces of 1 types on node 37
Recording 15 traces of 1 types on node 8
Recording 6 traces of 1 types on node 28
Recording 14 traces of 1 types on node 63
Recording 17 traces of 1 types on node 48
Recording 14 traces of 1 types on node 12
Recording 27 traces of 1 types on node 60
Recording 11 traces of 1 types on node 20
Recording 21 traces of 1 types on node 0
Recording 12 traces of 1 types on node 32
Recording 13 traces of 1 types on node 23
0.0s

Running simulation for 5000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
  Done; run time = 97887.80 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 15.60 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 1022182 (5.29 Hz)
  Simulated time: 5.0 s; 64 workers
  Run time: 97887.80 s
   L1_DAC_bNA : 0.105 Hz
   L1_DAC_cNA : 0.087 Hz
   L1_DLAC_cNA : 0.067 Hz
   L1_HAC_bNA : 0.053 Hz
   L1_HAC_cIR : 0.040 Hz
   L1_HAC_cNA : 0.077 Hz
   L1_NGC-DA_bNA : 0.125 Hz
   L1_NGC-DA_cAC : 0.125 Hz
   L1_NGC-DA_cNA : 0.158 Hz
   L1_NGC-DA_cST : 0.100 Hz
   L1_NGC-SA_cNA : 0.162 Hz
   L1_SLAC_bNA : 0.286 Hz
   L1_SLAC_cAC : 0.075 Hz
   L1_SLAC_cNA : 0.074 Hz
   L23_BP_bAC : 2.600 Hz
   L23_BP_bIR : 2.300 Hz
   L23_BP_bNA : 4.800 Hz
   L23_BP_cAC : 4.429 Hz
   L23_BP_cNA : 6.050 Hz
   L23_BP_dST : 4.067 Hz
   L23_BTC_bAC : 0.347 Hz
   L23_BTC_bIR : 0.257 Hz
   L23_BTC_bNA : 0.530 Hz
   L23_BTC_cAC : 0.283 Hz
   L23_BTC_cNA : 0.711 Hz
   L23_ChC_cAC : 2.348 Hz
   L23_ChC_cNA : 1.843 Hz
   L23_ChC_dNA : 0.547 Hz
   L23_DBC_bAC : 1.850 Hz
   L23_DBC_bIR : 0.531 Hz
   L23_DBC_bNA : 2.723 Hz
   L23_DBC_cAC : 2.302 Hz
   L23_LBC_bAC : 0.320 Hz
   L23_LBC_bNA : 6.200 Hz
   L23_LBC_cAC : 1.850 Hz
   L23_LBC_cNA : 2.866 Hz
   L23_LBC_cST : 3.236 Hz
   L23_LBC_dNA : 5.189 Hz
   L23_MC_bAC : 0.020 Hz
   L23_MC_bNA : 0.420 Hz
   L23_MC_cAC : 0.061 Hz
   L23_MC_cNA : 0.097 Hz
   L23_MC_dNA : 0.000 Hz
   L23_NBC_bAC : 0.214 Hz
   L23_NBC_bNA : 2.833 Hz
   L23_NBC_cAC : 0.742 Hz
   L23_NBC_cIR : 0.167 Hz
   L23_NBC_cNA : 0.633 Hz
   L23_NBC_dNA : 1.231 Hz
   L23_NGC_bNA : 0.400 Hz
   L23_NGC_cAC : 0.360 Hz
   L23_NGC_cNA : 0.644 Hz
   L23_NGC_cST : 0.240 Hz
   L23_PC_cAD : 0.591 Hz
   L23_SBC_bNA : 5.327 Hz
   L23_SBC_cAC : 4.657 Hz
   L23_SBC_dNA : 3.517 Hz
   L4_BP_bAC : 9.000 Hz
   L4_BP_bIR : 6.400 Hz
   L4_BP_bNA : 8.000 Hz
   L4_BP_cAC : 5.000 Hz
   L4_BP_cNA : 16.400 Hz
   L4_BP_dST : 0.200 Hz
   L4_BTC_bAC : 4.400 Hz
   L4_BTC_bIR : 1.300 Hz
   L4_BTC_bST : 5.000 Hz
   L4_BTC_cAC : 6.867 Hz
   L4_BTC_cNA : 10.133 Hz
   L4_BTC_dNA : 2.700 Hz
   L4_ChC_cAC : 19.267 Hz
   L4_ChC_cNA : 19.467 Hz
   L4_ChC_dNA : 3.200 Hz
   L4_DBC_bAC : 5.350 Hz
   L4_DBC_bIR : 0.308 Hz
   L4_DBC_bNA : 3.000 Hz
   L4_DBC_bST : 0.400 Hz
   L4_DBC_cAC : 3.700 Hz
   L4_DBC_cIR : 0.771 Hz
   L4_DBC_cNA : 4.950 Hz
   L4_LBC_cAC : 15.009 Hz
   L4_LBC_cNA : 23.929 Hz
   L4_LBC_cST : 16.903 Hz
   L4_LBC_dNA : 25.683 Hz
   L4_LBC_dST : 19.022 Hz
   L4_MC_bAC : 0.091 Hz
   L4_MC_bNA : 0.300 Hz
   L4_MC_cAC : 0.277 Hz
   L4_MC_cNA : 0.467 Hz
   L4_MC_dNA : 0.050 Hz
   L4_NBC_cAC : 14.280 Hz
   L4_NBC_cIR : 9.800 Hz
   L4_NBC_cNA : 28.360 Hz
   L4_NBC_dNA : 21.411 Hz
   L4_NGC_bNA : 7.000 Hz
   L4_NGC_cAC : 5.600 Hz
   L4_NGC_cNA : 6.067 Hz
   L4_NGC_cST : 0.800 Hz
   L4_PC_cAD : 3.376 Hz
   L4_SBC_bNA : 24.667 Hz
   L4_SBC_cAC : 15.636 Hz
   L4_SBC_dNA : 25.588 Hz
   L4_SP_cAD : 4.500 Hz
   L4_SS_cAD : 4.919 Hz
   L5_BP_bAC : 11.000 Hz
   L5_BP_bIR : 4.080 Hz
   L5_BP_bNA : 25.178 Hz
   L5_BP_cAC : 15.978 Hz
   L5_BP_cNA : 32.280 Hz
   L5_BP_dST : 3.133 Hz
   L5_BTC_bAC : 10.154 Hz
   L5_BTC_cAC : 12.800 Hz
   L5_BTC_cNA : 20.846 Hz
   L5_ChC_cAC : 25.914 Hz
   L5_ChC_cNA : 36.514 Hz
   L5_ChC_dNA : 34.600 Hz
   L5_DBC_bAC : 6.133 Hz
   L5_DBC_bIR : 1.341 Hz
   L5_DBC_bNA : 9.289 Hz
   L5_DBC_bST : 3.756 Hz
   L5_DBC_cAC : 10.022 Hz
   L5_DBC_cIR : 2.976 Hz
   L5_DBC_cNA : 14.933 Hz
   L5_LBC_bAC : 11.000 Hz
   L5_LBC_cAC : 20.608 Hz
   L5_LBC_cIR : 6.985 Hz
   L5_LBC_cNA : 42.924 Hz
   L5_LBC_cST : 32.216 Hz
   L5_LBC_dNA : 38.459 Hz
   L5_LBC_dST : 26.890 Hz
   L5_MC_bAC : 2.495 Hz
   L5_MC_bIR : 0.709 Hz
   L5_MC_bST : 1.550 Hz
   L5_MC_cAC : 4.472 Hz
   L5_MC_cNA : 3.825 Hz
   L5_MC_cST : 0.537 Hz
   L5_MC_dNA : 0.963 Hz
   L5_NBC_bAC : 8.943 Hz
   L5_NBC_bIR : 5.043 Hz
   L5_NBC_bST : 24.837 Hz
   L5_NBC_cAC : 24.520 Hz
   L5_NBC_cIR : 14.100 Hz
   L5_NBC_cNA : 37.503 Hz
   L5_NBC_cST : 27.250 Hz
   L5_NBC_dST : 30.215 Hz
   L5_NGC_bNA : 0.200 Hz
   L5_NGC_cAC : 15.600 Hz
   L5_NGC_cNA : 23.960 Hz
   L5_NGC_cST : 4.000 Hz
   L5_SBC_bNA : 26.733 Hz
   L5_SBC_cAC : 14.644 Hz
   L5_SBC_dNA : 47.514 Hz
   L5_STPC_cAD : 7.142 Hz
   L5_TTPC1_cAD : 7.175 Hz
   L5_TTPC2_cAD : 7.486 Hz
   L5_UTPC_cAD : 10.103 Hz
   L6_BPC_cAD : 4.547 Hz
   L6_BP_bAC : 7.767 Hz
   L6_BP_bIR : 2.320 Hz
   L6_BP_bNA : 16.326 Hz
   L6_BP_cAC : 14.368 Hz
   L6_BP_cNA : 24.320 Hz
   L6_BP_dST : 1.567 Hz
   L6_BTC_bAC : 7.500 Hz
   L6_BTC_cAC : 11.288 Hz
   L6_BTC_cNA : 21.860 Hz
   L6_ChC_cAC : 11.200 Hz
   L6_ChC_cNA : 51.867 Hz
   L6_ChC_dNA : 30.900 Hz
   L6_DBC_bAC : 8.400 Hz
   L6_DBC_bIR : 1.460 Hz
   L6_DBC_bNA : 8.000 Hz
   L6_DBC_bST : 3.533 Hz
   L6_DBC_cAC : 11.200 Hz
   L6_DBC_cIR : 4.133 Hz
   L6_DBC_cNA : 7.600 Hz
   L6_IPC_cAD : 4.358 Hz
   L6_LBC_bAC : 7.238 Hz
   L6_LBC_bIR : 4.094 Hz
   L6_LBC_bNA : 54.567 Hz
   L6_LBC_bST : 28.605 Hz
   L6_LBC_cNA : 44.067 Hz
   L6_LBC_cST : 24.870 Hz
   L6_MC_bAC : 0.966 Hz
   L6_MC_bIR : 0.170 Hz
   L6_MC_bNA : 1.886 Hz
   L6_MC_bST : 0.500 Hz
   L6_MC_cAC : 2.853 Hz
   L6_MC_cIR : 0.157 Hz
   L6_MC_cNA : 2.114 Hz
   L6_NBC_bAC : 8.443 Hz
   L6_NBC_bIR : 5.100 Hz
   L6_NBC_bST : 36.348 Hz
   L6_NBC_cAC : 14.149 Hz
   L6_NBC_cIR : 6.100 Hz
   L6_NBC_cNA : 32.141 Hz
   L6_NBC_cST : 27.656 Hz
   L6_NBC_dST : 32.500 Hz
   L6_NGC_bNA : 15.100 Hz
   L6_NGC_cAC : 14.200 Hz
   L6_NGC_cNA : 25.709 Hz
   L6_NGC_cST : 3.700 Hz
   L6_SBC_bNA : 40.592 Hz
   L6_SBC_cAC : 25.158 Hz
   L6_SBC_dNA : 28.000 Hz
   L6_TPC_L1_cAD : 4.617 Hz
   L6_TPC_L4_cAD : 5.482 Hz
   L6_UTPC_cAD : 5.837 Hz
   ss_RTN_o : 10.849 Hz
   ss_RTN_m : 11.369 Hz
   ss_RTN_i : 10.526 Hz
   VPL_sTC : 2.838 Hz
   VPM_sTC : 3.046 Hz
   POm_sTC_s1 : 4.098 Hz
Saving output as ../data/v6_batch4/v6_batch4_0_0.json  ... 
Finished saving!
  Done; saving time = 84.34 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 3034.60 s

Total time = 120621.26 s

End time:  2021-12-15 07:45:07.838326
