numprocs=40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch8/v5_batch8_1_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py

Start time:  2021-07-10 23:00:07.619562
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py
Importing netParams from ../data/v5_batch8/v5_batch8_netParams.py

Creating network of 61 cell populations on 40 hosts...
  Number of cells on node 5: 966 
  Number of cells on node 28: 965 
  Number of cells on node 15: 965 
  Number of cells on node 10: 966 
  Number of cells on node 19: 965 
  Number of cells on node 37: 965 
  Number of cells on node 2: 966 
  Number of cells on node 34: 965 
  Number of cells on node 18: 965 
  Number of cells on node 30: 965 
  Number of cells on node 32: 965 
  Number of cells on node 9: 966 
  Number of cells on node 20: 965 
  Number of cells on node 33: 965 
  Number of cells on node 22: 965 
  Number of cells on node 38: 965 
  Number of cells on node 36: 965 
  Number of cells on node 29: 965 
  Number of cells on node 35: 965 
  Number of cells on node 24: 965 
  Number of cells on node 4: 966 
  Number of cells on node 12: 965 
  Number of cells on node 27: 965 
  Number of cells on node 23: 965 
  Number of cells on node 3: 966 
  Number of cells on node 1: 966 
  Number of cells on node 13: 965 
  Number of cells on node 31: 965 
  Number of cells on node 6: 966 
  Number of cells on node 26: 965 
  Number of cells on node 39: 965 
  Number of cells on node 17: 965 
  Number of cells on node 7: 966 
  Number of cells on node 11: 966 
  Number of cells on node 8: 966 
  Number of cells on node 16: 965 
  Number of cells on node 14: 965 
  Number of cells on node 25: 965 
  Number of cells on node 21: 965 
  Number of cells on node 0: 966 
  Done; cell creation time = 49.26 s.
Making connections...
  Number of connections on node 4: 3775 
  Number of synaptic contacts on node 4: 4505 
  Number of connections on node 8: 3595 
  Number of synaptic contacts on node 8: 4369 
  Number of connections on node 22: 3580 
  Number of synaptic contacts on node 22: 4323 
  Number of connections on node 30: 3577 
  Number of synaptic contacts on node 30: 4294 
  Number of connections on node 33: 3679 
  Number of synaptic contacts on node 33: 4419 
  Number of connections on node 9: 3698 
  Number of synaptic contacts on node 9: 4498 
  Number of connections on node 16: 3710 
  Number of synaptic contacts on node 16: 4412 
  Number of connections on node 26: 3728 
  Number of synaptic contacts on node 26: 4486 
  Number of connections on node 23: 3562 
  Number of synaptic contacts on node 23: 4335 
  Number of connections on node 5: 3489 
  Number of synaptic contacts on node 5: 4310 
  Number of connections on node 37: 3584 
  Number of synaptic contacts on node 37: 4303 
  Number of connections on node 0: 3731 
  Number of synaptic contacts on node 0: 4553 
  Number of connections on node 14: 3674 
  Number of synaptic contacts on node 14: 4432 
  Number of connections on node 34: 3749 
  Number of synaptic contacts on node 34: 4530 
  Number of connections on node 31: 3655 
  Number of synaptic contacts on node 31: 4408 
  Number of connections on node 28: 3539 
  Number of synaptic contacts on node 28: 4313 
  Number of connections on node 20: 3581 
  Number of synaptic contacts on node 20: 4347 
  Number of connections on node 2: 3862 
  Number of synaptic contacts on node 2: 4625 
  Number of connections on node 36: 3812 
  Number of synaptic contacts on node 36: 4558 
  Number of connections on node 12: 3520 
  Number of synaptic contacts on node 12: 4278 
  Number of connections on node 17: 3761 
  Number of synaptic contacts on node 17: 4530 
  Number of connections on node 38: 3511 
  Number of synaptic contacts on node 38: 4214 
  Number of connections on node 21: 3588 
  Number of synaptic contacts on node 21: 4335 
  Number of connections on node 3: 3688 
  Number of synaptic contacts on node 3: 4445 
  Number of connections on node 19: 3625 
  Number of synaptic contacts on node 19: 4362 
  Number of connections on node 6: 3748 
  Number of synaptic contacts on node 6: 4549 
  Number of connections on node 39: 3579 
  Number of synaptic contacts on node 39: 4317 
  Number of connections on node 25: 3482 
  Number of synaptic contacts on node 25: 4221 
  Number of connections on node 27: 3639 
  Number of synaptic contacts on node 27: 4339 
  Number of connections on node 32: 3745 
  Number of synaptic contacts on node 32: 4500 
  Number of connections on node 35: 3513 
  Number of synaptic contacts on node 35: 4233 
  Number of connections on node 15: 3731 
  Number of synaptic contacts on node 15: 4470 
  Number of connections on node 13: 3602 
  Number of synaptic contacts on node 13: 4319 
  Number of connections on node 10: 3525 
  Number of synaptic contacts on node 10: 4311 
  Number of connections on node 29: 3799 
  Number of synaptic contacts on node 29: 4566 
  Number of connections on node 7: 3570 
  Number of synaptic contacts on node 7: 4273 
  Number of connections on node 11: 3798 
  Number of synaptic contacts on node 11: 4625 
  Number of connections on node 24: 3447 
  Number of synaptic contacts on node 24: 4186 
  Number of connections on node 18: 3633 
  Number of synaptic contacts on node 18: 4368 
  Number of connections on node 1: 3566 
  Number of synaptic contacts on node 1: 4344 
  Done; cell connection time = 281.72 s.
Adding stims...
  Number of stims on node 31: 7937 
  Number of stims on node 39: 7937 
  Number of stims on node 22: 7947 
  Number of stims on node 8: 7947 
  Number of stims on node 30: 7937 
  Number of stims on node 16: 7946 
  Number of stims on node 20: 7946 
  Number of stims on node 4: 7947 
  Number of stims on node 18: 7946 
  Number of stims on node 9: 7947 
  Number of stims on node 17: 7946 
  Number of stims on node 33: 7937 
  Number of stims on node 23: 7947 
  Number of stims on node 34: 7937 
  Number of stims on node 21: 7947 
  Number of stims on node 7: 7947 
  Number of stims on node 3: 7947 
  Number of stims on node 37: 7937 
  Number of stims on node 0: 7947 
  Number of stims on node 15: 7946 
  Number of stims on node 14: 7946 
  Number of stims on node 35: 7937 
  Number of stims on node 13: 7946 
  Number of stims on node 38: 7937 
  Number of stims on node 27: 7937 
  Number of stims on node 10: 7947 
  Number of stims on node 36: 7937 
  Number of stims on node 25: 7947 
  Number of stims on node 1: 7947 
  Number of stims on node 2: 7947 
  Number of stims on node 28: 7937 
  Number of stims on node 19: 7946 
  Number of stims on node 12: 7946 
  Number of stims on node 32: 7937 
  Number of stims on node 6: 7947 
  Number of stims on node 29: 7937 
  Number of stims on node 11: 7947 
  Number of stims on node 26: 7937 
  Number of stims on node 5: 7947 
  Number of stims on node 24: 7947 
  Done; cell stims creation time = 11.54 s.
Recording 3 traces of 1 types on node 30
Recording 1 traces of 1 types on node 16
Recording 0 traces of 0 types on node 8
Recording 1 traces of 1 types on node 4
Recording 2 traces of 1 types on node 6
Recording 2 traces of 1 types on node 22
Recording 0 traces of 0 types on node 31
Recording 1 traces of 1 types on node 19
Recording 1 traces of 1 types on node 29
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 1
Recording 2 traces of 1 types on node 36
Recording 0 traces of 0 types on node 35
Recording 1 traces of 1 types on node 3
Recording 1 traces of 1 types on node 15
Recording 0 traces of 0 types on node 24
Recording 3 traces of 1 types on node 14
Recording 1 traces of 1 types on node 20
Recording 2 traces of 1 types on node 17
Recording 2 traces of 1 types on node 34
Recording 0 traces of 0 types on node 39
Recording 5 traces of 1 types on node 18
Recording 3 traces of 1 types on node 11
Recording 3 traces of 1 types on node 32
Recording 1 traces of 1 types on node 21
Recording 0 traces of 0 types on node 9
Recording 1 traces of 1 types on node 23
Recording 2 traces of 1 types on node 13
Recording 4 traces of 1 types on node 26
Recording 2 traces of 1 types on node 0
Recording 1 traces of 1 types on node 27
Recording 2 traces of 1 types on node 28
Recording 1 traces of 1 types on node 37
Recording 1 traces of 1 types on node 5
Recording 1 traces of 1 types on node 38
Recording 1 traces of 1 types on node 12
Recording 2 traces of 1 types on node 7
Recording 3 traces of 1 types on node 2
Recording 4 traces of 1 types on node 10
Recording 1 traces of 1 types on node 33
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 31518.69 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 7.41 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 221995 (2.87 Hz)
  Simulated time: 2.0 s; 40 workers
  Run time: 31518.69 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.000 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.000 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 0.045 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.006 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.165 Hz
   L23_SBC : 0.145 Hz
   L4_BP : 1.500 Hz
   L4_BTC : 0.350 Hz
   L4_ChC : 3.375 Hz
   L4_DBC : 0.013 Hz
   L4_LBC : 4.270 Hz
   L4_MC : 0.000 Hz
   L4_NBC : 6.281 Hz
   L4_NGC : 0.083 Hz
   L4_PC : 0.701 Hz
   L4_SBC : 7.325 Hz
   L4_SP : 1.248 Hz
   L4_SS : 1.784 Hz
   L5_BP : 5.412 Hz
   L5_BTC : 1.967 Hz
   L5_ChC : 12.105 Hz
   L5_DBC : 0.297 Hz
   L5_LBC : 11.836 Hz
   L5_MC : 0.006 Hz
   L5_NBC : 10.716 Hz
   L5_NGC : 8.375 Hz
   L5_SBC : 10.300 Hz
   L5_STPC : 2.591 Hz
   L5_TTPC1 : 1.851 Hz
   L5_TTPC2 : 1.708 Hz
   L5_UTPC : 3.349 Hz
   L6_BPC : 1.239 Hz
   L6_BP : 4.629 Hz
   L6_BTC : 4.343 Hz
   L6_ChC : 17.875 Hz
   L6_DBC : 1.645 Hz
   L6_IPC : 1.858 Hz
   L6_LBC : 10.714 Hz
   L6_MC : 0.006 Hz
   L6_NBC : 13.096 Hz
   L6_NGC : 9.059 Hz
   L6_SBC : 20.679 Hz
   L6_TPC_L1 : 1.566 Hz
   L6_TPC_L4 : 2.065 Hz
   L6_UTPC : 2.361 Hz
   ss_RTN_o : 10.650 Hz
   ss_RTN_m : 12.173 Hz
   ss_RTN_i : 10.677 Hz
   VPL_sTC : 5.224 Hz
   VPM_sTC : 5.634 Hz
   POm_sTC_s1 : 7.436 Hz
Saving output as ../data/v5_batch8/v5_batch8_1_0.json  ... 
Finished saving!
  Done; saving time = 3.28 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 221.60 s

Total time = 32125.14 s

End time:  2021-07-11 07:55:32.760350
--------------------------------------------------------------------------
mpiexec noticed that process rank 5 with PID 64005 on node high-mem exited on signal 15 (Terminated).
--------------------------------------------------------------------------
