numprocs=40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py

Start time:  2021-11-23 03:24:23.516987
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py

Creating network of 213 cell populations on 40 hosts...
  Number of cells on node 10: 966 
  Number of cells on node 7: 966 
  Number of cells on node 24: 965 
  Number of cells on node 9: 966 
  Number of cells on node 35: 965 
  Number of cells on node 32: 965 
  Number of cells on node 20: 965 
  Number of cells on node 19: 965 
  Number of cells on node 16: 965 
  Number of cells on node 29: 965 
  Number of cells on node 2: 966 
  Number of cells on node 15: 965 
  Number of cells on node 4: 966 
  Number of cells on node 39: 965 
  Number of cells on node 30: 965 
  Number of cells on node 22: 965 
  Number of cells on node 28: 965 
  Number of cells on node 25: 965 
  Number of cells on node 26: 965 
  Number of cells on node 18: 965 
  Number of cells on node 11: 966 
  Number of cells on node 34: 965 
  Number of cells on node 3: 966 
  Number of cells on node 17: 965 
  Number of cells on node 21: 965 
  Number of cells on node 6: 966 
  Number of cells on node 5: 966 
  Number of cells on node 0: 966 
  Done; cell creation time = 70.21 s.
Making connections...
  Number of cells on node 23: 965 
  Number of cells on node 33: 965 
  Number of cells on node 14: 965 
  Number of cells on node 36: 965 
  Number of cells on node 37: 965 
  Number of cells on node 12: 965 
  Number of cells on node 27: 965 
  Number of cells on node 8: 966 
  Number of cells on node 1: 966 
  Number of cells on node 13: 965 
  Number of cells on node 38: 965 
  Number of cells on node 31: 965 
  Number of connections on node 6: 492589 
  Number of synaptic contacts on node 6: 1823326 
  Number of connections on node 4: 496190 
  Number of synaptic contacts on node 4: 1837196 
  Number of connections on node 22: 488297 
  Number of synaptic contacts on node 22: 1807654 
  Number of connections on node 19: 496367 
  Number of synaptic contacts on node 19: 1840086 
  Number of connections on node 11: 497066 
  Number of synaptic contacts on node 11: 1845419 
  Number of connections on node 1: 495537 
  Number of synaptic contacts on node 1: 1835321 
  Number of connections on node 0: 496714 
  Number of synaptic contacts on node 0: 1842462 
  Number of connections on node 8: 494869 
  Number of synaptic contacts on node 8: 1834758 
  Number of connections on node 24: 493277 
  Number of synaptic contacts on node 24: 1832271 
  Number of connections on node 5: 493361 
  Number of synaptic contacts on node 5: 1825186 
  Number of connections on node 21: 492650 
  Number of synaptic contacts on node 21: 1828903 
  Number of connections on node 7: 496416 
  Number of synaptic contacts on node 7: 1840445 
  Number of connections on node 15: 494281 
  Number of synaptic contacts on node 15: 1821828 
  Number of connections on node 2: 495142 
  Number of synaptic contacts on node 2: 1830996 
  Number of connections on node 12: 495118 
  Number of synaptic contacts on node 12: 1829610 
  Number of connections on node 9: 494245 
  Number of synaptic contacts on node 9: 1826312 
  Number of connections on node 27: 496412 
  Number of synaptic contacts on node 27: 1835994 
  Number of connections on node 37: 498847 
  Number of synaptic contacts on node 37: 1853460 
  Number of connections on node 26: 493070 
  Number of synaptic contacts on node 26: 1821704 
  Number of connections on node 13: 495118 
  Number of synaptic contacts on node 13: 1834339 
  Number of connections on node 29: 494259 
  Number of synaptic contacts on node 29: 1824688 
  Number of connections on node 10: 493971 
  Number of synaptic contacts on node 10: 1831651 
  Number of connections on node 3: 492930 
  Number of synaptic contacts on node 3: 1815639 
  Number of connections on node 25: 490107 
  Number of synaptic contacts on node 25: 1815586 
  Number of connections on node 36: 497818 
  Number of synaptic contacts on node 36: 1845714 
  Number of connections on node 33: 496393 
  Number of synaptic contacts on node 33: 1845920 
  Number of connections on node 35: 494944 
  Number of synaptic contacts on node 35: 1826820 
  Number of connections on node 17: 496399 
  Number of synaptic contacts on node 17: 1839057 
  Number of connections on node 31: 491950 
  Number of synaptic contacts on node 31: 1818754 
  Number of connections on node 14: 494105 
  Number of synaptic contacts on node 14: 1820804 
  Number of connections on node 18: 495606 
  Number of synaptic contacts on node 18: 1826148 
  Number of connections on node 23: 493424 
  Number of synaptic contacts on node 23: 1833728 
  Number of connections on node 38: 493495 
  Number of synaptic contacts on node 38: 1819486 
  Number of connections on node 39: 494359 
  Number of synaptic contacts on node 39: 1823049 
  Number of connections on node 20: 493931 
  Number of synaptic contacts on node 20: 1823984 
  Number of connections on node 34: 494914 
  Number of synaptic contacts on node 34: 1825759 
  Number of connections on node 32: 492336 
  Number of synaptic contacts on node 32: 1809912 
  Number of connections on node 30: 495303 
  Number of synaptic contacts on node 30: 1835735 
  Number of connections on node 28: 496184 
  Number of synaptic contacts on node 28: 1835319 
  Done; cell connection time = 15539.85 s.
  Number of connections on node 16: 495304 
  Number of synaptic contacts on node 16: 1832090 
Adding stims...
  Number of stims on node 7: 7947 
  Number of stims on node 34: 7937 
  Number of stims on node 10: 7947 
  Number of stims on node 3: 7947 
  Number of stims on node 26: 7937 
  Number of stims on node 35: 7937 
  Number of stims on node 18: 7946 
  Number of stims on node 9: 7947 
  Number of stims on node 5: 7947 
  Number of stims on node 6: 7947 
  Number of stims on node 17: 7946 
  Number of stims on node 23: 7947 
  Number of stims on node 12: 7946 
  Number of stims on node 20: 7946 
  Number of stims on node 29: 7937 
  Number of stims on node 33: 7937 
  Number of stims on node 11: 7947 
  Number of stims on node 1: 7947 
  Number of stims on node 27: 7937 
  Number of stims on node 39: 7937 
  Number of stims on node 32: 7937 
  Number of stims on node 21: 7947 
  Number of stims on node 2: 7947 
  Number of stims on node 16: 7946 
  Number of stims on node 15: 7946 
  Number of stims on node 37: 7937 
  Number of stims on node 31: 7937 
  Number of stims on node 19: 7946 
  Number of stims on node 28: 7937 
  Number of stims on node 30: 7937 
  Number of stims on node 22: 7947 
  Number of stims on node 0: 7947 
  Number of stims on node 36: 7937 
  Number of stims on node 25: 7947 
  Number of stims on node 4: 7947 
  Number of stims on node 14: 7946 
  Number of stims on node 8: 7947 
  Number of stims on node 38: 7937 
  Number of stims on node 24: 7947 
  Number of stims on node 13: 7946 
  Done; cell stims creation time = 9.15 s.
Recording 20 traces of 1 types on node 7
Recording 19 traces of 1 types on node 9
Recording 26 traces of 1 types on node 16
Recording 21 traces of 1 types on node 19
Recording 26 traces of 1 types on node 26
Recording 22 traces of 1 types on node 10
Recording 22 traces of 1 types on node 23
Recording 20 traces of 1 types on node 39
Recording 23 traces of 1 types on node 0
Recording 27 traces of 1 types on node 35
Recording 26 traces of 1 types on node 3
Recording 29 traces of 1 types on node 11
Recording 30 traces of 1 types on node 5
Recording 27 traces of 1 types on node 14
Recording 23 traces of 1 types on node 36
Recording 23 traces of 1 types on node 32
Recording 26 traces of 1 types on node 15
Recording 23 traces of 1 types on node 30
Recording 18 traces of 1 types on node 31
Recording 21 traces of 1 types on node 21
Recording 28 traces of 1 types on node 12
Recording 26 traces of 1 types on node 2
Recording 29 traces of 1 types on node 4
Recording 26 traces of 1 types on node 20
Recording 25 traces of 1 types on node 22
Recording 20 traces of 1 types on node 18
Recording 29 traces of 1 types on node 33
Recording 26 traces of 1 types on node 8
Recording 21 traces of 1 types on node 25
Recording 25 traces of 1 types on node 29
Recording 25 traces of 1 types on node 6
Recording 22 traces of 1 types on node 28
Recording 31 traces of 1 types on node 27
Recording 22 traces of 1 types on node 34
Recording 17 traces of 1 types on node 1
Recording 22 traces of 1 types on node 13
Recording 21 traces of 1 types on node 37
Recording 26 traces of 1 types on node 24
Recording 24 traces of 1 types on node 38
Recording 22 traces of 1 types on node 17
0.0s

Running simulation for 5000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
  Done; run time = 133538.97 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 17.96 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 1647322 (8.53 Hz)
  Simulated time: 5.0 s; 40 workers
  Run time: 133538.97 s
   L1_DAC_bNA : 0.221 Hz
   L1_DAC_cNA : 0.205 Hz
   L1_DLAC_cNA : 0.192 Hz
   L1_HAC_bNA : 0.263 Hz
   L1_HAC_cIR : 0.260 Hz
   L1_HAC_cNA : 0.187 Hz
   L1_NGC-DA_bNA : 0.400 Hz
   L1_NGC-DA_cAC : 0.300 Hz
   L1_NGC-DA_cNA : 0.329 Hz
   L1_NGC-DA_cST : 0.300 Hz
   L1_NGC-SA_cNA : 0.342 Hz
   L1_SLAC_bNA : 0.429 Hz
   L1_SLAC_cAC : 0.375 Hz
   L1_SLAC_cNA : 0.274 Hz
   L23_BP_bAC : 1.800 Hz
   L23_BP_bIR : 1.650 Hz
   L23_BP_bNA : 5.914 Hz
   L23_BP_cAC : 3.229 Hz
   L23_BP_cNA : 6.000 Hz
   L23_BP_dST : 3.333 Hz
   L23_BTC_bAC : 0.413 Hz
   L23_BTC_bIR : 0.229 Hz
   L23_BTC_bNA : 1.478 Hz
   L23_BTC_cAC : 1.078 Hz
   L23_BTC_cNA : 1.000 Hz
   L23_ChC_cAC : 2.122 Hz
   L23_ChC_cNA : 2.209 Hz
   L23_ChC_dNA : 0.893 Hz
   L23_DBC_bAC : 0.950 Hz
   L23_DBC_bIR : 0.738 Hz
   L23_DBC_bNA : 3.920 Hz
   L23_DBC_cAC : 2.144 Hz
   L23_LBC_bAC : 0.366 Hz
   L23_LBC_bNA : 6.437 Hz
   L23_LBC_cAC : 2.181 Hz
   L23_LBC_cNA : 3.037 Hz
   L23_LBC_cST : 3.727 Hz
   L23_LBC_dNA : 4.670 Hz
   L23_MC_bAC : 0.220 Hz
   L23_MC_bNA : 0.860 Hz
   L23_MC_cAC : 0.507 Hz
   L23_MC_cNA : 0.473 Hz
   L23_MC_dNA : 0.340 Hz
   L23_NBC_bAC : 0.314 Hz
   L23_NBC_bNA : 2.167 Hz
   L23_NBC_cAC : 1.018 Hz
   L23_NBC_cIR : 0.467 Hz
   L23_NBC_cNA : 1.052 Hz
   L23_NBC_dNA : 1.266 Hz
   L23_NGC_bNA : 1.160 Hz
   L23_NGC_cAC : 1.160 Hz
   L23_NGC_cNA : 1.005 Hz
   L23_NGC_cST : 0.240 Hz
   L23_PC_cAD : 0.546 Hz
   L23_SBC_bNA : 6.287 Hz
   L23_SBC_cAC : 4.267 Hz
   L23_SBC_dNA : 3.804 Hz
   L4_BP_bAC : 2.200 Hz
   L4_BP_bIR : 2.400 Hz
   L4_BP_bNA : 12.800 Hz
   L4_BP_cAC : 3.900 Hz
   L4_BP_cNA : 9.200 Hz
   L4_BP_dST : 5.400 Hz
   L4_BTC_bAC : 2.500 Hz
   L4_BTC_bIR : 1.000 Hz
   L4_BTC_bST : 5.600 Hz
   L4_BTC_cAC : 5.844 Hz
   L4_BTC_cNA : 10.933 Hz
   L4_BTC_dNA : 3.500 Hz
   L4_ChC_cAC : 15.467 Hz
   L4_ChC_cNA : 12.133 Hz
   L4_ChC_dNA : 2.900 Hz
   L4_DBC_bAC : 1.850 Hz
   L4_DBC_bIR : 0.738 Hz
   L4_DBC_bNA : 5.650 Hz
   L4_DBC_bST : 1.750 Hz
   L4_DBC_cAC : 3.800 Hz
   L4_DBC_cIR : 1.857 Hz
   L4_DBC_cNA : 7.400 Hz
   L4_LBC_cAC : 12.155 Hz
   L4_LBC_cNA : 18.657 Hz
   L4_LBC_cST : 14.587 Hz
   L4_LBC_dNA : 19.839 Hz
   L4_LBC_dST : 16.933 Hz
   L4_MC_bAC : 0.218 Hz
   L4_MC_bNA : 0.750 Hz
   L4_MC_cAC : 0.993 Hz
   L4_MC_cNA : 0.956 Hz
   L4_MC_dNA : 0.600 Hz
   L4_NBC_cAC : 12.720 Hz
   L4_NBC_cIR : 8.320 Hz
   L4_NBC_cNA : 22.778 Hz
   L4_NBC_dNA : 17.889 Hz
   L4_NGC_bNA : 8.200 Hz
   L4_NGC_cAC : 5.000 Hz
   L4_NGC_cNA : 4.533 Hz
   L4_NGC_cST : 1.400 Hz
   L4_PC_cAD : 2.102 Hz
   L4_SBC_bNA : 26.162 Hz
   L4_SBC_cAC : 11.855 Hz
   L4_SBC_dNA : 22.988 Hz
   L4_SP_cAD : 2.880 Hz
   L4_SS_cAD : 3.234 Hz
   L5_BP_bAC : 3.133 Hz
   L5_BP_bIR : 1.560 Hz
   L5_BP_bNA : 18.889 Hz
   L5_BP_cAC : 4.756 Hz
   L5_BP_cNA : 11.760 Hz
   L5_BP_dST : 1.067 Hz
   L5_BTC_bAC : 5.708 Hz
   L5_BTC_cAC : 7.236 Hz
   L5_BTC_cNA : 11.462 Hz
   L5_ChC_cAC : 14.543 Hz
   L5_ChC_cNA : 20.686 Hz
   L5_ChC_dNA : 22.720 Hz
   L5_DBC_bAC : 2.333 Hz
   L5_DBC_bIR : 0.735 Hz
   L5_DBC_bNA : 5.822 Hz
   L5_DBC_bST : 2.778 Hz
   L5_DBC_cAC : 4.844 Hz
   L5_DBC_cIR : 1.647 Hz
   L5_DBC_cNA : 8.422 Hz
   L5_LBC_bAC : 6.733 Hz
   L5_LBC_cAC : 12.896 Hz
   L5_LBC_cIR : 4.831 Hz
   L5_LBC_cNA : 29.595 Hz
   L5_LBC_cST : 26.054 Hz
   L5_LBC_dNA : 28.195 Hz
   L5_LBC_dST : 22.959 Hz
   L5_MC_bAC : 0.799 Hz
   L5_MC_bIR : 0.745 Hz
   L5_MC_bST : 2.462 Hz
   L5_MC_cAC : 2.086 Hz
   L5_MC_cNA : 1.637 Hz
   L5_MC_cST : 1.075 Hz
   L5_MC_dNA : 1.238 Hz
   L5_NBC_bAC : 4.614 Hz
   L5_NBC_bIR : 2.700 Hz
   L5_NBC_bST : 23.244 Hz
   L5_NBC_cAC : 16.120 Hz
   L5_NBC_cIR : 10.414 Hz
   L5_NBC_cNA : 27.477 Hz
   L5_NBC_cST : 19.495 Hz
   L5_NBC_dST : 23.631 Hz
   L5_NGC_bNA : 0.200 Hz
   L5_NGC_cAC : 6.000 Hz
   L5_NGC_cNA : 12.560 Hz
   L5_NGC_cST : 1.200 Hz
   L5_SBC_bNA : 22.600 Hz
   L5_SBC_cAC : 9.133 Hz
   L5_SBC_dNA : 31.943 Hz
   L5_STPC_cAD : 6.746 Hz
   L5_TTPC1_cAD : 6.924 Hz
   L5_TTPC2_cAD : 7.436 Hz
   L5_UTPC_cAD : 8.943 Hz
   L6_BPC_cAD : 3.078 Hz
   L6_BP_bAC : 3.500 Hz
   L6_BP_bIR : 1.560 Hz
   L6_BP_bNA : 16.326 Hz
   L6_BP_cAC : 8.305 Hz
   L6_BP_cNA : 15.460 Hz
   L6_BP_dST : 1.967 Hz
   L6_BTC_bAC : 5.060 Hz
   L6_BTC_cAC : 10.465 Hz
   L6_BTC_cNA : 20.580 Hz
   L6_ChC_cAC : 13.767 Hz
   L6_ChC_cNA : 41.733 Hz
   L6_ChC_dNA : 26.400 Hz
   L6_DBC_bAC : 5.333 Hz
   L6_DBC_bIR : 1.100 Hz
   L6_DBC_bNA : 7.867 Hz
   L6_DBC_bST : 3.667 Hz
   L6_DBC_cAC : 9.333 Hz
   L6_DBC_cIR : 3.700 Hz
   L6_DBC_cNA : 6.133 Hz
   L6_IPC_cAD : 2.735 Hz
   L6_LBC_bAC : 5.093 Hz
   L6_LBC_bIR : 3.340 Hz
   L6_LBC_bNA : 54.237 Hz
   L6_LBC_bST : 29.011 Hz
   L6_LBC_cNA : 42.519 Hz
   L6_LBC_cST : 23.930 Hz
   L6_MC_bAC : 0.376 Hz
   L6_MC_bIR : 0.312 Hz
   L6_MC_bNA : 2.229 Hz
   L6_MC_bST : 0.957 Hz
   L6_MC_cAC : 2.234 Hz
   L6_MC_cIR : 0.614 Hz
   L6_MC_cNA : 2.257 Hz
   L6_NBC_bAC : 5.700 Hz
   L6_NBC_bIR : 3.843 Hz
   L6_NBC_bST : 33.467 Hz
   L6_NBC_cAC : 12.738 Hz
   L6_NBC_cIR : 6.486 Hz
   L6_NBC_cNA : 28.714 Hz
   L6_NBC_cST : 25.005 Hz
   L6_NBC_dST : 29.386 Hz
   L6_NGC_bNA : 0.200 Hz
   L6_NGC_cAC : 9.600 Hz
   L6_NGC_cNA : 16.073 Hz
   L6_NGC_cST : 2.500 Hz
   L6_SBC_bNA : 30.808 Hz
   L6_SBC_cAC : 18.633 Hz
   L6_SBC_dNA : 25.495 Hz
   L6_TPC_L1_cAD : 3.018 Hz
   L6_TPC_L4_cAD : 3.662 Hz
   L6_UTPC_cAD : 4.031 Hz
   ss_RTN_o : 69.967 Hz
   ss_RTN_m : 69.191 Hz
   ss_RTN_i : 64.286 Hz
   VPL_sTC : 1.180 Hz
   VPM_sTC : 1.272 Hz
   POm_sTC_s1 : 0.642 Hz
Saving output as ../data/v6_batch1/v6_batch1_0_0.json  ... 
Finished saving!
  Done; saving time = 84.89 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 4715.00 s

Total time = 154271.97 s

End time:  2021-11-24 22:15:35.486129
