#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _cadad_reg(void);
extern void _CaDynamics_E2_reg(void);
extern void _Ca_HVA_reg(void);
extern void _Ca_LVAst_reg(void);
extern void _Ca_reg(void);
extern void _DetAMPANMDA_reg(void);
extern void _DetGABAAB_reg(void);
extern void _HH2_reg(void);
extern void _htc_reg(void);
extern void _Ih_reg(void);
extern void _Im_reg(void);
extern void _IT2_reg(void);
extern void _IT_reg(void);
extern void _KdShu2007_reg(void);
extern void _kl_reg(void);
extern void _K_Pst_reg(void);
extern void _K_Tst_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _Nap_Et2_reg(void);
extern void _NaTa_t_reg(void);
extern void _NaTs2_t_reg(void);
extern void _ProbAMPANMDA_EMS_reg(void);
extern void _ProbGABAAB_EMS_reg(void);
extern void _SK_E2_reg(void);
extern void _SKv3_1_reg(void);
extern void _StochKv_deterministic_reg(void);
extern void _StochKv_reg(void);
extern void _tia_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"mod/cadad.mod\"");
    fprintf(stderr," \"mod/CaDynamics_E2.mod\"");
    fprintf(stderr," \"mod/Ca_HVA.mod\"");
    fprintf(stderr," \"mod/Ca_LVAst.mod\"");
    fprintf(stderr," \"mod/Ca.mod\"");
    fprintf(stderr," \"mod/DetAMPANMDA.mod\"");
    fprintf(stderr," \"mod/DetGABAAB.mod\"");
    fprintf(stderr," \"mod/HH2.mod\"");
    fprintf(stderr," \"mod/htc.mod\"");
    fprintf(stderr," \"mod/Ih.mod\"");
    fprintf(stderr," \"mod/Im.mod\"");
    fprintf(stderr," \"mod/IT2.mod\"");
    fprintf(stderr," \"mod/IT.mod\"");
    fprintf(stderr," \"mod/KdShu2007.mod\"");
    fprintf(stderr," \"mod/kl.mod\"");
    fprintf(stderr," \"mod/K_Pst.mod\"");
    fprintf(stderr," \"mod/K_Tst.mod\"");
    fprintf(stderr," \"mod/MyExp2SynBB.mod\"");
    fprintf(stderr," \"mod/MyExp2SynNMDABB.mod\"");
    fprintf(stderr," \"mod/Nap_Et2.mod\"");
    fprintf(stderr," \"mod/NaTa_t.mod\"");
    fprintf(stderr," \"mod/NaTs2_t.mod\"");
    fprintf(stderr," \"mod/ProbAMPANMDA_EMS.mod\"");
    fprintf(stderr," \"mod/ProbGABAAB_EMS.mod\"");
    fprintf(stderr," \"mod/SK_E2.mod\"");
    fprintf(stderr," \"mod/SKv3_1.mod\"");
    fprintf(stderr," \"mod/StochKv_deterministic.mod\"");
    fprintf(stderr," \"mod/StochKv.mod\"");
    fprintf(stderr," \"mod/tia.mod\"");
    fprintf(stderr," \"mod/vecevent.mod\"");
    fprintf(stderr, "\n");
  }
  _cadad_reg();
  _CaDynamics_E2_reg();
  _Ca_HVA_reg();
  _Ca_LVAst_reg();
  _Ca_reg();
  _DetAMPANMDA_reg();
  _DetGABAAB_reg();
  _HH2_reg();
  _htc_reg();
  _Ih_reg();
  _Im_reg();
  _IT2_reg();
  _IT_reg();
  _KdShu2007_reg();
  _kl_reg();
  _K_Pst_reg();
  _K_Tst_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _Nap_Et2_reg();
  _NaTa_t_reg();
  _NaTs2_t_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SK_E2_reg();
  _SKv3_1_reg();
  _StochKv_deterministic_reg();
  _StochKv_reg();
  _tia_reg();
  _vecevent_reg();
}
