#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/fernando/Documents/anaconda3/envs/p37/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/fernando/Documents/anaconda3/envs/p37/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/fernando/S1_netpyne/sim/x86_64/.libs/libnrnmech.so" "$@"
