numprocs=224

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 49: 147 
  Number of connections on node 49: 2141 
  Number of synaptic contacts on node 49: 12071 
  Number of stims on node 49: 70 
Recording 7 traces of 1 types on node 49

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 56: 147 
  Number of connections on node 56: 1960 
  Number of synaptic contacts on node 56: 9305 
  Number of stims on node 56: 70 
Recording 7 traces of 1 types on node 56

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 89: 147 
  Number of connections on node 89: 2086 
  Number of synaptic contacts on node 89: 10338 
  Number of stims on node 89: 70 
Recording 7 traces of 1 types on node 89

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 2: 147 
  Number of connections on node 2: 2130 
  Number of synaptic contacts on node 2: 11254 
  Number of stims on node 2: 70 
Recording 7 traces of 1 types on node 2

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 5: 147 
  Number of connections on node 5: 2178 
  Number of synaptic contacts on node 5: 11362 
  Number of stims on node 5: 70 
Recording 7 traces of 1 types on node 5

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 7: 147 
  Number of connections on node 7: 2378 
  Number of synaptic contacts on node 7: 13159 
  Number of stims on node 7: 70 
Recording 7 traces of 1 types on node 7

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 22: 147 
  Number of connections on node 22: 2173 
  Number of synaptic contacts on node 22: 12185 
  Number of stims on node 22: 70 
Recording 7 traces of 1 types on node 22

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 29: 147 
  Number of connections on node 29: 2370 
  Number of synaptic contacts on node 29: 12938 
  Number of stims on node 29: 70 
Recording 7 traces of 1 types on node 29

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 44: 147 
  Number of connections on node 44: 2058 
  Number of synaptic contacts on node 44: 11228 
  Number of stims on node 44: 70 
Recording 7 traces of 1 types on node 44

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 51: 147 
  Number of connections on node 51: 2100 
  Number of synaptic contacts on node 51: 11888 
  Number of stims on node 51: 70 
Recording 7 traces of 1 types on node 51

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 60: 147 
  Number of connections on node 60: 1836 
  Number of synaptic contacts on node 60: 8990 
  Number of stims on node 60: 70 
Recording 7 traces of 1 types on node 60

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 65: 147 
  Number of connections on node 65: 2150 
  Number of synaptic contacts on node 65: 11375 
  Number of stims on node 65: 70 
Recording 7 traces of 1 types on node 65

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 68: 147 
  Number of connections on node 68: 1992 
  Number of synaptic contacts on node 68: 10087 
  Number of stims on node 68: 70 
Recording 7 traces of 1 types on node 68

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 77: 147 
  Number of connections on node 77: 1984 
  Number of synaptic contacts on node 77: 9882 
  Number of stims on node 77: 70 
Recording 7 traces of 1 types on node 77

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 84: 147 
  Number of connections on node 84: 2050 
  Number of synaptic contacts on node 84: 10538 
  Number of stims on node 84: 70 
Recording 7 traces of 1 types on node 84

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 86: 147 
  Number of connections on node 86: 2054 
  Number of synaptic contacts on node 86: 10320 
  Number of stims on node 86: 70 
Recording 7 traces of 1 types on node 86

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 87: 147 
  Number of connections on node 87: 2063 
  Number of synaptic contacts on node 87: 10283 
  Number of stims on node 87: 70 
Recording 7 traces of 1 types on node 87

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 88: 147 
  Number of connections on node 88: 2011 
  Number of synaptic contacts on node 88: 10365 
  Number of stims on node 88: 70 
Recording 7 traces of 1 types on node 88

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 98: 147 
  Number of connections on node 98: 2070 
  Number of synaptic contacts on node 98: 9883 
  Number of stims on node 98: 70 
Recording 7 traces of 1 types on node 98

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 99: 147 
  Number of connections on node 99: 2098 
  Number of synaptic contacts on node 99: 9901 
  Number of stims on node 99: 70 
Recording 7 traces of 1 types on node 99

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 108: 147 
  Number of connections on node 108: 2582 
  Number of synaptic contacts on node 108: 12622 
  Number of stims on node 108: 70 
Recording 7 traces of 1 types on node 108

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 111: 147 
  Number of connections on node 111: 2666 
  Number of synaptic contacts on node 111: 12915 
  Number of stims on node 111: 70 
Recording 7 traces of 1 types on node 111

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 112: 147 
  Number of connections on node 112: 2635 
  Number of synaptic contacts on node 112: 12617 
  Number of stims on node 112: 70 
Recording 7 traces of 1 types on node 112

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 124: 146 
  Number of connections on node 124: 2129 
  Number of synaptic contacts on node 124: 11970 
  Number of stims on node 124: 60 
Recording 6 traces of 1 types on node 124

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 127: 146 
  Number of connections on node 127: 2172 
  Number of synaptic contacts on node 127: 12634 
  Number of stims on node 127: 60 
Recording 6 traces of 1 types on node 127

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 3: 147 
  Number of connections on node 3: 2120 
  Number of synaptic contacts on node 3: 11176 
  Number of stims on node 3: 70 
Recording 7 traces of 1 types on node 3

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 8: 147 
  Number of connections on node 8: 2237 
  Number of synaptic contacts on node 8: 12050 
  Number of stims on node 8: 70 
Recording 7 traces of 1 types on node 8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 10: 147 
  Number of connections on node 10: 2220 
  Number of synaptic contacts on node 10: 11999 
  Number of stims on node 10: 70 
Recording 7 traces of 1 types on node 10

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 13: 147 
  Number of connections on node 13: 2242 
  Number of synaptic contacts on node 13: 11947 
  Number of stims on node 13: 70 
Recording 7 traces of 1 types on node 13

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 15: 147 
  Number of connections on node 15: 2132 
  Number of synaptic contacts on node 15: 11062 
  Number of stims on node 15: 70 
Recording 7 traces of 1 types on node 15

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 18: 147 
  Number of connections on node 18: 2237 
  Number of synaptic contacts on node 18: 11790 
  Number of stims on node 18: 70 
Recording 7 traces of 1 types on node 18

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 19: 147 
  Number of connections on node 19: 2183 
  Number of synaptic contacts on node 19: 11290 
  Number of stims on node 19: 70 
Recording 7 traces of 1 types on node 19

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 30: 147 
  Number of connections on node 30: 2325 
  Number of synaptic contacts on node 30: 12794 
  Number of stims on node 30: 70 
Recording 7 traces of 1 types on node 30

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 31: 147 
  Number of connections on node 31: 2307 
  Number of synaptic contacts on node 31: 12396 
  Number of stims on node 31: 70 
Recording 7 traces of 1 types on node 31

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 32: 147 
  Number of connections on node 32: 2255 
  Number of synaptic contacts on node 32: 12326 
  Number of stims on node 32: 70 
Recording 7 traces of 1 types on node 32

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 35: 147 
  Number of connections on node 35: 2235 
  Number of synaptic contacts on node 35: 12179 
  Number of stims on node 35: 70 
Recording 7 traces of 1 types on node 35

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 36: 147 
  Number of connections on node 36: 2334 
  Number of synaptic contacts on node 36: 12404 
  Number of stims on node 36: 70 
Recording 7 traces of 1 types on node 36

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 42: 147 
  Number of connections on node 42: 2035 
  Number of synaptic contacts on node 42: 11492 
  Number of stims on node 42: 70 
Recording 7 traces of 1 types on node 42

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 46: 147 
  Number of connections on node 46: 2209 
  Number of synaptic contacts on node 46: 12799 
  Number of stims on node 46: 70 
Recording 7 traces of 1 types on node 46

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 47: 147 
  Number of connections on node 47: 2170 
  Number of synaptic contacts on node 47: 12614 
  Number of stims on node 47: 70 
Recording 7 traces of 1 types on node 47

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 55: 147 
  Number of connections on node 55: 1990 
  Number of synaptic contacts on node 55: 9681 
  Number of stims on node 55: 70 
Recording 7 traces of 1 types on node 55

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 57: 147 
  Number of connections on node 57: 1883 
  Number of synaptic contacts on node 57: 8906 
  Number of stims on node 57: 70 
Recording 7 traces of 1 types on node 57

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 58: 147 
  Number of connections on node 58: 1929 
  Number of synaptic contacts on node 58: 9078 
  Number of stims on node 58: 70 
Recording 7 traces of 1 types on node 58

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 59: 147 
  Number of connections on node 59: 1789 
  Number of synaptic contacts on node 59: 8119 
  Number of stims on node 59: 70 
Recording 7 traces of 1 types on node 59

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 62: 147 
  Number of connections on node 62: 1941 
  Number of synaptic contacts on node 62: 9536 
  Number of stims on node 62: 70 
Recording 7 traces of 1 types on node 62

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 71: 147 
  Number of connections on node 71: 2060 
  Number of synaptic contacts on node 71: 10163 
  Number of stims on node 71: 70 
Recording 7 traces of 1 types on node 71

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 72: 147 
  Number of connections on node 72: 2066 
  Number of synaptic contacts on node 72: 10041 
  Number of stims on node 72: 70 
Recording 7 traces of 1 types on node 72

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 74: 147 
  Number of connections on node 74: 1922 
  Number of synaptic contacts on node 74: 9067 
  Number of stims on node 74: 70 
Recording 7 traces of 1 types on node 74

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 76: 147 
  Number of connections on node 76: 2026 
  Number of synaptic contacts on node 76: 9458 
  Number of stims on node 76: 70 
Recording 7 traces of 1 types on node 76

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 80: 147 
  Number of connections on node 80: 1979 
  Number of synaptic contacts on node 80: 9646 
  Number of stims on node 80: 70 
Recording 7 traces of 1 types on node 80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 83: 147 
  Number of connections on node 83: 2103 
  Number of synaptic contacts on node 83: 10762 
  Number of stims on node 83: 70 
Recording 7 traces of 1 types on node 83

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 85: 147 
  Number of connections on node 85: 2158 
  Number of synaptic contacts on node 85: 10835 
  Number of stims on node 85: 70 
Recording 7 traces of 1 types on node 85

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 93: 147 
  Number of connections on node 93: 2017 
  Number of synaptic contacts on node 93: 10384 
  Number of stims on node 93: 70 
Recording 7 traces of 1 types on node 93

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 94: 147 
  Number of connections on node 94: 2070 
  Number of synaptic contacts on node 94: 10254 
  Number of stims on node 94: 70 
Recording 7 traces of 1 types on node 94

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 95: 147 
  Number of connections on node 95: 2062 
  Number of synaptic contacts on node 95: 9762 
  Number of stims on node 95: 70 
Recording 7 traces of 1 types on node 95

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 102: 147 
  Number of connections on node 102: 1803 
  Number of synaptic contacts on node 102: 8163 
  Number of stims on node 102: 70 
Recording 7 traces of 1 types on node 102

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 105: 147 
  Number of connections on node 105: 2280 
  Number of synaptic contacts on node 105: 10292 
  Number of stims on node 105: 70 
Recording 7 traces of 1 types on node 105

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 109: 147 
  Number of connections on node 109: 2704 
  Number of synaptic contacts on node 109: 12812 
  Number of stims on node 109: 70 
Recording 7 traces of 1 types on node 109

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 110: 147 
  Number of connections on node 110: 2595 
  Number of synaptic contacts on node 110: 12469 
  Number of stims on node 110: 70 
Recording 7 traces of 1 types on node 110

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 116: 146 
  Number of connections on node 116: 2102 
  Number of synaptic contacts on node 116: 10736 
  Number of stims on node 116: 60 
Recording 6 traces of 1 types on node 116

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 121: 146 
  Number of connections on node 121: 2059 
  Number of synaptic contacts on node 121: 11840 
  Number of stims on node 121: 60 
Recording 6 traces of 1 types on node 121

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 125: 146 
  Number of connections on node 125: 2088 
  Number of synaptic contacts on node 125: 11594 
  Number of stims on node 125: 60 
Recording 6 traces of 1 types on node 125

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 1: 147 
  Number of connections on node 1: 2128 
  Number of synaptic contacts on node 1: 11000 
  Number of stims on node 1: 70 
Recording 7 traces of 1 types on node 1

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 4: 147 
  Number of connections on node 4: 2086 
  Number of synaptic contacts on node 4: 10941 
  Number of stims on node 4: 70 
Recording 7 traces of 1 types on node 4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 6: 147 
  Number of connections on node 6: 2231 
  Number of synaptic contacts on node 6: 12349 
  Number of stims on node 6: 70 
Recording 7 traces of 1 types on node 6

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 9: 147 
  Number of connections on node 9: 2231 
  Number of synaptic contacts on node 9: 11740 
  Number of stims on node 9: 70 
Recording 7 traces of 1 types on node 9

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 11: 147 
  Number of connections on node 11: 2244 
  Number of synaptic contacts on node 11: 11722 
  Number of stims on node 11: 70 
Recording 7 traces of 1 types on node 11

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 12: 147 
  Number of connections on node 12: 2235 
  Number of synaptic contacts on node 12: 11871 
  Number of stims on node 12: 70 
Recording 7 traces of 1 types on node 12

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 14: 147 
  Number of connections on node 14: 2248 
  Number of synaptic contacts on node 14: 11697 
  Number of stims on node 14: 70 
Recording 7 traces of 1 types on node 14

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 16: 147 
  Number of connections on node 16: 2127 
  Number of synaptic contacts on node 16: 10937 
  Number of stims on node 16: 70 
Recording 7 traces of 1 types on node 16

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 20: 147 
  Number of connections on node 20: 2252 
  Number of synaptic contacts on node 20: 12294 
  Number of stims on node 20: 70 
Recording 7 traces of 1 types on node 20

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 21: 147 
  Number of connections on node 21: 2281 
  Number of synaptic contacts on node 21: 12466 
  Number of stims on node 21: 70 
Recording 7 traces of 1 types on node 21

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 23: 147 
  Number of connections on node 23: 2336 
  Number of synaptic contacts on node 23: 12464 
  Number of stims on node 23: 70 
Recording 7 traces of 1 types on node 23

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 24: 147 
  Number of connections on node 24: 2334 
  Number of synaptic contacts on node 24: 12584 
  Number of stims on node 24: 70 
Recording 7 traces of 1 types on node 24

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 25: 147 
  Number of connections on node 25: 2260 
  Number of synaptic contacts on node 25: 12207 
  Number of stims on node 25: 70 
Recording 7 traces of 1 types on node 25

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 26: 147 
  Number of connections on node 26: 2322 
  Number of synaptic contacts on node 26: 12601 
  Number of stims on node 26: 70 
Recording 7 traces of 1 types on node 26

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 27: 147 
  Number of connections on node 27: 2280 
  Number of synaptic contacts on node 27: 12251 
  Number of stims on node 27: 70 
Recording 7 traces of 1 types on node 27

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 37: 147 
  Number of connections on node 37: 2372 
  Number of synaptic contacts on node 37: 13050 
  Number of stims on node 37: 70 
Recording 7 traces of 1 types on node 37

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 38: 147 
  Number of connections on node 38: 2251 
  Number of synaptic contacts on node 38: 12205 
  Number of stims on node 38: 70 
Recording 7 traces of 1 types on node 38

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 39: 147 
  Number of connections on node 39: 1981 
  Number of synaptic contacts on node 39: 11131 
  Number of stims on node 39: 70 
Recording 7 traces of 1 types on node 39

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 40: 147 
  Number of connections on node 40: 2128 
  Number of synaptic contacts on node 40: 11876 
  Number of stims on node 40: 70 
Recording 7 traces of 1 types on node 40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 43: 147 
  Number of connections on node 43: 2069 
  Number of synaptic contacts on node 43: 11395 
  Number of stims on node 43: 70 
Recording 7 traces of 1 types on node 43

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 45: 147 
  Number of connections on node 45: 2179 
  Number of synaptic contacts on node 45: 12451 
  Number of stims on node 45: 70 
Recording 7 traces of 1 types on node 45

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 48: 147 
  Number of connections on node 48: 2157 
  Number of synaptic contacts on node 48: 12495 
  Number of stims on node 48: 70 
Recording 7 traces of 1 types on node 48

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 50: 147 
  Number of connections on node 50: 2124 
  Number of synaptic contacts on node 50: 12025 
  Number of stims on node 50: 70 
Recording 7 traces of 1 types on node 50

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 52: 147 
  Number of connections on node 52: 2014 
  Number of synaptic contacts on node 52: 11020 
  Number of stims on node 52: 70 
Recording 7 traces of 1 types on node 52

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 53: 147 
  Number of connections on node 53: 2107 
  Number of synaptic contacts on node 53: 11282 
  Number of stims on node 53: 70 
Recording 7 traces of 1 types on node 53

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 54: 147 
  Number of connections on node 54: 2099 
  Number of synaptic contacts on node 54: 11092 
  Number of stims on node 54: 70 
Recording 7 traces of 1 types on node 54

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 61: 147 
  Number of connections on node 61: 1988 
  Number of synaptic contacts on node 61: 9840 
  Number of stims on node 61: 70 
Recording 7 traces of 1 types on node 61

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 63: 147 
  Number of connections on node 63: 2021 
  Number of synaptic contacts on node 63: 9754 
  Number of stims on node 63: 70 
Recording 7 traces of 1 types on node 63

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 64: 147 
  Number of connections on node 64: 1931 
  Number of synaptic contacts on node 64: 9694 
  Number of stims on node 64: 70 
Recording 7 traces of 1 types on node 64

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 66: 147 
  Number of connections on node 66: 2098 
  Number of synaptic contacts on node 66: 10880 
  Number of stims on node 66: 70 
Recording 7 traces of 1 types on node 66

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 67: 147 
  Number of connections on node 67: 2094 
  Number of synaptic contacts on node 67: 11037 
  Number of stims on node 67: 70 
Recording 7 traces of 1 types on node 67

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 69: 147 
  Number of connections on node 69: 1995 
  Number of synaptic contacts on node 69: 9858 
  Number of stims on node 69: 70 
Recording 7 traces of 1 types on node 69

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 70: 147 
  Number of connections on node 70: 2051 
  Number of synaptic contacts on node 70: 10173 
  Number of stims on node 70: 70 
Recording 7 traces of 1 types on node 70

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 73: 147 
  Number of connections on node 73: 2104 
  Number of synaptic contacts on node 73: 10407 
  Number of stims on node 73: 70 
Recording 7 traces of 1 types on node 73

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 75: 147 
  Number of connections on node 75: 1980 
  Number of synaptic contacts on node 75: 9743 
  Number of stims on node 75: 70 
Recording 7 traces of 1 types on node 75

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 78: 147 
  Number of connections on node 78: 1941 
  Number of synaptic contacts on node 78: 9331 
  Number of stims on node 78: 70 
Recording 7 traces of 1 types on node 78

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 79: 147 
  Number of connections on node 79: 1880 
  Number of synaptic contacts on node 79: 9048 
  Number of stims on node 79: 70 
Recording 7 traces of 1 types on node 79

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 81: 147 
  Number of connections on node 81: 2061 
  Number of synaptic contacts on node 81: 10458 
  Number of stims on node 81: 70 
Recording 7 traces of 1 types on node 81

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 82: 147 
  Number of connections on node 82: 2075 
  Number of synaptic contacts on node 82: 10264 
  Number of stims on node 82: 70 
Recording 7 traces of 1 types on node 82

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 90: 147 
  Number of connections on node 90: 1997 
  Number of synaptic contacts on node 90: 10102 
  Number of stims on node 90: 70 
Recording 7 traces of 1 types on node 90

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 91: 147 
  Number of connections on node 91: 2145 
  Number of synaptic contacts on node 91: 10453 
  Number of stims on node 91: 70 
Recording 7 traces of 1 types on node 91

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 92: 147 
  Number of connections on node 92: 2134 
  Number of synaptic contacts on node 92: 10622 
  Number of stims on node 92: 70 
Recording 7 traces of 1 types on node 92

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 96: 147 
  Number of connections on node 96: 2115 
  Number of synaptic contacts on node 96: 10068 
  Number of stims on node 96: 70 
Recording 7 traces of 1 types on node 96

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 97: 147 
  Number of connections on node 97: 2077 
  Number of synaptic contacts on node 97: 9861 
  Number of stims on node 97: 70 
Recording 7 traces of 1 types on node 97

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 100: 147 
  Number of connections on node 100: 1977 
  Number of synaptic contacts on node 100: 9254 
  Number of stims on node 100: 70 
Recording 7 traces of 1 types on node 100

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 101: 147 
  Number of connections on node 101: 1767 
  Number of synaptic contacts on node 101: 7703 
  Number of stims on node 101: 70 
Recording 7 traces of 1 types on node 101

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 103: 147 
  Number of connections on node 103: 1842 
  Number of synaptic contacts on node 103: 8179 
  Number of stims on node 103: 70 
Recording 7 traces of 1 types on node 103

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 104: 147 
  Number of connections on node 104: 1995 
  Number of synaptic contacts on node 104: 8878 
  Number of stims on node 104: 70 
Recording 7 traces of 1 types on node 104

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 106: 147 
  Number of connections on node 106: 2346 
  Number of synaptic contacts on node 106: 10485 
  Number of stims on node 106: 70 
Recording 7 traces of 1 types on node 106

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 107: 147 
  Number of connections on node 107: 2557 
  Number of synaptic contacts on node 107: 12539 
  Number of stims on node 107: 70 
Recording 7 traces of 1 types on node 107

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 113: 147 
  Number of connections on node 113: 2615 
  Number of synaptic contacts on node 113: 12524 
  Number of stims on node 113: 70 
Recording 7 traces of 1 types on node 113

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 114: 147 
  Number of connections on node 114: 2638 
  Number of synaptic contacts on node 114: 12877 
  Number of stims on node 114: 70 
Recording 7 traces of 1 types on node 114

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 115: 147 
  Number of connections on node 115: 2623 
  Number of synaptic contacts on node 115: 12482 
  Number of stims on node 115: 70 
Recording 7 traces of 1 types on node 115

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 117: 146 
  Number of connections on node 117: 2048 
  Number of synaptic contacts on node 117: 10286 
  Number of stims on node 117: 60 
Recording 6 traces of 1 types on node 117

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 118: 146 
  Number of connections on node 118: 2188 
  Number of synaptic contacts on node 118: 12354 
  Number of stims on node 118: 60 
Recording 6 traces of 1 types on node 118

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 119: 146 
  Number of connections on node 119: 2082 
  Number of synaptic contacts on node 119: 11866 
  Number of stims on node 119: 60 
Recording 6 traces of 1 types on node 119

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 120: 146 
  Number of connections on node 120: 2095 
  Number of synaptic contacts on node 120: 11592 
  Number of stims on node 120: 60 
Recording 6 traces of 1 types on node 120

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 122: 146 
  Number of connections on node 122: 2105 
  Number of synaptic contacts on node 122: 11827 
  Number of stims on node 122: 60 
Recording 6 traces of 1 types on node 122

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 123: 146 
  Number of connections on node 123: 2095 
  Number of synaptic contacts on node 123: 11600 
  Number of stims on node 123: 60 
Recording 6 traces of 1 types on node 123

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 126: 146 
  Number of connections on node 126: 2162 
  Number of synaptic contacts on node 126: 11874 
  Number of stims on node 126: 60 
Recording 6 traces of 1 types on node 126

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 17: 147 
  Number of connections on node 17: 2242 
  Number of synaptic contacts on node 17: 12020 
  Number of stims on node 17: 70 
Recording 7 traces of 1 types on node 17

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 33: 147 
  Number of connections on node 33: 2208 
  Number of synaptic contacts on node 33: 11522 
  Number of stims on node 33: 70 
Recording 7 traces of 1 types on node 33

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 34: 147 
  Number of connections on node 34: 2322 
  Number of synaptic contacts on node 34: 12738 
  Number of stims on node 34: 70 
Recording 7 traces of 1 types on node 34

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 41: 147 
  Number of connections on node 41: 2088 
  Number of synaptic contacts on node 41: 11701 
  Number of stims on node 41: 70 
Recording 7 traces of 1 types on node 41

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 128: 146 
  Number of connections on node 128: 2022 
  Number of synaptic contacts on node 128: 11559 
  Number of stims on node 128: 60 
Recording 6 traces of 1 types on node 128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 130: 146 
  Number of connections on node 130: 2155 
  Number of synaptic contacts on node 130: 11786 
  Number of stims on node 130: 60 
Recording 6 traces of 1 types on node 130

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 131: 146 
  Number of connections on node 131: 2166 
  Number of synaptic contacts on node 131: 11851 
  Number of stims on node 131: 60 
Recording 6 traces of 1 types on node 131

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 136: 146 
  Number of connections on node 136: 2106 
  Number of synaptic contacts on node 136: 11824 
  Number of stims on node 136: 60 
Recording 6 traces of 1 types on node 136

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 137: 146 
  Number of connections on node 137: 2010 
  Number of synaptic contacts on node 137: 11014 
  Number of stims on node 137: 60 
Recording 6 traces of 1 types on node 137

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 138: 146 
  Number of connections on node 138: 2121 
  Number of synaptic contacts on node 138: 11882 
  Number of stims on node 138: 60 
Recording 6 traces of 1 types on node 138

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 139: 146 
  Number of connections on node 139: 2108 
  Number of synaptic contacts on node 139: 11818 
  Number of stims on node 139: 60 
Recording 6 traces of 1 types on node 139

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 141: 146 
  Number of connections on node 141: 2093 
  Number of synaptic contacts on node 141: 11753 
  Number of stims on node 141: 60 
Recording 6 traces of 1 types on node 141

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 152: 146 
  Number of connections on node 152: 2038 
  Number of synaptic contacts on node 152: 11324 
  Number of stims on node 152: 60 
Recording 6 traces of 1 types on node 152

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 155: 146 
  Number of connections on node 155: 2091 
  Number of synaptic contacts on node 155: 11581 
  Number of stims on node 155: 60 
Recording 6 traces of 1 types on node 155

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 160: 146 
  Number of connections on node 160: 2048 
  Number of synaptic contacts on node 160: 11223 
  Number of stims on node 160: 60 
Recording 6 traces of 1 types on node 160

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 163: 146 
  Number of connections on node 163: 2320 
  Number of synaptic contacts on node 163: 11931 
  Number of stims on node 163: 60 
Recording 6 traces of 1 types on node 163

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 164: 146 
  Number of connections on node 164: 2406 
  Number of synaptic contacts on node 164: 12676 
  Number of stims on node 164: 60 
Recording 6 traces of 1 types on node 164

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 172: 146 
  Number of connections on node 172: 2391 
  Number of synaptic contacts on node 172: 12444 
  Number of stims on node 172: 60 
Recording 6 traces of 1 types on node 172

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 174: 146 
  Number of connections on node 174: 2354 
  Number of synaptic contacts on node 174: 12317 
  Number of stims on node 174: 60 
Recording 6 traces of 1 types on node 174

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 175: 146 
  Number of connections on node 175: 2370 
  Number of synaptic contacts on node 175: 12299 
  Number of stims on node 175: 60 
Recording 6 traces of 1 types on node 175

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 192: 146 
  Number of connections on node 192: 2036 
  Number of synaptic contacts on node 192: 11760 
  Number of stims on node 192: 60 
Recording 6 traces of 1 types on node 192

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 193: 146 
  Number of connections on node 193: 1962 
  Number of synaptic contacts on node 193: 11615 
  Number of stims on node 193: 60 
Recording 6 traces of 1 types on node 193

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 194: 146 
  Number of connections on node 194: 1929 
  Number of synaptic contacts on node 194: 11022 
  Number of stims on node 194: 60 
Recording 6 traces of 1 types on node 194

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 196: 146 
  Number of connections on node 196: 1973 
  Number of synaptic contacts on node 196: 11327 
  Number of stims on node 196: 60 
Recording 6 traces of 1 types on node 196

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 197: 146 
  Number of connections on node 197: 1897 
  Number of synaptic contacts on node 197: 10558 
  Number of stims on node 197: 60 
Recording 6 traces of 1 types on node 197

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 198: 146 
  Number of connections on node 198: 1928 
  Number of synaptic contacts on node 198: 10646 
  Number of stims on node 198: 60 
Recording 6 traces of 1 types on node 198

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 199: 146 
  Number of connections on node 199: 1902 
  Number of synaptic contacts on node 199: 10510 
  Number of stims on node 199: 60 
Recording 6 traces of 1 types on node 199

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 200: 146 
  Number of connections on node 200: 1907 
  Number of synaptic contacts on node 200: 10523 
  Number of stims on node 200: 60 
Recording 6 traces of 1 types on node 200

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 201: 146 
  Number of connections on node 201: 1828 
  Number of synaptic contacts on node 201: 10227 
  Number of stims on node 201: 60 
Recording 6 traces of 1 types on node 201

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 202: 146 
  Number of connections on node 202: 1899 
  Number of synaptic contacts on node 202: 10400 
  Number of stims on node 202: 60 
Recording 6 traces of 1 types on node 202

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 203: 146 
  Number of connections on node 203: 1726 
  Number of synaptic contacts on node 203: 10045 
  Number of stims on node 203: 60 
Recording 6 traces of 1 types on node 203

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 204: 146 
  Number of connections on node 204: 1950 
  Number of synaptic contacts on node 204: 10784 
  Number of stims on node 204: 60 
Recording 6 traces of 1 types on node 204

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 205: 146 
  Number of connections on node 205: 1879 
  Number of synaptic contacts on node 205: 10666 
  Number of stims on node 205: 60 
Recording 6 traces of 1 types on node 205

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 206: 146 
  Number of connections on node 206: 2076 
  Number of synaptic contacts on node 206: 11283 
  Number of stims on node 206: 60 
Recording 6 traces of 1 types on node 206

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 207: 146 
  Number of connections on node 207: 2118 
  Number of synaptic contacts on node 207: 11239 
  Number of stims on node 207: 60 
Recording 6 traces of 1 types on node 207

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 208: 146 
  Number of connections on node 208: 2100 
  Number of synaptic contacts on node 208: 11592 
  Number of stims on node 208: 60 
Recording 6 traces of 1 types on node 208

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 209: 146 
  Number of connections on node 209: 2142 
  Number of synaptic contacts on node 209: 11401 
  Number of stims on node 209: 60 
Recording 6 traces of 1 types on node 209

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 210: 146 
  Number of connections on node 210: 2176 
  Number of synaptic contacts on node 210: 11807 
  Number of stims on node 210: 70 
Recording 7 traces of 1 types on node 210

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 211: 146 
  Number of connections on node 211: 2208 
  Number of synaptic contacts on node 211: 11959 
  Number of stims on node 211: 70 
Recording 7 traces of 1 types on node 211

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 212: 146 
  Number of connections on node 212: 2177 
  Number of synaptic contacts on node 212: 12028 
  Number of stims on node 212: 70 
Recording 7 traces of 1 types on node 212

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 213: 146 
  Number of connections on node 213: 2138 
  Number of synaptic contacts on node 213: 11738 
  Number of stims on node 213: 70 
Recording 7 traces of 1 types on node 213

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 214: 146 
  Number of connections on node 214: 2203 
  Number of synaptic contacts on node 214: 11778 
  Number of stims on node 214: 70 
Recording 7 traces of 1 types on node 214

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 215: 146 
  Number of connections on node 215: 2108 
  Number of synaptic contacts on node 215: 11333 
  Number of stims on node 215: 70 
Recording 7 traces of 1 types on node 215

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 216: 146 
  Number of connections on node 216: 2116 
  Number of synaptic contacts on node 216: 11619 
  Number of stims on node 216: 70 
Recording 7 traces of 1 types on node 216

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 218: 146 
  Number of connections on node 218: 2210 
  Number of synaptic contacts on node 218: 12112 
  Number of stims on node 218: 70 
Recording 7 traces of 1 types on node 218

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 220: 146 
  Number of connections on node 220: 2139 
  Number of synaptic contacts on node 220: 11684 
  Number of stims on node 220: 70 
Recording 7 traces of 1 types on node 220

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 221: 146 
  Number of connections on node 221: 2044 
  Number of synaptic contacts on node 221: 10236 
  Number of stims on node 221: 70 
Recording 7 traces of 1 types on node 221

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 222: 146 
  Number of connections on node 222: 1995 
  Number of synaptic contacts on node 222: 10203 
  Number of stims on node 222: 70 
Recording 7 traces of 1 types on node 222

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 129: 146 
  Number of connections on node 129: 2173 
  Number of synaptic contacts on node 129: 12044 
  Number of stims on node 129: 60 
Recording 6 traces of 1 types on node 129

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 132: 146 
  Number of connections on node 132: 2188 
  Number of synaptic contacts on node 132: 12648 
  Number of stims on node 132: 60 
Recording 6 traces of 1 types on node 132

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 133: 146 
  Number of connections on node 133: 2124 
  Number of synaptic contacts on node 133: 11934 
  Number of stims on node 133: 60 
Recording 6 traces of 1 types on node 133

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 134: 146 
  Number of connections on node 134: 2126 
  Number of synaptic contacts on node 134: 12132 
  Number of stims on node 134: 60 
Recording 6 traces of 1 types on node 134

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 135: 146 
  Number of connections on node 135: 2062 
  Number of synaptic contacts on node 135: 11510 
  Number of stims on node 135: 60 
Recording 6 traces of 1 types on node 135

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 140: 146 
  Number of connections on node 140: 2079 
  Number of synaptic contacts on node 140: 11512 
  Number of stims on node 140: 60 
Recording 6 traces of 1 types on node 140

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 147: 146 
  Number of connections on node 147: 2115 
  Number of synaptic contacts on node 147: 11704 
  Number of stims on node 147: 60 
Recording 6 traces of 1 types on node 147

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 149: 146 
  Number of connections on node 149: 2133 
  Number of synaptic contacts on node 149: 11649 
  Number of stims on node 149: 60 
Recording 6 traces of 1 types on node 149

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 150: 146 
  Number of connections on node 150: 2106 
  Number of synaptic contacts on node 150: 11581 
  Number of stims on node 150: 60 
Recording 6 traces of 1 types on node 150

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 151: 146 
  Number of connections on node 151: 2043 
  Number of synaptic contacts on node 151: 11370 
  Number of stims on node 151: 60 
Recording 6 traces of 1 types on node 151

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 153: 146 
  Number of connections on node 153: 2010 
  Number of synaptic contacts on node 153: 11078 
  Number of stims on node 153: 60 
Recording 6 traces of 1 types on node 153

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 154: 146 
  Number of connections on node 154: 2148 
  Number of synaptic contacts on node 154: 11752 
  Number of stims on node 154: 60 
Recording 6 traces of 1 types on node 154

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 165: 146 
  Number of connections on node 165: 2360 
  Number of synaptic contacts on node 165: 12369 
  Number of stims on node 165: 60 
Recording 6 traces of 1 types on node 165

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 166: 146 
  Number of connections on node 166: 2364 
  Number of synaptic contacts on node 166: 12399 
  Number of stims on node 166: 60 
Recording 6 traces of 1 types on node 166

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 168: 146 
  Number of connections on node 168: 2318 
  Number of synaptic contacts on node 168: 11889 
  Number of stims on node 168: 60 
Recording 6 traces of 1 types on node 168

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 170: 146 
  Number of connections on node 170: 2398 
  Number of synaptic contacts on node 170: 12572 
  Number of stims on node 170: 60 
Recording 6 traces of 1 types on node 170

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 171: 146 
  Number of connections on node 171: 2411 
  Number of synaptic contacts on node 171: 12622 
  Number of stims on node 171: 60 
Recording 6 traces of 1 types on node 171

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 173: 146 
  Number of connections on node 173: 2291 
  Number of synaptic contacts on node 173: 11799 
  Number of stims on node 173: 60 
Recording 6 traces of 1 types on node 173

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 180: 146 
  Number of connections on node 180: 2322 
  Number of synaptic contacts on node 180: 12097 
  Number of stims on node 180: 60 
Recording 6 traces of 1 types on node 180

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 184: 146 
  Number of connections on node 184: 1917 
  Number of synaptic contacts on node 184: 10556 
  Number of stims on node 184: 60 
Recording 6 traces of 1 types on node 184

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 186: 146 
  Number of connections on node 186: 1907 
  Number of synaptic contacts on node 186: 10148 
  Number of stims on node 186: 60 
Recording 6 traces of 1 types on node 186

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 187: 146 
  Number of connections on node 187: 1930 
  Number of synaptic contacts on node 187: 10780 
  Number of stims on node 187: 60 
Recording 6 traces of 1 types on node 187

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 188: 146 
  Number of connections on node 188: 1934 
  Number of synaptic contacts on node 188: 10723 
  Number of stims on node 188: 60 
Recording 6 traces of 1 types on node 188

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 191: 146 
  Number of connections on node 191: 1998 
  Number of synaptic contacts on node 191: 11839 
  Number of stims on node 191: 60 
Recording 6 traces of 1 types on node 191

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 195: 146 
  Number of connections on node 195: 2044 
  Number of synaptic contacts on node 195: 11410 
  Number of stims on node 195: 60 
Recording 6 traces of 1 types on node 195

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 219: 146 
  Number of connections on node 219: 2109 
  Number of synaptic contacts on node 219: 11540 
  Number of stims on node 219: 70 
Recording 7 traces of 1 types on node 219

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 223: 146 
  Number of connections on node 223: 2048 
  Number of synaptic contacts on node 223: 10813 
  Number of stims on node 223: 70 
Recording 7 traces of 1 types on node 223

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 142: 146 
  Number of connections on node 142: 2062 
  Number of synaptic contacts on node 142: 11560 
  Number of stims on node 142: 60 
Recording 6 traces of 1 types on node 142

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 143: 146 
  Number of connections on node 143: 2069 
  Number of synaptic contacts on node 143: 11640 
  Number of stims on node 143: 60 
Recording 6 traces of 1 types on node 143

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 144: 146 
  Number of connections on node 144: 2094 
  Number of synaptic contacts on node 144: 11602 
  Number of stims on node 144: 60 
Recording 6 traces of 1 types on node 144

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 145: 146 
  Number of connections on node 145: 2067 
  Number of synaptic contacts on node 145: 11634 
  Number of stims on node 145: 60 
Recording 6 traces of 1 types on node 145

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 146: 146 
  Number of connections on node 146: 2167 
  Number of synaptic contacts on node 146: 11688 
  Number of stims on node 146: 60 
Recording 6 traces of 1 types on node 146

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 148: 146 
  Number of connections on node 148: 2029 
  Number of synaptic contacts on node 148: 10941 
  Number of stims on node 148: 60 
Recording 6 traces of 1 types on node 148

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 161: 146 
  Number of connections on node 161: 2062 
  Number of synaptic contacts on node 161: 11160 
  Number of stims on node 161: 60 
Recording 6 traces of 1 types on node 161

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 162: 146 
  Number of connections on node 162: 2046 
  Number of synaptic contacts on node 162: 11422 
  Number of stims on node 162: 60 
Recording 6 traces of 1 types on node 162

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 167: 146 
  Number of connections on node 167: 2475 
  Number of synaptic contacts on node 167: 12452 
  Number of stims on node 167: 60 
Recording 6 traces of 1 types on node 167

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 169: 146 
  Number of connections on node 169: 2448 
  Number of synaptic contacts on node 169: 12643 
  Number of stims on node 169: 60 
Recording 6 traces of 1 types on node 169

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 176: 146 
  Number of connections on node 176: 2335 
  Number of synaptic contacts on node 176: 12267 
  Number of stims on node 176: 60 
Recording 6 traces of 1 types on node 176

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 177: 146 
  Number of connections on node 177: 2325 
  Number of synaptic contacts on node 177: 12138 
  Number of stims on node 177: 60 
Recording 6 traces of 1 types on node 177

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 178: 146 
  Number of connections on node 178: 2448 
  Number of synaptic contacts on node 178: 12618 
  Number of stims on node 178: 60 
Recording 6 traces of 1 types on node 178

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 179: 146 
  Number of connections on node 179: 2364 
  Number of synaptic contacts on node 179: 12289 
  Number of stims on node 179: 60 
Recording 6 traces of 1 types on node 179

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 181: 146 
  Number of connections on node 181: 2343 
  Number of synaptic contacts on node 181: 12229 
  Number of stims on node 181: 60 
Recording 6 traces of 1 types on node 181

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 182: 146 
  Number of connections on node 182: 2310 
  Number of synaptic contacts on node 182: 12068 
  Number of stims on node 182: 60 
Recording 6 traces of 1 types on node 182

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 183: 146 
  Number of connections on node 183: 2397 
  Number of synaptic contacts on node 183: 12402 
  Number of stims on node 183: 60 
Recording 6 traces of 1 types on node 183

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 185: 146 
  Number of connections on node 185: 1937 
  Number of synaptic contacts on node 185: 10316 
  Number of stims on node 185: 60 
Recording 6 traces of 1 types on node 185

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 189: 146 
  Number of connections on node 189: 1904 
  Number of synaptic contacts on node 189: 10383 
  Number of stims on node 189: 60 
Recording 6 traces of 1 types on node 189

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 190: 146 
  Number of connections on node 190: 2061 
  Number of synaptic contacts on node 190: 12036 
  Number of stims on node 190: 60 
Recording 6 traces of 1 types on node 190

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 217: 146 
  Number of connections on node 217: 2128 
  Number of synaptic contacts on node 217: 11389 
  Number of stims on node 217: 70 
Recording 7 traces of 1 types on node 217

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 28: 147 
  Number of connections on node 28: 2346 
  Number of synaptic contacts on node 28: 12554 
  Number of stims on node 28: 70 
Recording 7 traces of 1 types on node 28

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 156: 146 
  Number of connections on node 156: 1907 
  Number of synaptic contacts on node 156: 10260 
  Number of stims on node 156: 60 
Recording 6 traces of 1 types on node 156

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 157: 146 
  Number of connections on node 157: 1923 
  Number of synaptic contacts on node 157: 10094 
  Number of stims on node 157: 60 
Recording 6 traces of 1 types on node 157

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 158: 146 
  Number of connections on node 158: 1885 
  Number of synaptic contacts on node 158: 9972 
  Number of stims on node 158: 60 
Recording 6 traces of 1 types on node 158

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
  Number of cells on node 159: 146 
  Number of connections on node 159: 1966 
  Number of synaptic contacts on node 159: 10430 
  Number of stims on node 159: 60 
Recording 6 traces of 1 types on node 159

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py

Start time:  2022-04-16 01:14:50.162885

Creating network of 414 cell populations on 224 hosts...
  Number of cells on node 0: 147 
  Done; cell creation time = 11.88 s.
Making connections...
  Number of connections on node 0: 1974 
  Number of synaptic contacts on node 0: 9808 
  Done; cell connection time = 1953.29 s.
Adding stims...
  Number of stims on node 0: 70 
  Done; cell stims creation time = 24.20 s.
Recording 7 traces of 1 types on node 0
0.0s

Running simulation using NEURON for 10000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
  Done; run time = 8510.68 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 55.26 s.

Analyzing...
  Cells: 32820
  Connections: 0 (0.00 per cell)
  Spikes: 1503818 (4.58 Hz)
  Simulated time: 10.0 s; 224 workers
  Run time: 8510.68 s
   presyn_L1_DAC_bNA : 0.000 Hz
   presyn_L1_DAC_cNA : 0.000 Hz
   presyn_L1_DLAC_cNA : 0.000 Hz
   presyn_L1_HAC_bNA : 0.000 Hz
   presyn_L1_HAC_cIR : 0.000 Hz
   presyn_L1_HAC_cNA : 0.000 Hz
   presyn_L1_NGC-DA_bNA : 0.000 Hz
   presyn_L1_NGC-DA_cAC : 0.000 Hz
   presyn_L1_NGC-DA_cNA : 0.000 Hz
   presyn_L1_NGC-DA_cST : 0.000 Hz
   presyn_L1_NGC-SA_cNA : 0.002 Hz
   presyn_L1_SLAC_bNA : 0.007 Hz
   presyn_L1_SLAC_cAC : 0.000 Hz
   presyn_L1_SLAC_cNA : 0.000 Hz
   presyn_L23_BP_bAC : 0.100 Hz
   presyn_L23_BP_bIR : 0.000 Hz
   presyn_L23_BP_bNA : 0.443 Hz
   presyn_L23_BP_cAC : 0.657 Hz
   presyn_L23_BP_cNA : 1.100 Hz
   presyn_L23_BP_dST : 0.033 Hz
   presyn_L23_BTC_bAC : 0.040 Hz
   presyn_L23_BTC_bIR : 0.014 Hz
   presyn_L23_BTC_bNA : 0.083 Hz
   presyn_L23_BTC_cAC : 0.000 Hz
   presyn_L23_BTC_cNA : 0.167 Hz
   presyn_L23_ChC_cAC : 0.843 Hz
   presyn_L23_ChC_cNA : 0.517 Hz
   presyn_L23_ChC_dNA : 0.200 Hz
   presyn_L23_DBC_bAC : 0.008 Hz
   presyn_L23_DBC_bIR : 0.000 Hz
   presyn_L23_DBC_bNA : 0.046 Hz
   presyn_L23_DBC_cAC : 0.023 Hz
   presyn_L23_LBC_bAC : 0.094 Hz
   presyn_L23_LBC_bNA : 4.863 Hz
   presyn_L23_LBC_cAC : 0.897 Hz
   presyn_L23_LBC_cNA : 1.778 Hz
   presyn_L23_LBC_cST : 2.041 Hz
   presyn_L23_LBC_dNA : 3.520 Hz
   presyn_L23_MC_bAC : 0.000 Hz
   presyn_L23_MC_bNA : 0.000 Hz
   presyn_L23_MC_cAC : 0.000 Hz
   presyn_L23_MC_cNA : 0.000 Hz
   presyn_L23_MC_dNA : 0.000 Hz
   presyn_L23_NBC_bAC : 0.071 Hz
   presyn_L23_NBC_bNA : 1.833 Hz
   presyn_L23_NBC_cAC : 0.137 Hz
   presyn_L23_NBC_cIR : 0.000 Hz
   presyn_L23_NBC_cNA : 0.113 Hz
   presyn_L23_NBC_dNA : 0.684 Hz
   presyn_L23_NGC_bNA : 0.020 Hz
   presyn_L23_NGC_cAC : 0.000 Hz
   presyn_L23_NGC_cNA : 0.017 Hz
   presyn_L23_NGC_cST : 0.000 Hz
   presyn_L23_PC_cAD : 0.316 Hz
   presyn_L23_SBC_bNA : 3.347 Hz
   presyn_L23_SBC_cAC : 2.758 Hz
   presyn_L23_SBC_dNA : 1.863 Hz
   presyn_L4_BP_bAC : 0.000 Hz
   presyn_L4_BP_bIR : 0.000 Hz
   presyn_L4_BP_bNA : 1.900 Hz
   presyn_L4_BP_cAC : 0.100 Hz
   presyn_L4_BP_cNA : 10.300 Hz
   presyn_L4_BP_dST : 0.000 Hz
   presyn_L4_BTC_bAC : 2.550 Hz
   presyn_L4_BTC_bIR : 1.000 Hz
   presyn_L4_BTC_bST : 2.650 Hz
   presyn_L4_BTC_cAC : 4.667 Hz
   presyn_L4_BTC_cNA : 6.300 Hz
   presyn_L4_BTC_dNA : 1.300 Hz
   presyn_L4_ChC_cAC : 17.700 Hz
   presyn_L4_ChC_cNA : 14.967 Hz
   presyn_L4_ChC_dNA : 2.000 Hz
   presyn_L4_DBC_bAC : 3.825 Hz
   presyn_L4_DBC_bIR : 0.069 Hz
   presyn_L4_DBC_bNA : 0.650 Hz
   presyn_L4_DBC_bST : 0.050 Hz
   presyn_L4_DBC_cAC : 0.875 Hz
   presyn_L4_DBC_cIR : 0.257 Hz
   presyn_L4_DBC_cNA : 2.700 Hz
   presyn_L4_LBC_cAC : 13.009 Hz
   presyn_L4_LBC_cNA : 20.264 Hz
   presyn_L4_LBC_cST : 15.265 Hz
   presyn_L4_LBC_dNA : 23.361 Hz
   presyn_L4_LBC_dST : 17.578 Hz
   presyn_L4_MC_bAC : 0.000 Hz
   presyn_L4_MC_bNA : 0.000 Hz
   presyn_L4_MC_cAC : 0.002 Hz
   presyn_L4_MC_cNA : 0.000 Hz
   presyn_L4_MC_dNA : 0.000 Hz
   presyn_L4_NBC_cAC : 12.660 Hz
   presyn_L4_NBC_cIR : 8.640 Hz
   presyn_L4_NBC_cNA : 26.831 Hz
   presyn_L4_NBC_dNA : 19.394 Hz
   presyn_L4_NGC_bNA : 3.900 Hz
   presyn_L4_NGC_cAC : 2.300 Hz
   presyn_L4_NGC_cNA : 2.167 Hz
   presyn_L4_NGC_cST : 0.700 Hz
   presyn_L4_PC_cAD : 3.058 Hz
   presyn_L4_SBC_bNA : 22.810 Hz
   presyn_L4_SBC_cAC : 14.264 Hz
   presyn_L4_SBC_dNA : 23.724 Hz
   presyn_L4_SP_cAD : 3.988 Hz
   presyn_L4_SS_cAD : 4.481 Hz
   presyn_L5_BP_bAC : 5.867 Hz
   presyn_L5_BP_bIR : 1.100 Hz
   presyn_L5_BP_bNA : 15.656 Hz
   presyn_L5_BP_cAC : 11.833 Hz
   presyn_L5_BP_cNA : 22.980 Hz
   presyn_L5_BP_dST : 0.800 Hz
   presyn_L5_BTC_bAC : 8.754 Hz
   presyn_L5_BTC_cAC : 9.032 Hz
   presyn_L5_BTC_cNA : 15.969 Hz
   presyn_L5_ChC_cAC : 23.829 Hz
   presyn_L5_ChC_cNA : 31.743 Hz
   presyn_L5_ChC_dNA : 27.960 Hz
   presyn_L5_DBC_bAC : 3.467 Hz
   presyn_L5_DBC_bIR : 0.491 Hz
   presyn_L5_DBC_bNA : 5.122 Hz
   presyn_L5_DBC_bST : 1.344 Hz
   presyn_L5_DBC_cAC : 5.756 Hz
   presyn_L5_DBC_cIR : 0.959 Hz
   presyn_L5_DBC_cNA : 9.078 Hz
   presyn_L5_LBC_bAC : 9.092 Hz
   presyn_L5_LBC_cAC : 17.788 Hz
   presyn_L5_LBC_cIR : 5.031 Hz
   presyn_L5_LBC_cNA : 39.046 Hz
   presyn_L5_LBC_cST : 30.151 Hz
   presyn_L5_LBC_dNA : 36.019 Hz
   presyn_L5_LBC_dST : 24.990 Hz
   presyn_L5_MC_bAC : 0.384 Hz
   presyn_L5_MC_bIR : 0.055 Hz
   presyn_L5_MC_bST : 0.113 Hz
   presyn_L5_MC_cAC : 0.995 Hz
   presyn_L5_MC_cNA : 0.544 Hz
   presyn_L5_MC_cST : 0.000 Hz
   presyn_L5_MC_dNA : 0.000 Hz
   presyn_L5_NBC_bAC : 7.286 Hz
   presyn_L5_NBC_bIR : 3.443 Hz
   presyn_L5_NBC_bST : 23.030 Hz
   presyn_L5_NBC_cAC : 22.545 Hz
   presyn_L5_NBC_cIR : 11.700 Hz
   presyn_L5_NBC_cNA : 32.903 Hz
   presyn_L5_NBC_cST : 24.495 Hz
   presyn_L5_NBC_dST : 28.500 Hz
   presyn_L5_NGC_bNA : 9.500 Hz
   presyn_L5_NGC_cAC : 11.900 Hz
   presyn_L5_NGC_cNA : 22.800 Hz
   presyn_L5_NGC_cST : 0.200 Hz
   presyn_L5_SBC_bNA : 21.400 Hz
   presyn_L5_SBC_cAC : 12.800 Hz
   presyn_L5_SBC_dNA : 44.100 Hz
   presyn_L5_STPC_cAD : 6.804 Hz
   presyn_L5_TTPC1_cAD : 6.907 Hz
   presyn_L5_TTPC2_cAD : 7.129 Hz
   presyn_L5_UTPC_cAD : 9.533 Hz
   presyn_L6_BPC_cAD : 4.276 Hz
   presyn_L6_BP_bAC : 5.700 Hz
   presyn_L6_BP_bIR : 1.110 Hz
   presyn_L6_BP_bNA : 12.668 Hz
   presyn_L6_BP_cAC : 11.632 Hz
   presyn_L6_BP_cNA : 18.230 Hz
   presyn_L6_BP_dST : 0.717 Hz
   presyn_L6_BTC_bAC : 6.690 Hz
   presyn_L6_BTC_cAC : 9.491 Hz
   presyn_L6_BTC_cNA : 20.100 Hz
   presyn_L6_ChC_cAC : 11.367 Hz
   presyn_L6_ChC_cNA : 50.033 Hz
   presyn_L6_ChC_dNA : 29.500 Hz
   presyn_L6_DBC_bAC : 7.567 Hz
   presyn_L6_DBC_bIR : 0.810 Hz
   presyn_L6_DBC_bNA : 4.500 Hz
   presyn_L6_DBC_bST : 2.967 Hz
   presyn_L6_DBC_cAC : 9.167 Hz
   presyn_L6_DBC_cIR : 3.100 Hz
   presyn_L6_DBC_cNA : 4.967 Hz
   presyn_L6_IPC_cAD : 4.085 Hz
   presyn_L6_LBC_bAC : 6.229 Hz
   presyn_L6_LBC_bIR : 3.641 Hz
   presyn_L6_LBC_bNA : 53.449 Hz
   presyn_L6_LBC_bST : 27.771 Hz
   presyn_L6_LBC_cNA : 42.905 Hz
   presyn_L6_LBC_cST : 24.074 Hz
   presyn_L6_MC_bAC : 0.322 Hz
   presyn_L6_MC_bIR : 0.018 Hz
   presyn_L6_MC_bNA : 0.550 Hz
   presyn_L6_MC_bST : 0.086 Hz
   presyn_L6_MC_cAC : 1.235 Hz
   presyn_L6_MC_cIR : 0.000 Hz
   presyn_L6_MC_cNA : 0.571 Hz
   presyn_L6_NBC_bAC : 7.286 Hz
   presyn_L6_NBC_bIR : 4.350 Hz
   presyn_L6_NBC_bST : 35.274 Hz
   presyn_L6_NBC_cAC : 12.908 Hz
   presyn_L6_NBC_cIR : 5.350 Hz
   presyn_L6_NBC_cNA : 30.524 Hz
   presyn_L6_NBC_cST : 26.474 Hz
   presyn_L6_NBC_dST : 31.721 Hz
   presyn_L6_NGC_bNA : 12.650 Hz
   presyn_L6_NGC_cAC : 12.150 Hz
   presyn_L6_NGC_cNA : 22.355 Hz
   presyn_L6_NGC_cST : 1.100 Hz
   presyn_L6_SBC_bNA : 40.829 Hz
   presyn_L6_SBC_cAC : 23.596 Hz
   presyn_L6_SBC_dNA : 27.126 Hz
   presyn_L6_TPC_L1_cAD : 4.363 Hz
   presyn_L6_TPC_L4_cAD : 5.230 Hz
   presyn_L6_UTPC_cAD : 5.637 Hz
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.000 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.000 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.000 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 0.100 Hz
   L23_MC_cAC : 0.217 Hz
   L23_BP_bIR : 0.000 Hz
   L23_BP_bNA : 0.800 Hz
   L23_BP_cAC : 0.000 Hz
   L23_BP_cNA : 0.800 Hz
   L23_BP_dST : 0.000 Hz
   L23_BTC_bAC : 0.000 Hz
   L23_BTC_bIR : 0.000 Hz
   L23_BTC_bNA : 0.000 Hz
   L23_BTC_cAC : 0.000 Hz
   L23_BTC_cNA : 0.200 Hz
   L23_ChC_cAC : 1.400 Hz
   L23_ChC_cNA : 1.000 Hz
   L23_ChC_dNA : 0.100 Hz
   L23_DBC_bAC : 0.000 Hz
   L23_DBC_bIR : 0.000 Hz
   L23_DBC_bNA : 0.033 Hz
   L23_DBC_cAC : 0.067 Hz
   L23_LBC_bAC : 0.000 Hz
   L23_LBC_bNA : 4.800 Hz
   L23_LBC_cAC : 1.150 Hz
   L23_LBC_cNA : 0.000 Hz
   L23_LBC_cST : 1.200 Hz
   L23_LBC_dNA : 4.271 Hz
   L23_MC_bAC : 0.000 Hz
   L23_MC_bNA : 0.000 Hz
   L23_MC_cNA : 0.000 Hz
   L23_MC_dNA : 0.000 Hz
   L23_NBC_bAC : 0.000 Hz
   L23_NBC_bNA : 1.400 Hz
   L23_NBC_cAC : 0.233 Hz
   L23_NBC_cIR : 0.000 Hz
   L23_NBC_cNA : 0.000 Hz
   L23_NBC_dNA : 0.900 Hz
   L23_NGC_bNA : 0.000 Hz
   L23_NGC_cAC : 0.000 Hz
   L23_NGC_cNA : 0.100 Hz
   L23_NGC_cST : 0.000 Hz
   L23_PC_cAD : 0.377 Hz
   L23_SBC_bNA : 2.800 Hz
   L23_SBC_cAC : 2.067 Hz
   L23_SBC_dNA : 1.250 Hz
   L4_BP_bAC : 0.000 Hz
   L4_BP_bIR : 0.000 Hz
   L4_BP_bNA : 0.000 Hz
   L4_BP_cAC : 0.000 Hz
   L4_BP_cNA : 11.400 Hz
   L4_BP_dST : 0.100 Hz
   L4_BTC_bAC : 2.300 Hz
   L4_BTC_bIR : 1.100 Hz
   L4_BTC_bST : 5.800 Hz
   L4_BTC_cAC : 0.000 Hz
   L4_BTC_cNA : 18.400 Hz
   L4_BTC_dNA : 3.500 Hz
   L4_ChC_cAC : 7.500 Hz
   L4_ChC_cNA : 9.200 Hz
   L4_ChC_dNA : 3.900 Hz
   L4_DBC_bAC : 1.400 Hz
   L4_DBC_bIR : 0.100 Hz
   L4_DBC_bNA : 7.100 Hz
   L4_DBC_bST : 0.100 Hz
   L4_DBC_cAC : 0.000 Hz
   L4_DBC_cIR : 0.100 Hz
   L4_DBC_cNA : 1.100 Hz
   L4_LBC_cAC : 3.600 Hz
   L4_LBC_cNA : 15.300 Hz
   L4_LBC_cST : 5.700 Hz
   L4_LBC_dNA : 63.950 Hz
   L4_LBC_dST : 7.600 Hz
   L4_MC_bAC : 0.000 Hz
   L4_MC_bNA : 0.000 Hz
   L4_MC_cAC : 0.000 Hz
   L4_MC_cNA : 0.000 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 5.400 Hz
   L4_NBC_cIR : 22.800 Hz
   L4_NBC_cNA : 1.500 Hz
   L4_NBC_dNA : 16.550 Hz
   L4_NGC_bNA : 1.600 Hz
   L4_NGC_cAC : 8.600 Hz
   L4_NGC_cNA : 10.400 Hz
   L4_NGC_cST : 0.700 Hz
   L4_PC_cAD : 3.208 Hz
   L4_SBC_bNA : 19.000 Hz
   L4_SBC_cAC : 11.900 Hz
   L4_SBC_dNA : 55.900 Hz
   L4_SP_cAD : 4.227 Hz
   L4_SS_cAD : 5.656 Hz
   L5_BP_bAC : 3.000 Hz
   L5_BP_bIR : 2.500 Hz
   L5_BP_bNA : 8.700 Hz
   L5_BP_cAC : 10.400 Hz
   L5_BP_cNA : 31.500 Hz
   L5_BP_dST : 1.200 Hz
   L5_BTC_bAC : 11.000 Hz
   L5_BTC_cAC : 12.050 Hz
   L5_BTC_cNA : 36.500 Hz
   L5_ChC_cAC : 17.400 Hz
   L5_ChC_cNA : 78.900 Hz
   L5_ChC_dNA : 6.800 Hz
   L5_DBC_bAC : 1.100 Hz
   L5_DBC_bIR : 1.900 Hz
   L5_DBC_bNA : 7.600 Hz
   L5_DBC_bST : 2.000 Hz
   L5_DBC_cAC : 7.700 Hz
   L5_DBC_cIR : 2.300 Hz
   L5_DBC_cNA : 10.600 Hz
   L5_LBC_bAC : 11.000 Hz
   L5_LBC_cAC : 22.100 Hz
   L5_LBC_cIR : 0.900 Hz
   L5_LBC_cNA : 4.700 Hz
   L5_LBC_cST : 12.750 Hz
   L5_LBC_dNA : 94.500 Hz
   L5_LBC_dST : 13.450 Hz
   L5_MC_bAC : 0.233 Hz
   L5_MC_bIR : 0.050 Hz
   L5_MC_bST : 0.000 Hz
   L5_MC_cAC : 1.483 Hz
   L5_MC_cNA : 0.800 Hz
   L5_MC_cST : 0.000 Hz
   L5_MC_dNA : 0.800 Hz
   L5_NBC_bAC : 11.000 Hz
   L5_NBC_bIR : 0.600 Hz
   L5_NBC_bST : 10.400 Hz
   L5_NBC_cAC : 16.550 Hz
   L5_NBC_cIR : 2.900 Hz
   L5_NBC_cNA : 37.550 Hz
   L5_NBC_cST : 7.450 Hz
   L5_NBC_dST : 3.900 Hz
   L5_NGC_bNA : 9.600 Hz
   L5_NGC_cAC : 13.400 Hz
   L5_NGC_cNA : 19.800 Hz
   L5_NGC_cST : 1.600 Hz
   L5_SBC_bNA : 13.300 Hz
   L5_SBC_cAC : 21.200 Hz
   L5_SBC_dNA : 13.400 Hz
   L5_STPC_cAD : 13.682 Hz
   L5_TTPC1_cAD : 7.676 Hz
   L5_TTPC2_cAD : 8.182 Hz
   L5_UTPC_cAD : 6.977 Hz
   L6_BPC_cAD : 5.164 Hz
   L6_BP_bAC : 6.500 Hz
   L6_BP_bIR : 1.300 Hz
   L6_BP_bNA : 12.300 Hz
   L6_BP_cAC : 18.400 Hz
   L6_BP_cNA : 36.400 Hz
   L6_BP_dST : 1.200 Hz
   L6_BTC_bAC : 7.000 Hz
   L6_BTC_cAC : 28.150 Hz
   L6_BTC_cNA : 7.900 Hz
   L6_ChC_cAC : 33.400 Hz
   L6_ChC_cNA : 32.500 Hz
   L6_ChC_dNA : 82.900 Hz
   L6_DBC_bAC : 4.400 Hz
   L6_DBC_bIR : 0.400 Hz
   L6_DBC_bNA : 6.800 Hz
   L6_DBC_bST : 1.000 Hz
   L6_DBC_cAC : 19.900 Hz
   L6_DBC_cIR : 2.400 Hz
   L6_DBC_cNA : 2.900 Hz
   L6_IPC_cAD : 4.206 Hz
   L6_LBC_bAC : 4.025 Hz
   L6_LBC_bIR : 3.117 Hz
   L6_LBC_bNA : 42.500 Hz
   L6_LBC_bST : 58.900 Hz
   L6_LBC_cNA : 59.100 Hz
   L6_LBC_cST : 45.850 Hz
   L6_MC_bAC : 1.600 Hz
   L6_MC_bIR : 0.200 Hz
   L6_MC_bNA : 3.300 Hz
   L6_MC_bST : 0.000 Hz
   L6_MC_cAC : 0.725 Hz
   L6_MC_cIR : 0.000 Hz
   L6_MC_cNA : 1.100 Hz
   L6_NBC_bAC : 12.000 Hz
   L6_NBC_bIR : 1.700 Hz
   L6_NBC_bST : 31.000 Hz
   L6_NBC_cAC : 15.800 Hz
   L6_NBC_cIR : 1.200 Hz
   L6_NBC_cNA : 46.700 Hz
   L6_NBC_cST : 11.450 Hz
   L6_NBC_dST : 1.800 Hz
   L6_NGC_bNA : 17.200 Hz
   L6_NGC_cAC : 11.400 Hz
   L6_NGC_cNA : 22.100 Hz
   L6_NGC_cST : 2.000 Hz
   L6_SBC_bNA : 0.300 Hz
   L6_SBC_cAC : 23.600 Hz
   L6_SBC_dNA : 17.300 Hz
   L6_TPC_L1_cAD : 4.911 Hz
   L6_TPC_L4_cAD : 5.053 Hz
   L6_UTPC_cAD : 5.778 Hz
Saving output as ../data/v8_batch2/v8_batch2_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 57.75 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
  Done; plotting time = 157.87 s

Total time = 11095.04 s

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 14038 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 14039 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 14040 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 14041 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 14042 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 14043 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 6 PID 14044 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 7 PID 14045 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 8 PID 14046 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 9 PID 14047 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 10 PID 14048 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 11 PID 14049 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 12 PID 14050 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 13 PID 14051 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 14 PID 14052 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 15 PID 14053 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 16 PID 14054 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 17 PID 14055 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 18 PID 14056 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 19 PID 14057 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 20 PID 14058 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 21 PID 14059 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 22 PID 14060 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 23 PID 14061 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 24 PID 14062 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 25 PID 14063 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 26 PID 14064 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 27 PID 14065 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 28 PID 14066 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 29 PID 14067 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 30 PID 14068 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 31 PID 14069 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 32 PID 14070 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 33 PID 14071 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 34 PID 14072 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 35 PID 14073 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 36 PID 14074 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 37 PID 14075 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 38 PID 14076 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 39 PID 14077 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 40 PID 14078 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 41 PID 14079 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 42 PID 14080 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 43 PID 14081 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 44 PID 14082 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 45 PID 14083 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 46 PID 14084 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 47 PID 14085 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 48 PID 14086 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 49 PID 14087 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 50 PID 14088 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 51 PID 14089 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 52 PID 14090 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 53 PID 14091 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 54 PID 14092 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 55 PID 14093 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 56 PID 14094 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 57 PID 14095 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 58 PID 14096 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 59 PID 14097 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 60 PID 14098 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 61 PID 14099 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 62 PID 14100 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 63 PID 14101 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 64 PID 14102 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 65 PID 14103 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 66 PID 14104 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 67 PID 14105 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 68 PID 14106 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 69 PID 14107 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 70 PID 14108 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 71 PID 14109 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 72 PID 14110 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 73 PID 14111 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 74 PID 14112 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 75 PID 14113 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 76 PID 14114 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 77 PID 14115 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 78 PID 14116 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 79 PID 14117 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 80 PID 14118 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 81 PID 14119 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 82 PID 14120 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 83 PID 14121 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 84 PID 14122 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 85 PID 14123 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 86 PID 14124 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 87 PID 14125 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 88 PID 14126 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 89 PID 14127 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 90 PID 14128 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 91 PID 14129 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 92 PID 14130 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 93 PID 14131 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 94 PID 14132 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 95 PID 14133 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 96 PID 14134 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 97 PID 14135 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 98 PID 14136 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 99 PID 14137 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 100 PID 14138 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 101 PID 14139 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 102 PID 14140 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 103 PID 14141 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 104 PID 14142 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 105 PID 14143 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 106 PID 14144 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 107 PID 14145 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 108 PID 14146 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 109 PID 14147 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 110 PID 14148 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 111 PID 14149 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 112 PID 14150 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 113 PID 14151 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 114 PID 14152 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 115 PID 14153 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 116 PID 14154 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 117 PID 14155 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 118 PID 14156 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 119 PID 14157 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 120 PID 14158 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 121 PID 14159 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 122 PID 14160 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 123 PID 14161 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 124 PID 14162 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 125 PID 14163 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 126 PID 14164 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 127 PID 14165 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 128 PID 14166 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 129 PID 14167 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 130 PID 14168 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 131 PID 14169 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 132 PID 14170 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 133 PID 14171 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 134 PID 14172 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 135 PID 14173 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 136 PID 14174 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 137 PID 14175 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 138 PID 14176 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 139 PID 14177 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 140 PID 14178 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 141 PID 14179 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 142 PID 14180 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 143 PID 14181 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 144 PID 14182 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 145 PID 14183 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 146 PID 14184 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 147 PID 14185 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 148 PID 14186 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 149 PID 14187 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 150 PID 14188 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 151 PID 14189 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 152 PID 14190 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 153 PID 14191 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 154 PID 14192 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 155 PID 14193 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 156 PID 14194 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 157 PID 14195 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 158 PID 14196 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 159 PID 14197 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 160 PID 14198 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 161 PID 14199 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 162 PID 14200 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 163 PID 14201 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 164 PID 14202 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 165 PID 14203 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 166 PID 14204 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 167 PID 14205 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 168 PID 14206 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 169 PID 14207 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 170 PID 14208 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 171 PID 14209 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 172 PID 14210 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 173 PID 14211 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 174 PID 14212 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 175 PID 14213 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 176 PID 14214 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 177 PID 14215 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 178 PID 14216 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 179 PID 14217 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 180 PID 14218 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 181 PID 14219 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 182 PID 14220 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 183 PID 14221 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 184 PID 14222 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 185 PID 14223 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 186 PID 14224 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 187 PID 14225 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 188 PID 14226 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 189 PID 14227 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 190 PID 14228 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 191 PID 14229 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 192 PID 14230 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 193 PID 14231 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 194 PID 14232 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 195 PID 14233 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 196 PID 14234 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 197 PID 14235 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 198 PID 14236 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 199 PID 14237 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 200 PID 14238 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 201 PID 14239 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 202 PID 14240 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 203 PID 14241 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 204 PID 14242 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 205 PID 14243 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 206 PID 14244 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 207 PID 14245 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 208 PID 14246 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 209 PID 14247 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 210 PID 14248 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 211 PID 14249 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 212 PID 14250 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 213 PID 14251 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 214 PID 14252 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 215 PID 14253 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 216 PID 14254 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 217 PID 14255 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 218 PID 14256 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 219 PID 14257 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 220 PID 14258 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 221 PID 14259 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 222 PID 14260 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 223 PID 14261 RUNNING AT coreneuron14jan22-1
=   KILLED BY SIGNAL: 15 (Terminated)
===================================================================================
