numprocs=80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch4/v5_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py

Start time:  2021-07-08 03:22:00.877597
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py
Importing netParams from ../data/v5_batch4/v5_batch4_netParams.py

Creating network of 61 cell populations on 80 hosts...
  Number of cells on node 72: 482 
  Number of cells on node 5: 483 
  Number of cells on node 60: 482 
  Number of cells on node 27: 483 
  Number of cells on node 48: 483 
  Number of cells on node 9: 483 
  Number of cells on node 50: 483 
  Number of cells on node 77: 482 
  Number of cells on node 42: 483 
  Number of cells on node 59: 482 
  Number of cells on node 41: 483 
  Number of cells on node 62: 482 
  Number of cells on node 38: 483 
  Number of cells on node 75: 482 
  Number of cells on node 71: 482 
  Number of cells on node 25: 483 
  Number of cells on node 37: 483 
  Number of cells on node 76: 482 
  Number of cells on node 73: 482 
  Number of cells on node 35: 483 
  Number of cells on node 32: 483 
  Number of cells on node 14: 483 
  Number of cells on node 78: 482 
  Number of cells on node 28: 483 
  Number of cells on node 7: 483 
  Number of cells on node 21: 483 
  Number of cells on node 18: 483 
  Number of cells on node 63: 482 
  Number of cells on node 29: 483 
  Number of cells on node 39: 483 
  Number of cells on node 58: 482 
  Number of cells on node 65: 482 
  Number of cells on node 11: 483 
  Number of cells on node 45: 483 
  Number of cells on node 55: 482 
  Number of cells on node 43: 483 
  Number of cells on node 68: 482 
  Number of cells on node 24: 483 
  Number of cells on node 1: 483 
  Number of cells on node 15: 483 
  Number of cells on node 54: 482 
  Number of cells on node 0: 483 
  Done; cell creation time = 30.06 s.
Making connections...
  Number of cells on node 2: 483 
  Number of cells on node 8: 483 
  Number of cells on node 22: 483 
  Number of cells on node 49: 483 
  Number of cells on node 13: 483 
  Number of cells on node 31: 483 
  Number of cells on node 40: 483 
  Number of cells on node 79: 482 
  Number of cells on node 20: 483 
  Number of cells on node 33: 483 
  Number of cells on node 26: 483 
  Number of cells on node 23: 483 
  Number of cells on node 16: 483 
  Number of cells on node 57: 482 
  Number of cells on node 53: 482 
  Number of cells on node 17: 483 
  Number of cells on node 51: 483 
  Number of cells on node 64: 482 
  Number of cells on node 52: 482 
  Number of cells on node 3: 483 
  Number of cells on node 56: 482 
  Number of cells on node 70: 482 
  Number of cells on node 47: 483 
  Number of cells on node 44: 483 
  Number of cells on node 69: 482 
  Number of cells on node 66: 482 
  Number of cells on node 36: 483 
  Number of cells on node 30: 483 
  Number of cells on node 19: 483 
  Number of cells on node 67: 482 
  Number of cells on node 61: 482 
  Number of cells on node 4: 483 
  Number of cells on node 46: 483 
  Number of cells on node 74: 482 
  Number of cells on node 34: 483 
  Number of cells on node 6: 483 
  Number of cells on node 12: 483 
  Number of cells on node 10: 483 
  Number of connections on node 24: 103871 
  Number of synaptic contacts on node 24: 982712 
  Number of connections on node 44: 103066 
  Number of synaptic contacts on node 44: 971137 
  Number of connections on node 50: 100460 
  Number of synaptic contacts on node 50: 951183 
  Number of connections on node 76: 104682 
  Number of synaptic contacts on node 76: 984252 
  Number of connections on node 34: 102013 
  Number of synaptic contacts on node 34: 963421 
  Number of connections on node 28: 102325 
  Number of synaptic contacts on node 28: 960213 
  Number of connections on node 6: 101444 
  Number of synaptic contacts on node 6: 957742 
  Number of connections on node 18: 102358 
  Number of synaptic contacts on node 18: 953949 
  Number of connections on node 72: 102558 
  Number of synaptic contacts on node 72: 963958 
  Number of connections on node 70: 102993 
  Number of synaptic contacts on node 70: 970972 
  Number of connections on node 0: 102382 
  Number of synaptic contacts on node 0: 965276 
  Number of connections on node 38: 101649 
  Number of synaptic contacts on node 38: 958224 
  Number of connections on node 20: 101452 
  Number of synaptic contacts on node 20: 950423 
  Number of connections on node 12: 102097 
  Number of synaptic contacts on node 12: 960583 
  Number of connections on node 16: 102365 
  Number of synaptic contacts on node 16: 960736 
  Number of connections on node 46: 100969 
  Number of synaptic contacts on node 46: 955843 
  Number of connections on node 22: 100459 
  Number of synaptic contacts on node 22: 948780 
  Number of connections on node 40: 103731 
  Number of synaptic contacts on node 40: 977635 
  Number of connections on node 68: 103083 
  Number of synaptic contacts on node 68: 963236 
  Number of connections on node 8: 102899 
  Number of synaptic contacts on node 8: 967516 
  Number of connections on node 36: 103272 
  Number of synaptic contacts on node 36: 975982 
  Number of connections on node 2: 102227 
  Number of synaptic contacts on node 2: 963723 
  Number of connections on node 64: 103415 
  Number of synaptic contacts on node 64: 974032 
  Number of connections on node 48: 102050 
  Number of synaptic contacts on node 48: 966391 
  Number of connections on node 52: 103132 
  Number of synaptic contacts on node 52: 970503 
  Number of connections on node 62: 101600 
  Number of synaptic contacts on node 62: 953327 
  Number of connections on node 30: 101593 
  Number of synaptic contacts on node 30: 960202 
  Number of connections on node 14: 102166 
  Number of synaptic contacts on node 14: 964866 
  Number of connections on node 32: 100077 
  Number of synaptic contacts on node 32: 937182 
  Number of connections on node 60: 102155 
  Number of synaptic contacts on node 60: 962644 
  Number of connections on node 4: 102694 
  Number of synaptic contacts on node 4: 967580 
  Number of connections on node 56: 102514 
  Number of synaptic contacts on node 56: 963736 
  Number of connections on node 26: 101172 
  Number of synaptic contacts on node 26: 959489 
  Number of connections on node 58: 103171 
  Number of synaptic contacts on node 58: 970689 
  Number of connections on node 78: 102355 
  Number of synaptic contacts on node 78: 961634 
  Number of connections on node 10: 102862 
  Number of synaptic contacts on node 10: 968396 
  Number of connections on node 54: 103406 
  Number of synaptic contacts on node 54: 975812 
  Number of connections on node 74: 103168 
  Number of synaptic contacts on node 74: 964329 
  Number of connections on node 42: 102698 
  Number of synaptic contacts on node 42: 963420 
  Number of connections on node 63: 103395 
  Number of synaptic contacts on node 63: 968681 
  Number of connections on node 23: 103216 
  Number of synaptic contacts on node 23: 971954 
  Number of connections on node 49: 101922 
  Number of synaptic contacts on node 49: 963495 
  Number of connections on node 31: 101200 
  Number of synaptic contacts on node 31: 951598 
  Number of connections on node 1: 102650 
  Number of synaptic contacts on node 1: 965861 
  Number of connections on node 43: 103149 
  Number of synaptic contacts on node 43: 971248 
  Number of connections on node 75: 104420 
  Number of synaptic contacts on node 75: 984169 
  Number of connections on node 66: 101720 
  Number of synaptic contacts on node 66: 950605 
  Number of connections on node 55: 102619 
  Number of synaptic contacts on node 55: 965424 
  Number of connections on node 57: 103926 
  Number of synaptic contacts on node 57: 983341 
  Number of connections on node 37: 104123 
  Number of synaptic contacts on node 37: 982809 
  Number of connections on node 7: 103269 
  Number of synaptic contacts on node 7: 971608 
  Number of connections on node 17: 102301 
  Number of synaptic contacts on node 17: 956997 
  Number of connections on node 53: 103166 
  Number of synaptic contacts on node 53: 972461 
  Number of connections on node 39: 101549 
  Number of synaptic contacts on node 39: 952710 
  Number of connections on node 29: 102518 
  Number of synaptic contacts on node 29: 964423 
  Number of connections on node 21: 103370 
  Number of synaptic contacts on node 21: 969892 
  Number of connections on node 61: 102103 
  Number of synaptic contacts on node 61: 955355 
  Number of connections on node 15: 101809 
  Number of synaptic contacts on node 15: 956352 
  Number of connections on node 73: 103784 
  Number of synaptic contacts on node 73: 983449 
  Number of connections on node 9: 102726 
  Number of synaptic contacts on node 9: 964709 
  Number of connections on node 11: 103070 
  Number of synaptic contacts on node 11: 967768 
  Number of connections on node 79: 102705 
  Number of synaptic contacts on node 79: 965345 
  Number of connections on node 69: 101289 
  Number of synaptic contacts on node 69: 949735 
  Number of connections on node 25: 102580 
  Number of synaptic contacts on node 25: 971144 
  Number of connections on node 41: 102644 
  Number of synaptic contacts on node 41: 968547 
  Number of connections on node 19: 102125 
  Number of synaptic contacts on node 19: 956220 
  Number of connections on node 59: 103435 
  Number of synaptic contacts on node 59: 974118 
  Number of connections on node 33: 102670 
  Number of synaptic contacts on node 33: 969458 
  Number of connections on node 65: 101919 
  Number of synaptic contacts on node 65: 953741 
  Number of connections on node 3: 100734 
  Number of synaptic contacts on node 3: 945259 
  Number of connections on node 5: 100190 
  Number of synaptic contacts on node 5: 941668 
  Number of connections on node 51: 103265 
  Number of synaptic contacts on node 51: 968487 
  Number of connections on node 67: 104476 
  Number of synaptic contacts on node 67: 979203 
  Number of connections on node 13: 101572 
  Number of synaptic contacts on node 13: 952896 
  Number of connections on node 27: 102020 
  Number of synaptic contacts on node 27: 964032 
  Number of connections on node 77: 104190 
  Number of synaptic contacts on node 77: 983078 
  Number of connections on node 45: 103183 
  Number of synaptic contacts on node 45: 974610 
  Number of connections on node 71: 100087 
  Number of synaptic contacts on node 71: 937690 
  Number of connections on node 35: 100922 
  Number of synaptic contacts on node 35: 946418 
  Number of connections on node 47: 103319 
  Number of synaptic contacts on node 47: 973659 
  Done; cell connection time = 19879.03 s.
Adding stims...
  Number of stims on node 13: 3973 
  Number of stims on node 21: 3974 
  Number of stims on node 23: 3974 
  Number of stims on node 77: 3963 
  Number of stims on node 8: 3973 
  Number of stims on node 36: 3974 
  Number of stims on node 27: 3974 
  Number of stims on node 30: 3974 
  Number of stims on node 41: 3974 
  Number of stims on node 15: 3973 
  Number of stims on node 79: 3963 
  Number of stims on node 12: 3973 
  Number of stims on node 39: 3974 
  Number of stims on node 38: 3974 
  Number of stims on node 76: 3963 
  Number of stims on node 4: 3973 
  Number of stims on node 58: 3973 
  Number of stims on node 19: 3973 
  Number of stims on node 54: 3973 
  Number of stims on node 42: 3974 
  Number of stims on node 25: 3974 
  Number of stims on node 72: 3963 
  Number of stims on node 35: 3974 
  Number of stims on node 31: 3974 
  Number of stims on node 47: 3974 
  Number of stims on node 10: 3973 
  Number of stims on node 20: 3973 
  Number of stims on node 32: 3974 
  Number of stims on node 66: 3963 
  Number of stims on node 70: 3963 
  Number of stims on node 43: 3974 
  Number of stims on node 65: 3973 
  Number of stims on node 28: 3974 
  Number of stims on node 64: 3973 
  Number of stims on node 29: 3974 
  Number of stims on node 69: 3963 
  Number of stims on node 50: 3974 
  Number of stims on node 51: 3974 
  Number of stims on node 40: 3974 
  Number of stims on node 67: 3963 
  Number of stims on node 73: 3963 
  Number of stims on node 60: 3973 
  Number of stims on node 45: 3974 
  Number of stims on node 75: 3963 
  Number of stims on node 7: 3973 
  Number of stims on node 59: 3973 
  Number of stims on node 14: 3973 
  Number of stims on node 16: 3973 
  Number of stims on node 1: 3973 
  Number of stims on node 78: 3963 
  Number of stims on node 37: 3974 
  Number of stims on node 74: 3963 
  Number of stims on node 22: 3974 
  Number of stims on node 3: 3973 
  Number of stims on node 56: 3973 
  Number of stims on node 11: 3973 
  Number of stims on node 17: 3973 
  Number of stims on node 0: 3973 
  Number of stims on node 57: 3973 
  Number of stims on node 24: 3974 
  Number of stims on node 49: 3974 
  Number of stims on node 33: 3974 
  Number of stims on node 2: 3973 
  Number of stims on node 71: 3963 
  Number of stims on node 9: 3973 
  Number of stims on node 62: 3973 
  Number of stims on node 68: 3963 
  Number of stims on node 61: 3973 
  Number of stims on node 46: 3974 
  Number of stims on node 44: 3974 
  Number of stims on node 63: 3973 
  Number of stims on node 34: 3974 
  Number of stims on node 26: 3974 
  Number of stims on node 55: 3973 
  Number of stims on node 5: 3973 
  Number of stims on node 52: 3973 
  Number of stims on node 53: 3973 
  Number of stims on node 6: 3973 
  Number of stims on node 18: 3973 
  Done; cell stims creation time = 11.37 s.
  Number of stims on node 48: 3974 
Recording 10 traces of 1 types on node 53
Recording 14 traces of 1 types on node 20
Recording 12 traces of 1 types on node 33
Recording 15 traces of 1 types on node 62
Recording 14 traces of 1 types on node 4
Recording 16 traces of 1 types on node 5
Recording 8 traces of 1 types on node 19
Recording 16 traces of 1 types on node 70
Recording 12 traces of 1 types on node 2
Recording 17 traces of 1 types on node 64
Recording 11 traces of 1 types on node 36
Recording 15 traces of 1 types on node 14
Recording 10 traces of 1 types on node 43
Recording 11 traces of 1 types on node 34
Recording 14 traces of 1 types on node 27
Recording 17 traces of 1 types on node 49
Recording 8 traces of 1 types on node 71
Recording 15 traces of 1 types on node 28
Recording 16 traces of 1 types on node 54
Recording 15 traces of 1 types on node 45
Recording 11 traces of 1 types on node 15
Recording 9 traces of 1 types on node 77
Recording 11 traces of 1 types on node 9
Recording 17 traces of 1 types on node 42
Recording 14 traces of 1 types on node 0
Recording 14 traces of 1 types on node 23
Recording 16 traces of 1 types on node 67
Recording 7 traces of 1 types on node 47
Recording 11 traces of 1 types on node 30
Recording 13 traces of 1 types on node 73
Recording 14 traces of 1 types on node 18
Recording 9 traces of 1 types on node 17
Recording 12 traces of 1 types on node 39
Recording 12 traces of 1 types on node 68
Recording 17 traces of 1 types on node 16
Recording 12 traces of 1 types on node 44
Recording 16 traces of 1 types on node 46
Recording 15 traces of 1 types on node 38
Recording 18 traces of 1 types on node 11
Recording 12 traces of 1 types on node 56
Recording 17 traces of 1 types on node 66
Recording 9 traces of 1 types on node 24
Recording 18 traces of 1 types on node 72
Recording 12 traces of 1 types on node 50
Recording 4 traces of 1 types on node 79
Recording 17 traces of 1 types on node 22
Recording 11 traces of 1 types on node 61
Recording 13 traces of 1 types on node 78
Recording 10 traces of 1 types on node 13
Recording 8 traces of 1 types on node 69
Recording 10 traces of 1 types on node 75
Recording 16 traces of 1 types on node 57
Recording 16 traces of 1 types on node 60
Recording 15 traces of 1 types on node 76
Recording 10 traces of 1 types on node 37
Recording 8 traces of 1 types on node 7
Recording 11 traces of 1 types on node 21
Recording 15 traces of 1 types on node 52
Recording 10 traces of 1 types on node 59
Recording 13 traces of 1 types on node 25
Recording 14 traces of 1 types on node 58
Recording 10 traces of 1 types on node 10
Recording 7 traces of 1 types on node 41
Recording 12 traces of 1 types on node 74
Recording 9 traces of 1 types on node 8
Recording 10 traces of 1 types on node 1
Recording 11 traces of 1 types on node 32
Recording 15 traces of 1 types on node 40
Recording 15 traces of 1 types on node 35
Recording 13 traces of 1 types on node 12
Recording 9 traces of 1 types on node 63
Recording 13 traces of 1 types on node 3
Recording 15 traces of 1 types on node 29
Recording 14 traces of 1 types on node 51
Recording 16 traces of 1 types on node 55
Recording 6 traces of 1 types on node 65
Recording 19 traces of 1 types on node 31
Recording 10 traces of 1 types on node 6
Recording 16 traces of 1 types on node 26
Recording 14 traces of 1 types on node 48
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 41555.34 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 15.54 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 223752 (2.90 Hz)
  Simulated time: 2.0 s; 80 workers
  Run time: 41555.34 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.019 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.268 Hz
   L23_BTC : 0.096 Hz
   L23_ChC : 0.541 Hz
   L23_DBC : 0.063 Hz
   L23_LBC : 0.889 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.278 Hz
   L23_NGC : 0.045 Hz
   L23_PC : 0.159 Hz
   L23_SBC : 0.973 Hz
   L4_BP : 1.812 Hz
   L4_BTC : 0.525 Hz
   L4_ChC : 1.062 Hz
   L4_DBC : 0.450 Hz
   L4_LBC : 3.283 Hz
   L4_MC : 0.013 Hz
   L4_NBC : 5.943 Hz
   L4_NGC : 0.500 Hz
   L4_PC : 0.643 Hz
   L4_SBC : 3.500 Hz
   L4_SP : 0.934 Hz
   L4_SS : 1.117 Hz
   L5_BP : 5.206 Hz
   L5_BTC : 1.309 Hz
   L5_ChC : 5.842 Hz
   L5_DBC : 0.932 Hz
   L5_LBC : 7.988 Hz
   L5_MC : 0.103 Hz
   L5_NBC : 6.771 Hz
   L5_NGC : 12.000 Hz
   L5_SBC : 7.820 Hz
   L5_STPC : 1.119 Hz
   L5_TTPC1 : 1.093 Hz
   L5_TTPC2 : 1.092 Hz
   L5_UTPC : 1.465 Hz
   L6_BPC : 1.077 Hz
   L6_BP : 4.479 Hz
   L6_BTC : 3.398 Hz
   L6_ChC : 5.281 Hz
   L6_DBC : 3.113 Hz
   L6_IPC : 2.119 Hz
   L6_LBC : 8.449 Hz
   L6_MC : 0.146 Hz
   L6_NBC : 8.116 Hz
   L6_NGC : 9.441 Hz
   L6_SBC : 7.500 Hz
   L6_TPC_L1 : 1.329 Hz
   L6_TPC_L4 : 2.058 Hz
   L6_UTPC : 1.911 Hz
   ss_RTN_o : 12.704 Hz
   ss_RTN_m : 13.918 Hz
   ss_RTN_i : 10.677 Hz
   VPL_sTC : 8.595 Hz
   VPM_sTC : 8.035 Hz
   POm_sTC_s1 : 7.436 Hz
Saving output as ../data/v5_batch4/v5_batch4_0_0.json  ... 
Finished saving!
  Done; saving time = 34.39 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 386.67 s

Total time = 61965.37 s

End time:  2021-07-08 20:34:46.251832
