numprocs=80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch9/v5_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py

Start time:  2021-07-11 16:19:37.961289
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py
Importing netParams from ../data/v5_batch9/v5_batch9_netParams.py

Creating network of 61 cell populations on 80 hosts...
  Number of cells on node 49: 483 
  Number of cells on node 30: 483 
  Number of cells on node 19: 483 
  Number of cells on node 48: 483 
  Number of cells on node 77: 482 
  Number of cells on node 66: 482 
  Number of cells on node 47: 483 
  Number of cells on node 25: 483 
  Number of cells on node 75: 482 
  Number of cells on node 28: 483 
  Number of cells on node 78: 482 
  Number of cells on node 13: 483 
  Number of cells on node 67: 482 
  Number of cells on node 76: 482 
  Number of cells on node 54: 482 
  Number of cells on node 23: 483 
  Number of cells on node 35: 483 
  Number of cells on node 50: 483 
  Number of cells on node 7: 483 
  Number of cells on node 51: 483 
  Number of cells on node 4: 483 
  Number of cells on node 65: 482 
  Number of cells on node 20: 483 
  Number of cells on node 9: 483 
  Number of cells on node 11: 483 
  Number of cells on node 36: 483 
  Number of cells on node 1: 483 
  Number of cells on node 17: 483 
  Number of cells on node 68: 482 
  Number of cells on node 38: 483 
  Number of cells on node 27: 483 
  Number of cells on node 79: 482 
  Number of cells on node 42: 483 
  Number of cells on node 70: 482 
  Number of cells on node 39: 483 
  Number of cells on node 33: 483 
  Number of cells on node 37: 483 
  Number of cells on node 43: 483 
  Number of cells on node 8: 483 
  Number of cells on node 55: 482 
  Number of cells on node 12: 483 
  Number of cells on node 18: 483 
  Number of cells on node 14: 483 
  Number of cells on node 3: 483 
  Number of cells on node 53: 482 
  Number of cells on node 31: 483 
  Number of cells on node 6: 483 
  Number of cells on node 15: 483 
  Number of cells on node 71: 482 
  Number of cells on node 41: 483 
  Number of cells on node 44: 483 
  Number of cells on node 59: 482 
  Number of cells on node 10: 483 
  Number of cells on node 45: 483 
  Number of cells on node 52: 482 
  Number of cells on node 57: 482 
  Number of cells on node 69: 482 
  Number of cells on node 63: 482 
  Number of cells on node 56: 482 
  Number of cells on node 61: 482 
  Number of cells on node 64: 482 
  Number of cells on node 72: 482 
  Number of cells on node 26: 483 
  Number of cells on node 73: 482 
  Number of cells on node 40: 483 
  Number of cells on node 46: 483 
  Number of cells on node 24: 483 
  Number of cells on node 5: 483 
  Number of cells on node 29: 483 
  Number of cells on node 22: 483 
  Number of cells on node 16: 483 
  Number of cells on node 0: 483 
  Done; cell creation time = 27.98 s.
Making connections...
  Number of cells on node 74: 482 
  Number of cells on node 2: 483 
  Number of cells on node 58: 482 
  Number of cells on node 34: 483 
  Number of cells on node 62: 482 
  Number of cells on node 32: 483 
  Number of cells on node 21: 483 
  Number of cells on node 60: 482 
  Number of connections on node 52: 1714 
  Number of synaptic contacts on node 52: 2065 
  Number of connections on node 32: 1911 
  Number of synaptic contacts on node 32: 2304 
  Number of connections on node 17: 1882 
  Number of synaptic contacts on node 17: 2263 
  Number of connections on node 58: 1759 
  Number of synaptic contacts on node 58: 2095 
  Number of connections on node 44: 1901 
  Number of synaptic contacts on node 44: 2293 
  Number of connections on node 18: 1874 
  Number of synaptic contacts on node 18: 2273 
  Number of connections on node 47: 1833 
  Number of synaptic contacts on node 47: 2189 
  Number of connections on node 21: 1841 
  Number of synaptic contacts on node 21: 2242 
  Number of connections on node 30: 1812 
  Number of synaptic contacts on node 30: 2162 
  Number of connections on node 46: 1801 
  Number of synaptic contacts on node 46: 2183 
  Number of connections on node 6: 1947 
  Number of synaptic contacts on node 6: 2366 
  Number of connections on node 70: 1765 
  Number of synaptic contacts on node 70: 2132 
  Number of connections on node 26: 1768 
  Number of synaptic contacts on node 26: 2169 
  Number of connections on node 36: 1871 
  Number of synaptic contacts on node 36: 2216 
  Number of connections on node 73: 1894 
  Number of synaptic contacts on node 73: 2267 
  Number of connections on node 42: 1921 
  Number of synaptic contacts on node 42: 2306 
  Number of connections on node 50: 1693 
  Number of synaptic contacts on node 50: 2089 
  Number of connections on node 40: 1818 
  Number of synaptic contacts on node 40: 2237 
  Number of connections on node 76: 1941 
  Number of synaptic contacts on node 76: 2342 
  Number of connections on node 16: 1903 
  Number of synaptic contacts on node 16: 2250 
  Number of connections on node 11: 1981 
  Number of synaptic contacts on node 11: 2380 
  Number of connections on node 51: 1817 
  Number of synaptic contacts on node 51: 2245 
  Number of connections on node 12: 1806 
  Number of synaptic contacts on node 12: 2213 
  Number of connections on node 68: 1822 
  Number of synaptic contacts on node 68: 2220 
  Number of connections on node 63: 1710 
  Number of synaptic contacts on node 63: 2085 
  Number of connections on node 48: 1693 
  Number of synaptic contacts on node 48: 2091 
  Number of connections on node 24: 1674 
  Number of synaptic contacts on node 24: 2034 
  Number of connections on node 62: 1726 
  Number of synaptic contacts on node 62: 2073 
  Number of connections on node 69: 1938 
  Number of synaptic contacts on node 69: 2323 
  Number of connections on node 38: 1665 
  Number of synaptic contacts on node 38: 2018 
  Number of connections on node 64: 1773 
  Number of synaptic contacts on node 64: 2152 
  Number of connections on node 4: 1874 
  Number of synaptic contacts on node 4: 2212 
  Number of connections on node 35: 1728 
  Number of synaptic contacts on node 35: 2084 
  Number of connections on node 22: 1854 
  Number of synaptic contacts on node 22: 2250 
  Number of connections on node 43: 1801 
  Number of synaptic contacts on node 43: 2180 
  Number of connections on node 25: 1753 
  Number of synaptic contacts on node 25: 2126 
  Number of connections on node 78: 1846 
  Number of synaptic contacts on node 78: 2196 
  Number of connections on node 5: 1816 
  Number of synaptic contacts on node 5: 2240 
  Number of connections on node 56: 1807 
  Number of synaptic contacts on node 56: 2162 
  Number of connections on node 74: 1997 
  Number of synaptic contacts on node 74: 2365 
  Number of connections on node 72: 1834 
  Number of synaptic contacts on node 72: 2196 
  Number of connections on node 14: 1796 
  Number of synaptic contacts on node 14: 2170 
  Number of connections on node 49: 1823 
  Number of synaptic contacts on node 49: 2211 
  Number of connections on node 60: 1838 
  Number of synaptic contacts on node 60: 2220 
  Number of connections on node 0: 1913 
  Number of synaptic contacts on node 0: 2316 
  Number of connections on node 79: 1856 
  Number of synaptic contacts on node 79: 2229 
  Number of connections on node 54: 1878 
  Number of synaptic contacts on node 54: 2262 
  Number of connections on node 59: 1761 
  Number of synaptic contacts on node 59: 2110 
  Number of connections on node 23: 1852 
  Number of synaptic contacts on node 23: 2250 
  Number of connections on node 7: 1737 
  Number of synaptic contacts on node 7: 2084 
  Number of connections on node 20: 1743 
  Number of synaptic contacts on node 20: 2127 
  Number of connections on node 57: 1879 
  Number of synaptic contacts on node 57: 2267 
  Number of connections on node 28: 1717 
  Number of synaptic contacts on node 28: 2093 
  Number of connections on node 34: 1752 
  Number of synaptic contacts on node 34: 2165 
  Number of connections on node 45: 1673 
  Number of synaptic contacts on node 45: 2070 
  Number of connections on node 66: 1960 
  Number of synaptic contacts on node 66: 2317 
  Number of connections on node 2: 1941 
  Number of synaptic contacts on node 2: 2319 
  Number of connections on node 13: 1824 
  Number of synaptic contacts on node 13: 2204 
  Number of connections on node 31: 1790 
  Number of synaptic contacts on node 31: 2162 
  Number of connections on node 75: 1785 
  Number of synaptic contacts on node 75: 2149 
  Number of connections on node 9: 1875 
  Number of synaptic contacts on node 9: 2287 
  Number of connections on node 65: 1729 
  Number of synaptic contacts on node 65: 2095 
  Number of connections on node 10: 1832 
  Number of synaptic contacts on node 10: 2222 
  Number of connections on node 1: 1807 
  Number of synaptic contacts on node 1: 2201 
  Number of connections on node 3: 1887 
  Number of synaptic contacts on node 3: 2265 
  Number of connections on node 37: 1767 
  Number of synaptic contacts on node 37: 2135 
  Number of connections on node 19: 1864 
  Number of synaptic contacts on node 19: 2252 
  Number of connections on node 8: 1902 
  Number of synaptic contacts on node 8: 2278 
  Number of connections on node 41: 1759 
  Number of synaptic contacts on node 41: 2143 
  Number of connections on node 67: 1924 
  Number of synaptic contacts on node 67: 2255 
  Number of connections on node 33: 1785 
  Number of synaptic contacts on node 33: 2152 
  Number of connections on node 55: 1852 
  Number of synaptic contacts on node 55: 2226 
  Number of connections on node 61: 1747 
  Number of synaptic contacts on node 61: 2093 
  Number of connections on node 77: 1817 
  Number of synaptic contacts on node 77: 2168 
  Number of connections on node 15: 1879 
  Number of synaptic contacts on node 15: 2244 
  Number of connections on node 53: 1778 
  Number of synaptic contacts on node 53: 2115 
  Number of connections on node 39: 1723 
  Number of synaptic contacts on node 39: 2088 
  Number of connections on node 29: 1861 
  Number of synaptic contacts on node 29: 2243 
  Number of connections on node 27: 1715 
  Number of synaptic contacts on node 27: 2084 
  Done; cell connection time = 291.39 s.
  Number of connections on node 71: 1865 
  Number of synaptic contacts on node 71: 2246 
Adding stims...
  Number of stims on node 70: 3963 
  Number of stims on node 48: 3974 
  Number of stims on node 30: 3974 
  Number of stims on node 0: 3973 
  Number of stims on node 16: 3973 
  Number of stims on node 19: 3973 
  Number of stims on node 71: 3963 
  Number of stims on node 72: 3963 
  Number of stims on node 54: 3973 
  Number of stims on node 26: 3974 
  Number of stims on node 39: 3974 
  Number of stims on node 75: 3963 
  Number of stims on node 62: 3973 
  Number of stims on node 28: 3974 
  Number of stims on node 69: 3963 
  Number of stims on node 50: 3974 
  Number of stims on node 8: 3973 
  Number of stims on node 68: 3963 
  Number of stims on node 24: 3974 
  Number of stims on node 22: 3974 
  Number of stims on node 59: 3973 
  Number of stims on node 10: 3973 
  Number of stims on node 29: 3974 
  Number of stims on node 2: 3973 
  Number of stims on node 46: 3974 
  Number of stims on node 13: 3973 
  Number of stims on node 37: 3974 
  Number of stims on node 9: 3973 
  Number of stims on node 35: 3974 
  Number of stims on node 55: 3973 
  Number of stims on node 12: 3973 
  Number of stims on node 67: 3963 
  Number of stims on node 63: 3973 
  Number of stims on node 58: 3973 
  Number of stims on node 27: 3974 
  Number of stims on node 11: 3973 
  Number of stims on node 36: 3974 
  Number of stims on node 47: 3974 
  Number of stims on node 64: 3973 
  Number of stims on node 17: 3973 
  Number of stims on node 43: 3974 
  Number of stims on node 76: 3963 
  Number of stims on node 65: 3973 
  Number of stims on node 23: 3974 
  Number of stims on node 14: 3973 
  Number of stims on node 78: 3963 
  Number of stims on node 41: 3974 
  Number of stims on node 66: 3963 
  Number of stims on node 61: 3973 
  Number of stims on node 6: 3973 
  Number of stims on node 34: 3974 
  Number of stims on node 79: 3963 
  Number of stims on node 31: 3974 
  Number of stims on node 25: 3974 
  Number of stims on node 21: 3974 
  Number of stims on node 1: 3973 
  Number of stims on node 56: 3973 
  Number of stims on node 73: 3963 
  Number of stims on node 45: 3974 
  Number of stims on node 57: 3973 
  Number of stims on node 3: 3973 
  Number of stims on node 5: 3973 
  Number of stims on node 51: 3974 
  Number of stims on node 38: 3974 
  Number of stims on node 20: 3973 
  Number of stims on node 4: 3973 
  Number of stims on node 53: 3973 
  Number of stims on node 40: 3974 
  Number of stims on node 18: 3973 
  Number of stims on node 49: 3974 
  Number of stims on node 60: 3973 
  Number of stims on node 42: 3974 
  Number of stims on node 7: 3973 
  Number of stims on node 15: 3973 
  Number of stims on node 74: 3963 
  Number of stims on node 33: 3974 
  Number of stims on node 77: 3963 
  Number of stims on node 32: 3974 
  Number of stims on node 44: 3974 
  Done; cell stims creation time = 11.32 s.
  Number of stims on node 52: 3973 
Recording 0 traces of 0 types on node 8
Recording 1 traces of 1 types on node 34
Recording 0 traces of 0 types on node 75
Recording 1 traces of 1 types on node 0
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 48
Recording 1 traces of 1 types on node 38
Recording 2 traces of 1 types on node 70
Recording 1 traces of 1 types on node 22
Recording 1 traces of 1 types on node 32
Recording 1 traces of 1 types on node 3
Recording 1 traces of 1 types on node 30
Recording 0 traces of 0 types on node 49
Recording 1 traces of 1 types on node 67
Recording 1 traces of 1 types on node 59
Recording 1 traces of 1 types on node 5
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 52
Recording 3 traces of 1 types on node 50
Recording 0 traces of 0 types on node 31
Recording 2 traces of 1 types on node 42
Recording 0 traces of 0 types on node 39
Recording 1 traces of 1 types on node 44
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 69
Recording 2 traces of 1 types on node 66
Recording 0 traces of 0 types on node 45
Recording 0 traces of 0 types on node 65
Recording 1 traces of 1 types on node 10
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 24
Recording 1 traces of 1 types on node 76
Recording 0 traces of 0 types on node 6
Recording 1 traces of 1 types on node 51
Recording 1 traces of 1 types on node 2
Recording 0 traces of 0 types on node 19
Recording 1 traces of 1 types on node 14
Recording 0 traces of 0 types on node 64
Recording 1 traces of 1 types on node 60
Recording 2 traces of 1 types on node 46
Recording 0 traces of 0 types on node 71
Recording 1 traces of 1 types on node 55
Recording 0 traces of 0 types on node 79
Recording 1 traces of 1 types on node 36
Recording 1 traces of 1 types on node 23
Recording 1 traces of 1 types on node 16
Recording 0 traces of 0 types on node 33
Recording 0 traces of 0 types on node 17
Recording 1 traces of 1 types on node 12
Recording 0 traces of 0 types on node 35
Recording 0 traces of 0 types on node 43
Recording 0 traces of 0 types on node 56
Recording 0 traces of 0 types on node 78
Recording 2 traces of 1 types on node 11
Recording 2 traces of 1 types on node 26
Recording 0 traces of 0 types on node 63
Recording 2 traces of 1 types on node 54
Recording 1 traces of 1 types on node 62
Recording 0 traces of 0 types on node 61
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 41
Recording 1 traces of 1 types on node 40
Recording 0 traces of 0 types on node 1
Recording 1 traces of 1 types on node 47
Recording 0 traces of 0 types on node 9
Recording 1 traces of 1 types on node 29
Recording 1 traces of 1 types on node 7
Recording 0 traces of 0 types on node 77
Recording 0 traces of 0 types on node 53
Recording 2 traces of 1 types on node 68
Recording 1 traces of 1 types on node 73
Recording 1 traces of 1 types on node 21
Recording 3 traces of 1 types on node 18
Recording 0 traces of 0 types on node 15
Recording 1 traces of 1 types on node 37
Recording 2 traces of 1 types on node 57
Recording 2 traces of 1 types on node 72
Recording 2 traces of 1 types on node 13
Recording 2 traces of 1 types on node 58
Recording 1 traces of 1 types on node 74
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 16278.85 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 10.31 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 295675 (3.83 Hz)
  Simulated time: 2.0 s; 80 workers
  Run time: 16278.85 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.143 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.082 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 1.269 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.073 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.279 Hz
   L23_SBC : 1.825 Hz
   L4_BP : 2.188 Hz
   L4_BTC : 4.150 Hz
   L4_ChC : 10.188 Hz
   L4_DBC : 0.263 Hz
   L4_LBC : 13.008 Hz
   L4_MC : 0.004 Hz
   L4_NBC : 17.578 Hz
   L4_NGC : 0.917 Hz
   L4_PC : 1.346 Hz
   L4_SBC : 16.992 Hz
   L4_SP : 2.712 Hz
   L4_SS : 3.198 Hz
   L5_BP : 11.176 Hz
   L5_BTC : 7.980 Hz
   L5_ChC : 21.211 Hz
   L5_DBC : 1.661 Hz
   L5_LBC : 19.819 Hz
   L5_MC : 0.023 Hz
   L5_NBC : 17.948 Hz
   L5_NGC : 16.062 Hz
   L5_SBC : 18.460 Hz
   L5_STPC : 3.929 Hz
   L5_TTPC1 : 2.842 Hz
   L5_TTPC2 : 3.112 Hz
   L5_UTPC : 5.306 Hz
   L6_BPC : 1.911 Hz
   L6_BP : 9.393 Hz
   L6_BTC : 7.824 Hz
   L6_ChC : 25.656 Hz
   L6_DBC : 4.000 Hz
   L6_IPC : 2.818 Hz
   L6_LBC : 18.515 Hz
   L6_MC : 0.025 Hz
   L6_NBC : 20.869 Hz
   L6_NGC : 17.059 Hz
   L6_SBC : 33.657 Hz
   L6_TPC_L1 : 2.529 Hz
   L6_TPC_L4 : 3.395 Hz
   L6_UTPC : 3.544 Hz
   ss_RTN_o : 10.650 Hz
   ss_RTN_m : 12.173 Hz
   ss_RTN_i : 10.677 Hz
   VPL_sTC : 5.224 Hz
   VPM_sTC : 5.634 Hz
   POm_sTC_s1 : 7.436 Hz
Saving output as ../data/v5_batch9/v5_batch9_0_0.json  ... 
Finished saving!
  Done; saving time = 3.60 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 282.77 s

Total time = 16939.25 s

End time:  2021-07-11 21:01:57.206849
--------------------------------------------------------------------------
mpiexec noticed that process rank 17 with PID 34050 on node high-mem exited on signal 15 (Terminated).
--------------------------------------------------------------------------
