numprocs=64

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch3/v6_batch3_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py

Start time:  2021-12-09 19:59:57.129658
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py
Importing netParams from ../data/v6_batch3/v6_batch3_netParams.py

Creating network of 213 cell populations on 64 hosts...
  Number of cells on node 60: 603 
  Number of cells on node 25: 603 
  Number of cells on node 22: 603 
  Number of cells on node 1: 604 
  Number of cells on node 59: 603 
  Number of cells on node 19: 604 
  Number of cells on node 63: 603 
  Number of cells on node 58: 603 
  Number of cells on node 56: 603 
  Number of cells on node 36: 603 
  Number of cells on node 43: 603 
  Number of cells on node 41: 603 
  Number of cells on node 21: 603 
  Number of cells on node 32: 603 
  Number of cells on node 5: 604 
  Number of cells on node 51: 603 
  Number of cells on node 47: 603 
  Number of cells on node 3: 604 
  Number of cells on node 8: 604 
  Number of cells on node 7: 604 
  Number of cells on node 4: 604 
  Number of cells on node 38: 603 
  Number of cells on node 48: 603 
  Number of cells on node 42: 603 
  Number of cells on node 18: 604 
  Number of cells on node 16: 604 
  Number of cells on node 54: 603 
  Number of cells on node 20: 603 
  Number of cells on node 2: 604 
  Number of cells on node 24: 603 
  Number of cells on node 14: 604 
  Number of cells on node 34: 603 
  Number of cells on node 17: 604 
  Number of cells on node 15: 604 
  Number of cells on node 52: 603 
  Number of cells on node 28: 603 
  Number of cells on node 6: 604 
  Number of cells on node 37: 603 
  Number of cells on node 9: 604 
  Number of cells on node 44: 603 
  Number of cells on node 31: 603 
  Number of cells on node 0: 604 
  Done; cell creation time = 37.21 s.
Making connections...
  Number of cells on node 30: 603 
  Number of cells on node 10: 604 
  Number of cells on node 29: 603 
  Number of cells on node 40: 603 
  Number of cells on node 27: 603 
  Number of cells on node 55: 603 
  Number of cells on node 53: 603 
  Number of cells on node 35: 603 
  Number of cells on node 62: 603 
  Number of cells on node 39: 603 
  Number of cells on node 26: 603 
  Number of cells on node 57: 603 
  Number of cells on node 11: 604 
  Number of cells on node 49: 603 
  Number of cells on node 61: 603 
  Number of cells on node 45: 603 
  Number of cells on node 12: 604 
  Number of cells on node 50: 603 
  Number of cells on node 46: 603 
  Number of cells on node 23: 603 
  Number of cells on node 33: 603 
  Number of cells on node 13: 604 
  Number of connections on node 58: 153914 
  Number of synaptic contacts on node 58: 794165 
  Number of connections on node 26: 155047 
  Number of synaptic contacts on node 26: 799468 
  Number of connections on node 18: 152452 
  Number of synaptic contacts on node 18: 785366 
  Number of connections on node 2: 154448 
  Number of synaptic contacts on node 2: 796425 
  Number of connections on node 60: 155530 
  Number of synaptic contacts on node 60: 801223 
  Number of connections on node 42: 153621 
  Number of synaptic contacts on node 42: 790957 
  Number of connections on node 14: 155630 
  Number of synaptic contacts on node 14: 804648 
  Number of connections on node 22: 152826 
  Number of synaptic contacts on node 22: 791173 
  Number of connections on node 19: 154162 
  Number of synaptic contacts on node 19: 799401 
  Number of connections on node 52: 156340 
  Number of synaptic contacts on node 52: 806732 
  Number of connections on node 8: 156171 
  Number of synaptic contacts on node 8: 807084 
  Number of connections on node 44: 154681 
  Number of synaptic contacts on node 44: 797853 
  Number of connections on node 13: 151848 
  Number of synaptic contacts on node 13: 781769 
  Number of connections on node 54: 153377 
  Number of synaptic contacts on node 54: 792080 
  Number of connections on node 16: 154313 
  Number of synaptic contacts on node 16: 797658 
  Number of connections on node 21: 152820 
  Number of synaptic contacts on node 21: 788683 
  Number of connections on node 48: 154305 
  Number of synaptic contacts on node 48: 795629 
  Number of connections on node 62: 154444 
  Number of synaptic contacts on node 62: 800043 
  Number of connections on node 20: 154159 
  Number of synaptic contacts on node 20: 796154 
  Number of connections on node 10: 155050 
  Number of synaptic contacts on node 10: 799377 
  Number of connections on node 12: 153827 
  Number of synaptic contacts on node 12: 796922 
  Number of connections on node 3: 151036 
  Number of synaptic contacts on node 3: 782075 
  Number of connections on node 9: 154681 
  Number of synaptic contacts on node 9: 803291 
  Number of connections on node 36: 156097 
  Number of synaptic contacts on node 36: 803204 
  Number of connections on node 17: 155879 
  Number of synaptic contacts on node 17: 807220 
  Number of connections on node 50: 152878 
  Number of synaptic contacts on node 50: 788284 
  Number of connections on node 63: 153789 
  Number of synaptic contacts on node 63: 790783 
  Number of connections on node 53: 155746 
  Number of synaptic contacts on node 53: 804351 
  Number of connections on node 11: 154691 
  Number of synaptic contacts on node 11: 799186 
  Number of connections on node 6: 153046 
  Number of synaptic contacts on node 6: 788866 
  Number of connections on node 55: 153157 
  Number of synaptic contacts on node 55: 792239 
  Number of connections on node 0: 152198 
  Number of synaptic contacts on node 0: 786163 
  Number of connections on node 1: 150936 
  Number of synaptic contacts on node 1: 781297 
  Number of connections on node 57: 155513 
  Number of synaptic contacts on node 57: 801547 
  Number of connections on node 5: 154417 
  Number of synaptic contacts on node 5: 798205 
  Number of connections on node 27: 156879 
  Number of synaptic contacts on node 27: 810452 
  Number of connections on node 40: 154986 
  Number of synaptic contacts on node 40: 801148 
  Number of connections on node 51: 154149 
  Number of synaptic contacts on node 51: 789641 
  Number of connections on node 35: 156660 
  Number of synaptic contacts on node 35: 805938 
  Number of connections on node 30: 150527 
  Number of synaptic contacts on node 30: 775118 
  Number of connections on node 7: 153791 
  Number of synaptic contacts on node 7: 794016 
  Number of connections on node 49: 153317 
  Number of synaptic contacts on node 49: 789797 
  Number of connections on node 24: 155197 
  Number of synaptic contacts on node 24: 803051 
  Number of connections on node 33: 155296 
  Number of synaptic contacts on node 33: 797843 
  Number of connections on node 56: 153613 
  Number of synaptic contacts on node 56: 791406 
  Number of connections on node 47: 154903 
  Number of synaptic contacts on node 47: 795680 
  Number of connections on node 34: 153507 
  Number of synaptic contacts on node 34: 791836 
  Number of connections on node 28: 155253 
  Number of synaptic contacts on node 28: 800905 
  Number of connections on node 61: 155004 
  Number of synaptic contacts on node 61: 803035 
  Number of connections on node 38: 152818 
  Number of synaptic contacts on node 38: 786362 
  Number of connections on node 4: 152003 
  Number of synaptic contacts on node 4: 782062 
  Number of connections on node 29: 158118 
  Number of synaptic contacts on node 29: 815732 
  Number of connections on node 32: 153366 
  Number of synaptic contacts on node 32: 788970 
  Number of connections on node 59: 154555 
  Number of synaptic contacts on node 59: 799251 
  Number of connections on node 39: 153853 
  Number of synaptic contacts on node 39: 792738 
  Number of connections on node 45: 153188 
  Number of synaptic contacts on node 45: 790362 
  Number of connections on node 25: 154519 
  Number of synaptic contacts on node 25: 799589 
  Number of connections on node 41: 154476 
  Number of synaptic contacts on node 41: 797420 
  Number of connections on node 15: 154269 
  Number of synaptic contacts on node 15: 797000 
  Number of connections on node 46: 152714 
  Number of synaptic contacts on node 46: 790255 
  Number of connections on node 23: 155153 
  Number of synaptic contacts on node 23: 803919 
  Number of connections on node 37: 154855 
  Number of synaptic contacts on node 37: 799649 
  Number of connections on node 43: 153444 
  Number of synaptic contacts on node 43: 789464 
  Number of connections on node 31: 152926 
  Number of synaptic contacts on node 31: 787396 
  Done; cell connection time = 19264.54 s.
Adding stims...
  Number of stims on node 27: 4966 
  Number of stims on node 11: 4967 
  Number of stims on node 56: 4957 
  Number of stims on node 20: 4966 
  Number of stims on node 12: 4967 
  Number of stims on node 14: 4967 
  Number of stims on node 45: 4967 
  Number of stims on node 61: 4957 
  Number of stims on node 50: 4957 
  Number of stims on node 6: 4967 
  Number of stims on node 40: 4967 
  Number of stims on node 16: 4967 
  Number of stims on node 0: 4967 
  Number of stims on node 33: 4966 
  Number of stims on node 60: 4957 
  Number of stims on node 24: 4966 
  Number of stims on node 35: 4966 
  Number of stims on node 25: 4966 
  Number of stims on node 58: 4957 
  Number of stims on node 47: 4967 
  Number of stims on node 46: 4967 
  Number of stims on node 42: 4967 
  Number of stims on node 28: 4966 
  Number of stims on node 34: 4966 
  Number of stims on node 9: 4967 
  Number of stims on node 26: 4966 
  Number of stims on node 57: 4957 
  Number of stims on node 62: 4957 
  Number of stims on node 32: 4966 
  Number of stims on node 37: 4967 
  Number of stims on node 43: 4967 
  Number of stims on node 21: 4966 
  Number of stims on node 23: 4966 
  Number of stims on node 41: 4967 
  Number of stims on node 49: 4967 
  Number of stims on node 30: 4966 
  Number of stims on node 51: 4957 
  Number of stims on node 48: 4967 
  Number of stims on node 63: 4957 
  Number of stims on node 19: 4967 
  Number of stims on node 15: 4967 
  Number of stims on node 4: 4967 
  Number of stims on node 22: 4966 
  Number of stims on node 52: 4957 
  Number of stims on node 5: 4967 
  Number of stims on node 44: 4967 
  Number of stims on node 36: 4966 
  Number of stims on node 31: 4966 
  Number of stims on node 18: 4967 
  Number of stims on node 53: 4957 
  Number of stims on node 17: 4967 
  Number of stims on node 2: 4967 
  Number of stims on node 3: 4967 
  Number of stims on node 54: 4957 
  Number of stims on node 39: 4967 
  Number of stims on node 55: 4957 
  Number of stims on node 59: 4957 
  Number of stims on node 13: 4967 
  Number of stims on node 7: 4967 
  Number of stims on node 1: 4967 
  Number of stims on node 10: 4967 
  Number of stims on node 29: 4966 
  Number of stims on node 8: 4967 
  Done; cell stims creation time = 12.13 s.
  Number of stims on node 38: 4967 
Recording 13 traces of 1 types on node 6
Recording 14 traces of 1 types on node 12
Recording 20 traces of 1 types on node 54
Recording 11 traces of 1 types on node 20
Recording 18 traces of 1 types on node 62
Recording 19 traces of 1 types on node 19
Recording 12 traces of 1 types on node 47
Recording 27 traces of 1 types on node 60
Recording 6 traces of 1 types on node 28
Recording 21 traces of 1 types on node 0
Recording 16 traces of 1 types on node 29
Recording 16 traces of 1 types on node 41
Recording 13 traces of 1 types on node 37
Recording 12 traces of 1 types on node 33
Recording 16 traces of 1 types on node 24
Recording 15 traces of 1 types on node 36
Recording 14 traces of 1 types on node 59
Recording 18 traces of 1 types on node 22
Recording 12 traces of 1 types on node 9
Recording 16 traces of 1 types on node 53
Recording 18 traces of 1 types on node 57
Recording 14 traces of 1 types on node 49
Recording 13 traces of 1 types on node 31
Recording 13 traces of 1 types on node 56
Recording 15 traces of 1 types on node 14
Recording 16 traces of 1 types on node 43
Recording 12 traces of 1 types on node 13
Recording 13 traces of 1 types on node 23
Recording 17 traces of 1 types on node 50
Recording 14 traces of 1 types on node 2
Recording 15 traces of 1 types on node 35
Recording 15 traces of 1 types on node 38
Recording 21 traces of 1 types on node 45
Recording 20 traces of 1 types on node 52
Recording 15 traces of 1 types on node 26
Recording 17 traces of 1 types on node 48
Recording 9 traces of 1 types on node 58
Recording 17 traces of 1 types on node 18
Recording 15 traces of 1 types on node 55
Recording 12 traces of 1 types on node 5
Recording 11 traces of 1 types on node 17
Recording 16 traces of 1 types on node 61
Recording 19 traces of 1 types on node 4
Recording 21 traces of 1 types on node 27
Recording 12 traces of 1 types on node 39
Recording 12 traces of 1 types on node 30
Recording 14 traces of 1 types on node 63
Recording 20 traces of 1 types on node 51
Recording 13 traces of 1 types on node 15
Recording 12 traces of 1 types on node 3
Recording 17 traces of 1 types on node 16
Recording 17 traces of 1 types on node 11
Recording 13 traces of 1 types on node 40
Recording 11 traces of 1 types on node 25
Recording 15 traces of 1 types on node 8
Recording 14 traces of 1 types on node 1
Recording 13 traces of 1 types on node 21
Recording 14 traces of 1 types on node 42
Recording 12 traces of 1 types on node 34
Recording 12 traces of 1 types on node 32
Recording 18 traces of 1 types on node 10
Recording 14 traces of 1 types on node 7
Recording 16 traces of 1 types on node 44
Recording 13 traces of 1 types on node 46
0.0s

Running simulation for 5000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
  Done; run time = 97327.65 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 15.49 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 1080761 (5.60 Hz)
  Simulated time: 5.0 s; 64 workers
  Run time: 97327.65 s
   L1_DAC_bNA : 0.032 Hz
   L1_DAC_cNA : 0.067 Hz
   L1_DLAC_cNA : 0.067 Hz
   L1_HAC_bNA : 0.074 Hz
   L1_HAC_cIR : 0.060 Hz
   L1_HAC_cNA : 0.068 Hz
   L1_NGC-DA_bNA : 0.150 Hz
   L1_NGC-DA_cAC : 0.100 Hz
   L1_NGC-DA_cNA : 0.146 Hz
   L1_NGC-DA_cST : 0.100 Hz
   L1_NGC-SA_cNA : 0.146 Hz
   L1_SLAC_bNA : 0.243 Hz
   L1_SLAC_cAC : 0.100 Hz
   L1_SLAC_cNA : 0.084 Hz
   L23_BP_bAC : 2.867 Hz
   L23_BP_bIR : 3.100 Hz
   L23_BP_bNA : 4.857 Hz
   L23_BP_cAC : 4.429 Hz
   L23_BP_cNA : 7.700 Hz
   L23_BP_dST : 2.667 Hz
   L23_BTC_bAC : 0.373 Hz
   L23_BTC_bIR : 0.229 Hz
   L23_BTC_bNA : 0.878 Hz
   L23_BTC_cAC : 0.259 Hz
   L23_BTC_cNA : 0.711 Hz
   L23_ChC_cAC : 1.991 Hz
   L23_ChC_cNA : 1.896 Hz
   L23_ChC_dNA : 0.667 Hz
   L23_DBC_bAC : 1.850 Hz
   L23_DBC_bIR : 0.575 Hz
   L23_DBC_bNA : 2.486 Hz
   L23_DBC_cAC : 2.233 Hz
   L23_LBC_bAC : 0.337 Hz
   L23_LBC_bNA : 6.919 Hz
   L23_LBC_cAC : 1.859 Hz
   L23_LBC_cNA : 2.889 Hz
   L23_LBC_cST : 3.800 Hz
   L23_LBC_dNA : 5.238 Hz
   L23_MC_bAC : 0.000 Hz
   L23_MC_bNA : 0.140 Hz
   L23_MC_cAC : 0.087 Hz
   L23_MC_cNA : 0.158 Hz
   L23_MC_dNA : 0.040 Hz
   L23_NBC_bAC : 0.229 Hz
   L23_NBC_bNA : 2.967 Hz
   L23_NBC_cAC : 0.788 Hz
   L23_NBC_cIR : 0.100 Hz
   L23_NBC_cNA : 0.735 Hz
   L23_NBC_dNA : 1.371 Hz
   L23_NGC_bNA : 1.480 Hz
   L23_NGC_cAC : 0.520 Hz
   L23_NGC_cNA : 0.673 Hz
   L23_NGC_cST : 0.200 Hz
   L23_PC_cAD : 0.619 Hz
   L23_SBC_bNA : 5.440 Hz
   L23_SBC_cAC : 5.137 Hz
   L23_SBC_dNA : 3.739 Hz
   L4_BP_bAC : 8.800 Hz
   L4_BP_bIR : 6.400 Hz
   L4_BP_bNA : 7.000 Hz
   L4_BP_cAC : 5.000 Hz
   L4_BP_cNA : 16.000 Hz
   L4_BP_dST : 0.200 Hz
   L4_BTC_bAC : 6.100 Hz
   L4_BTC_bIR : 1.000 Hz
   L4_BTC_bST : 4.600 Hz
   L4_BTC_cAC : 6.822 Hz
   L4_BTC_cNA : 11.733 Hz
   L4_BTC_dNA : 3.700 Hz
   L4_ChC_cAC : 20.067 Hz
   L4_ChC_cNA : 17.800 Hz
   L4_ChC_dNA : 3.800 Hz
   L4_DBC_bAC : 7.600 Hz
   L4_DBC_bIR : 0.492 Hz
   L4_DBC_bNA : 4.850 Hz
   L4_DBC_bST : 0.350 Hz
   L4_DBC_cAC : 3.700 Hz
   L4_DBC_cIR : 0.886 Hz
   L4_DBC_cNA : 6.700 Hz
   L4_LBC_cAC : 15.245 Hz
   L4_LBC_cNA : 23.086 Hz
   L4_LBC_cST : 17.019 Hz
   L4_LBC_dNA : 26.117 Hz
   L4_LBC_dST : 20.200 Hz
   L4_MC_bAC : 0.109 Hz
   L4_MC_bNA : 0.100 Hz
   L4_MC_cAC : 0.375 Hz
   L4_MC_cNA : 0.189 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 15.120 Hz
   L4_NBC_cIR : 9.480 Hz
   L4_NBC_cNA : 27.422 Hz
   L4_NBC_dNA : 22.161 Hz
   L4_NGC_bNA : 7.000 Hz
   L4_NGC_cAC : 8.200 Hz
   L4_NGC_cNA : 6.133 Hz
   L4_NGC_cST : 1.600 Hz
   L4_PC_cAD : 3.729 Hz
   L4_SBC_bNA : 26.981 Hz
   L4_SBC_cAC : 16.327 Hz
   L4_SBC_dNA : 25.588 Hz
   L4_SP_cAD : 4.822 Hz
   L4_SS_cAD : 5.325 Hz
   L5_BP_bAC : 10.333 Hz
   L5_BP_bIR : 4.000 Hz
   L5_BP_bNA : 22.978 Hz
   L5_BP_cAC : 16.533 Hz
   L5_BP_cNA : 35.480 Hz
   L5_BP_dST : 4.000 Hz
   L5_BTC_bAC : 10.769 Hz
   L5_BTC_cAC : 13.444 Hz
   L5_BTC_cNA : 22.985 Hz
   L5_ChC_cAC : 27.371 Hz
   L5_ChC_cNA : 39.543 Hz
   L5_ChC_dNA : 35.120 Hz
   L5_DBC_bAC : 6.556 Hz
   L5_DBC_bIR : 1.324 Hz
   L5_DBC_bNA : 9.222 Hz
   L5_DBC_bST : 4.022 Hz
   L5_DBC_cAC : 9.778 Hz
   L5_DBC_cIR : 2.741 Hz
   L5_DBC_cNA : 16.333 Hz
   L5_LBC_bAC : 11.267 Hz
   L5_LBC_cAC : 20.760 Hz
   L5_LBC_cIR : 7.831 Hz
   L5_LBC_cNA : 43.351 Hz
   L5_LBC_cST : 32.962 Hz
   L5_LBC_dNA : 40.162 Hz
   L5_LBC_dST : 28.078 Hz
   L5_MC_bAC : 2.634 Hz
   L5_MC_bIR : 0.859 Hz
   L5_MC_bST : 1.075 Hz
   L5_MC_cAC : 4.973 Hz
   L5_MC_cNA : 3.562 Hz
   L5_MC_cST : 0.537 Hz
   L5_MC_dNA : 0.863 Hz
   L5_NBC_bAC : 8.614 Hz
   L5_NBC_bIR : 4.743 Hz
   L5_NBC_bST : 25.593 Hz
   L5_NBC_cAC : 25.050 Hz
   L5_NBC_cIR : 14.714 Hz
   L5_NBC_cNA : 37.949 Hz
   L5_NBC_cST : 26.940 Hz
   L5_NBC_dST : 30.646 Hz
   L5_NGC_bNA : 0.200 Hz
   L5_NGC_cAC : 15.600 Hz
   L5_NGC_cNA : 29.840 Hz
   L5_NGC_cST : 4.800 Hz
   L5_SBC_bNA : 25.533 Hz
   L5_SBC_cAC : 16.111 Hz
   L5_SBC_dNA : 48.800 Hz
   L5_STPC_cAD : 7.649 Hz
   L5_TTPC1_cAD : 7.826 Hz
   L5_TTPC2_cAD : 8.229 Hz
   L5_UTPC_cAD : 10.763 Hz
   L6_BPC_cAD : 5.014 Hz
   L6_BP_bAC : 8.700 Hz
   L6_BP_bIR : 2.500 Hz
   L6_BP_bNA : 17.116 Hz
   L6_BP_cAC : 14.389 Hz
   L6_BP_cNA : 25.520 Hz
   L6_BP_dST : 1.167 Hz
   L6_BTC_bAC : 6.940 Hz
   L6_BTC_cAC : 12.706 Hz
   L6_BTC_cNA : 23.320 Hz
   L6_ChC_cAC : 14.600 Hz
   L6_ChC_cNA : 50.933 Hz
   L6_ChC_dNA : 28.600 Hz
   L6_DBC_bAC : 8.467 Hz
   L6_DBC_bIR : 1.820 Hz
   L6_DBC_bNA : 9.000 Hz
   L6_DBC_bST : 3.667 Hz
   L6_DBC_cAC : 10.933 Hz
   L6_DBC_cIR : 3.967 Hz
   L6_DBC_cNA : 8.933 Hz
   L6_IPC_cAD : 4.691 Hz
   L6_LBC_bAC : 7.531 Hz
   L6_LBC_bIR : 4.287 Hz
   L6_LBC_bNA : 56.056 Hz
   L6_LBC_bST : 29.910 Hz
   L6_LBC_cNA : 45.119 Hz
   L6_LBC_cST : 24.926 Hz
   L6_MC_bAC : 0.854 Hz
   L6_MC_bIR : 0.171 Hz
   L6_MC_bNA : 2.029 Hz
   L6_MC_bST : 0.414 Hz
   L6_MC_cAC : 3.109 Hz
   L6_MC_cIR : 0.171 Hz
   L6_MC_cNA : 2.271 Hz
   L6_NBC_bAC : 8.143 Hz
   L6_NBC_bIR : 5.257 Hz
   L6_NBC_bST : 34.585 Hz
   L6_NBC_cAC : 15.087 Hz
   L6_NBC_cIR : 7.829 Hz
   L6_NBC_cNA : 32.805 Hz
   L6_NBC_cST : 28.287 Hz
   L6_NBC_dST : 32.486 Hz
   L6_NGC_bNA : 17.600 Hz
   L6_NGC_cAC : 13.700 Hz
   L6_NGC_cNA : 26.345 Hz
   L6_NGC_cST : 3.100 Hz
   L6_SBC_bNA : 33.725 Hz
   L6_SBC_cAC : 24.742 Hz
   L6_SBC_dNA : 29.105 Hz
   L6_TPC_L1_cAD : 5.010 Hz
   L6_TPC_L4_cAD : 5.913 Hz
   L6_UTPC_cAD : 6.324 Hz
   ss_RTN_o : 11.290 Hz
   ss_RTN_m : 11.625 Hz
   ss_RTN_i : 10.650 Hz
   VPL_sTC : 2.878 Hz
   VPM_sTC : 3.140 Hz
   POm_sTC_s1 : 4.042 Hz
Saving output as ../data/v6_batch3/v6_batch3_0_0.json  ... 
Finished saving!
  Done; saving time = 83.27 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 3135.51 s

Total time = 120111.76 s

End time:  2021-12-11 05:21:48.885329
