numprocs=80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v5_batch0/v5_batch0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py

Start time:  2021-07-03 01:06:48.847445
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py
Importing netParams from ../data/v5_batch0/v5_batch0_netParams.py

Creating network of 61 cell populations on 80 hosts...
  Number of cells on node 53: 482 
  Number of cells on node 47: 483 
  Number of cells on node 60: 482 
  Number of cells on node 61: 482 
  Number of cells on node 1: 483 
  Number of cells on node 44: 483 
  Number of cells on node 58: 482 
  Number of cells on node 40: 483 
  Number of cells on node 65: 482 
  Number of cells on node 36: 483 
  Number of cells on node 57: 482 
  Number of cells on node 9: 483 
  Number of cells on node 8: 483 
  Number of cells on node 28: 483 
  Number of cells on node 34: 483 
  Number of cells on node 10: 483 
  Number of cells on node 38: 483 
  Number of cells on node 50: 483 
  Number of cells on node 37: 483 
  Number of cells on node 51: 483 
  Number of cells on node 69: 482 
  Number of cells on node 67: 482 
  Number of cells on node 76: 482 
  Number of cells on node 16: 483 
  Number of cells on node 18: 483 
  Number of cells on node 71: 482 
  Number of cells on node 0: 483 
  Done; cell creation time = 33.46 s.
Making connections...
  Number of cells on node 79: 482 
  Number of cells on node 17: 483 
  Number of cells on node 23: 483 
  Number of cells on node 45: 483 
  Number of cells on node 72: 482 
  Number of cells on node 5: 483 
  Number of cells on node 14: 483 
  Number of cells on node 42: 483 
  Number of cells on node 15: 483 
  Number of cells on node 46: 483 
  Number of cells on node 48: 483 
  Number of cells on node 75: 482 
  Number of cells on node 7: 483 
  Number of cells on node 49: 483 
  Number of cells on node 13: 483 
  Number of cells on node 35: 483 
  Number of cells on node 74: 482 
  Number of cells on node 63: 482 
  Number of cells on node 26: 483 
  Number of cells on node 70: 482 
  Number of cells on node 32: 483 
  Number of cells on node 2: 483 
  Number of cells on node 20: 483 
  Number of cells on node 29: 483 
  Number of cells on node 11: 483 
  Number of cells on node 64: 482 
  Number of cells on node 25: 483 
  Number of cells on node 68: 482 
  Number of cells on node 6: 483 
  Number of cells on node 78: 482 
  Number of cells on node 31: 483 
  Number of cells on node 59: 482 
  Number of cells on node 54: 482 
  Number of cells on node 33: 483 
  Number of cells on node 52: 482 
  Number of cells on node 55: 482 
  Number of cells on node 24: 483 
  Number of cells on node 27: 483 
  Number of cells on node 3: 483 
  Number of cells on node 12: 483 
  Number of cells on node 21: 483 
  Number of cells on node 77: 482 
  Number of cells on node 62: 482 
  Number of cells on node 66: 482 
  Number of cells on node 19: 483 
  Number of cells on node 30: 483 
  Number of cells on node 4: 483 
  Number of cells on node 39: 483 
  Number of cells on node 43: 483 
  Number of cells on node 56: 482 
  Number of cells on node 41: 483 
  Number of cells on node 73: 482 
  Number of cells on node 22: 483 
  Number of connections on node 22: 0 
  Number of connections on node 53: 0 
  Number of connections on node 47: 0 
  Number of connections on node 60: 0 
  Number of connections on node 61: 0 
  Number of connections on node 1: 0 
  Number of connections on node 44: 0 
  Number of connections on node 58: 0 
  Number of connections on node 40: 0 
  Number of connections on node 65: 0 
  Number of connections on node 36: 0 
  Number of connections on node 57: 0 
  Number of connections on node 9: 0 
  Number of connections on node 8: 0 
  Number of connections on node 28: 0 
  Number of connections on node 34: 0 
  Number of connections on node 10: 0 
  Number of connections on node 38: 0 
  Number of connections on node 50: 0 
  Number of connections on node 37: 0 
  Number of connections on node 51: 0 
  Number of connections on node 69: 0 
  Number of connections on node 67: 0 
  Number of connections on node 76: 0 
  Number of connections on node 16: 0 
  Number of connections on node 18: 0 
  Number of connections on node 71: 0 
  Number of connections on node 0: 0 
  Done; cell connection time = 1.60 s.
  Number of connections on node 79: 0 
  Number of connections on node 17: 0 
  Number of connections on node 23: 0 
  Number of connections on node 45: 0 
  Number of connections on node 72: 0 
  Number of connections on node 5: 0 
  Number of connections on node 14: 0 
  Number of connections on node 42: 0 
  Number of connections on node 15: 0 
  Number of connections on node 46: 0 
  Number of connections on node 48: 0 
  Number of connections on node 75: 0 
  Number of connections on node 7: 0 
  Number of connections on node 49: 0 
  Number of connections on node 13: 0 
  Number of connections on node 35: 0 
  Number of connections on node 74: 0 
  Number of connections on node 63: 0 
  Number of connections on node 26: 0 
  Number of connections on node 70: 0 
  Number of connections on node 32: 0 
  Number of connections on node 2: 0 
  Number of connections on node 20: 0 
  Number of connections on node 29: 0 
  Number of connections on node 11: 0 
  Number of connections on node 64: 0 
  Number of connections on node 25: 0 
  Number of connections on node 68: 0 
  Number of connections on node 6: 0 
  Number of connections on node 78: 0 
  Number of connections on node 31: 0 
  Number of connections on node 59: 0 
  Number of connections on node 54: 0 
  Number of connections on node 33: 0 
  Number of connections on node 52: 0 
  Number of connections on node 55: 0 
  Number of connections on node 24: 0 
  Number of connections on node 27: 0 
  Number of connections on node 3: 0 
  Number of connections on node 12: 0 
  Number of connections on node 21: 0 
  Number of connections on node 77: 0 
  Number of connections on node 62: 0 
  Number of connections on node 66: 0 
  Number of connections on node 19: 0 
  Number of connections on node 30: 0 
  Number of connections on node 4: 0 
  Number of connections on node 39: 0 
  Number of connections on node 43: 0 
  Number of connections on node 56: 0 
  Number of connections on node 41: 0 
  Number of connections on node 73: 0 
Adding stims...
  Number of stims on node 69: 3910 
  Number of stims on node 57: 3920 
  Number of stims on node 27: 3920 
  Number of stims on node 22: 3920 
  Number of stims on node 67: 3910 
  Number of stims on node 32: 3920 
  Number of stims on node 40: 3920 
  Number of stims on node 64: 3920 
  Number of stims on node 17: 3920 
  Number of stims on node 30: 3920 
  Number of stims on node 15: 3920 
  Number of stims on node 38: 3920 
  Number of stims on node 12: 3920 
  Number of stims on node 36: 3920 
  Number of stims on node 29: 3920 
  Number of stims on node 59: 3920 
  Number of stims on node 77: 3910 
  Number of stims on node 9: 3920 
  Number of stims on node 66: 3910 
  Number of stims on node 63: 3920 
  Number of stims on node 7: 3920 
  Number of stims on node 68: 3910 
  Number of stims on node 55: 3920 
  Number of stims on node 20: 3920 
  Number of stims on node 39: 3920 
  Number of stims on node 71: 3910 
  Number of stims on node 14: 3920 
  Number of stims on node 23: 3920 
  Number of stims on node 41: 3920 
  Number of stims on node 65: 3920 
  Number of stims on node 8: 3920 
  Number of stims on node 62: 3920 
  Number of stims on node 44: 3920 
  Number of stims on node 18: 3920 
  Number of stims on node 42: 3920 
  Number of stims on node 75: 3910 
  Number of stims on node 35: 3920 
  Number of stims on node 76: 3910 
  Number of stims on node 78: 3910 
  Number of stims on node 2: 3920 
  Number of stims on node 47: 3920 
  Number of stims on node 61: 3920 
  Number of stims on node 58: 3920 
  Number of stims on node 0: 3920 
  Number of stims on node 16: 3920 
  Number of stims on node 72: 3910 
  Number of stims on node 28: 3920 
  Number of stims on node 10: 3920 
  Number of stims on node 37: 3920 
  Number of stims on node 31: 3920 
  Number of stims on node 50: 3920 
  Number of stims on node 79: 3910 
  Number of stims on node 3: 3920 
  Number of stims on node 25: 3920 
  Number of stims on node 46: 3920 
  Number of stims on node 11: 3920 
  Number of stims on node 1: 3920 
  Number of stims on node 43: 3920 
  Number of stims on node 60: 3920 
  Number of stims on node 34: 3920 
  Number of stims on node 26: 3920 
  Number of stims on node 74: 3910 
  Number of stims on node 49: 3920 
  Number of stims on node 33: 3920 
  Number of stims on node 73: 3910 
  Number of stims on node 48: 3920 
  Number of stims on node 21: 3920 
  Number of stims on node 52: 3920 
  Number of stims on node 56: 3920 
  Number of stims on node 70: 3910 
  Number of stims on node 24: 3920 
  Number of stims on node 4: 3920 
  Number of stims on node 51: 3920 
  Number of stims on node 13: 3920 
  Number of stims on node 45: 3920 
  Number of stims on node 19: 3920 
  Number of stims on node 6: 3920 
  Number of stims on node 54: 3920 
  Number of stims on node 5: 3920 
  Done; cell stims creation time = 11.85 s.
  Number of stims on node 53: 3920 
Recording 14 traces of 1 types on node 23
Recording 14 traces of 1 types on node 27
Recording 9 traces of 1 types on node 77
Recording 10 traces of 1 types on node 59
Recording 17 traces of 1 types on node 66
Recording 16 traces of 1 types on node 67
Recording 16 traces of 1 types on node 57
Recording 11 traces of 1 types on node 36
Recording 15 traces of 1 types on node 14
Recording 9 traces of 1 types on node 63
Recording 11 traces of 1 types on node 15
Recording 13 traces of 1 types on node 12
Recording 14 traces of 1 types on node 20
Recording 12 traces of 1 types on node 44
Recording 14 traces of 1 types on node 18
Recording 16 traces of 1 types on node 55
Recording 8 traces of 1 types on node 7
Recording 9 traces of 1 types on node 17
Recording 17 traces of 1 types on node 64
Recording 15 traces of 1 types on node 40
Recording 15 traces of 1 types on node 38
Recording 15 traces of 1 types on node 52
Recording 15 traces of 1 types on node 62
Recording 12 traces of 1 types on node 68
Recording 10 traces of 1 types on node 10
Recording 17 traces of 1 types on node 22
Recording 7 traces of 1 types on node 41
Recording 9 traces of 1 types on node 8
Recording 11 traces of 1 types on node 30
Recording 15 traces of 1 types on node 29
Recording 11 traces of 1 types on node 9
Recording 11 traces of 1 types on node 32
Recording 12 traces of 1 types on node 39
Recording 14 traces of 1 types on node 0
Recording 4 traces of 1 types on node 79
Recording 16 traces of 1 types on node 60
Recording 17 traces of 1 types on node 42
Recording 14 traces of 1 types on node 58
Recording 8 traces of 1 types on node 71
Recording 13 traces of 1 types on node 25
Recording 15 traces of 1 types on node 76
Recording 11 traces of 1 types on node 61
Recording 15 traces of 1 types on node 28
Recording 10 traces of 1 types on node 75
Recording 13 traces of 1 types on node 78
Recording 19 traces of 1 types on node 31
Recording 11 traces of 1 types on node 21
Recording 8 traces of 1 types on node 19
Recording 10 traces of 1 types on node 43
Recording 12 traces of 1 types on node 50
Recording 11 traces of 1 types on node 34
Recording 8 traces of 1 types on node 69
Recording 18 traces of 1 types on node 72
Recording 15 traces of 1 types on node 35
Recording 10 traces of 1 types on node 1
Recording 9 traces of 1 types on node 24
Recording 14 traces of 1 types on node 4
Recording 17 traces of 1 types on node 49
Recording 12 traces of 1 types on node 2
Recording 10 traces of 1 types on node 13
Recording 7 traces of 1 types on node 47
Recording 14 traces of 1 types on node 51
Recording 12 traces of 1 types on node 56
Recording 16 traces of 1 types on node 54
Recording 12 traces of 1 types on node 74
Recording 6 traces of 1 types on node 65
Recording 16 traces of 1 types on node 5
Recording 12 traces of 1 types on node 33
Recording 16 traces of 1 types on node 46
Recording 13 traces of 1 types on node 3
Recording 14 traces of 1 types on node 48
Recording 18 traces of 1 types on node 11
Recording 10 traces of 1 types on node 53
Recording 16 traces of 1 types on node 26
Recording 13 traces of 1 types on node 73
Recording 16 traces of 1 types on node 70
Recording 10 traces of 1 types on node 6
Recording 17 traces of 1 types on node 16
Recording 10 traces of 1 types on node 37
Recording 15 traces of 1 types on node 45
0.0s

Running simulation for 500.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
  Done; run time = 4121.00 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.68 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 41894 (2.17 Hz)
  Simulated time: 0.5 s; 80 workers
  Run time: 4121.00 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.000 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.000 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 0.075 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.022 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.270 Hz
   L23_SBC : 0.265 Hz
   L4_BP : 1.250 Hz
   L4_BTC : 0.900 Hz
   L4_ChC : 4.750 Hz
   L4_DBC : 0.050 Hz
   L4_LBC : 4.984 Hz
   L4_MC : 0.000 Hz
   L4_NBC : 6.938 Hz
   L4_NGC : 0.333 Hz
   L4_PC : 1.207 Hz
   L4_SBC : 9.167 Hz
   L4_SP : 2.158 Hz
   L4_SS : 3.064 Hz
   L5_BP : 7.294 Hz
   L5_BTC : 2.947 Hz
   L5_ChC : 14.842 Hz
   L5_DBC : 0.438 Hz
   L5_LBC : 13.162 Hz
   L5_MC : 0.025 Hz
   L5_NBC : 13.274 Hz
   L5_NGC : 11.750 Hz
   L5_SBC : 12.080 Hz
   L5_STPC : 3.119 Hz
   L5_TTPC1 : 2.281 Hz
   L5_TTPC2 : 2.161 Hz
   L5_UTPC : 3.971 Hz
   L6_BPC : 2.152 Hz
   L6_BP : 5.657 Hz
   L6_BTC : 6.296 Hz
   L6_ChC : 20.625 Hz
   L6_DBC : 2.581 Hz
   L6_IPC : 3.204 Hz
   L6_LBC : 12.467 Hz
   L6_MC : 0.024 Hz
   L6_NBC : 15.424 Hz
   L6_NGC : 9.529 Hz
   L6_SBC : 27.075 Hz
   L6_TPC_L1 : 2.667 Hz
   L6_TPC_L4 : 3.429 Hz
   L6_UTPC : 3.960 Hz
   ss_RTN_o : 0.000 Hz
   ss_RTN_m : 0.000 Hz
   ss_RTN_i : 0.000 Hz
   VPL_sTC : 2.000 Hz
   VPM_sTC : 2.000 Hz
   POm_sTC_s1 : 2.000 Hz
Saving output as ../data/v5_batch0/v5_batch0_0.json  ... 
Finished saving!
  Done; saving time = 9.57 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 260.01 s

Total time = 4483.34 s

End time:  2021-07-03 02:21:32.183530
