numprocs=40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py

Start time:  2021-11-21 03:41:39.900769

Creating network of 213 cell populations on 40 hosts...
  Number of cells on node 9: 966 
  Number of cells on node 31: 965 
  Number of cells on node 22: 965 
  Number of cells on node 8: 966 
  Number of cells on node 34: 965 
  Number of cells on node 12: 965 
  Number of cells on node 19: 965 
  Number of cells on node 38: 965 
  Number of cells on node 28: 965 
  Number of cells on node 33: 965 
  Number of cells on node 36: 965 
  Number of cells on node 21: 965 
  Number of cells on node 39: 965 
  Number of cells on node 3: 966 
  Number of cells on node 23: 965 
  Number of cells on node 4: 966 
  Number of cells on node 17: 965 
  Number of cells on node 2: 966 
  Number of cells on node 35: 965 
  Number of cells on node 18: 965 
  Number of cells on node 27: 965 
  Number of cells on node 13: 965 
  Number of cells on node 26: 965 
  Number of cells on node 29: 965 
  Number of cells on node 20: 965 
  Number of cells on node 30: 965 
  Number of cells on node 0: 966 
  Done; cell creation time = 38.73 s.
Making connections...
  Number of cells on node 10: 966 
  Number of cells on node 1: 966 
  Number of cells on node 32: 965 
  Number of cells on node 24: 965 
  Number of cells on node 15: 965 
  Number of cells on node 37: 965 
  Number of cells on node 11: 966 
  Number of cells on node 14: 965 
  Number of cells on node 25: 965 
  Number of cells on node 16: 965 
  Number of cells on node 6: 966 
  Number of cells on node 5: 966 
  Number of cells on node 7: 966 
  Number of connections on node 3: 200612 
  Number of synaptic contacts on node 3: 943740 
  Number of connections on node 17: 203887 
  Number of synaptic contacts on node 17: 963666 
  Number of connections on node 15: 201925 
  Number of synaptic contacts on node 15: 949245 
  Number of connections on node 20: 201400 
  Number of synaptic contacts on node 20: 948251 
  Number of connections on node 31: 199363 
  Number of synaptic contacts on node 31: 942013 
  Number of connections on node 9: 201819 
  Number of synaptic contacts on node 9: 952469 
  Number of connections on node 36: 205325 
  Number of synaptic contacts on node 36: 970665 
  Number of connections on node 34: 202536 
  Number of synaptic contacts on node 34: 952780 
  Number of connections on node 37: 206185 
  Number of synaptic contacts on node 37: 975369 
  Number of connections on node 11: 204336 
  Number of synaptic contacts on node 11: 966104 
  Number of connections on node 30: 202606 
  Number of synaptic contacts on node 30: 957014 
  Number of connections on node 2: 202410 
  Number of synaptic contacts on node 2: 951645 
  Number of connections on node 7: 203641 
  Number of synaptic contacts on node 7: 960320 
  Number of connections on node 21: 203554 
  Number of synaptic contacts on node 21: 956469 
  Number of connections on node 32: 200282 
  Number of synaptic contacts on node 32: 942765 
  Number of connections on node 8: 202043 
  Number of synaptic contacts on node 8: 953715 
  Number of connections on node 26: 200294 
  Number of synaptic contacts on node 26: 941561 
  Number of connections on node 39: 201863 
  Number of synaptic contacts on node 39: 947946 
  Number of connections on node 16: 202711 
  Number of synaptic contacts on node 16: 955241 
  Number of connections on node 38: 201124 
  Number of synaptic contacts on node 38: 946633 
  Number of connections on node 27: 203773 
  Number of synaptic contacts on node 27: 958317 
  Number of connections on node 29: 201768 
  Number of synaptic contacts on node 29: 949675 
  Number of connections on node 19: 203542 
  Number of synaptic contacts on node 19: 959061 
  Number of connections on node 6: 199909 
  Number of synaptic contacts on node 6: 944911 
  Number of connections on node 35: 202508 
  Number of synaptic contacts on node 35: 952797 
  Number of connections on node 4: 203695 
  Number of synaptic contacts on node 4: 962111 
  Number of connections on node 0: 204058 
  Number of synaptic contacts on node 0: 964479 
  Number of connections on node 14: 201956 
  Number of synaptic contacts on node 14: 951947 
  Number of connections on node 22: 199395 
  Number of synaptic contacts on node 22: 938712 
  Number of connections on node 25: 201178 
  Number of synaptic contacts on node 25: 946158 
  Number of connections on node 33: 203334 
  Number of synaptic contacts on node 33: 960683 
  Number of connections on node 23: 204240 
  Number of synaptic contacts on node 23: 959710 
  Number of connections on node 1: 202989 
  Number of synaptic contacts on node 1: 959282 
  Number of connections on node 10: 201118 
  Number of synaptic contacts on node 10: 950122 
  Number of connections on node 28: 203493 
  Number of synaptic contacts on node 28: 956706 
  Number of connections on node 12: 202490 
  Number of synaptic contacts on node 12: 952131 
  Number of connections on node 5: 200758 
  Number of synaptic contacts on node 5: 948157 
  Number of connections on node 24: 204387 
  Number of synaptic contacts on node 24: 963545 
  Number of connections on node 13: 202449 
  Number of synaptic contacts on node 13: 956122 
  Done; cell connection time = 16015.73 s.
  Number of connections on node 18: 203154 
  Number of synaptic contacts on node 18: 951837 
Adding stims...
  Number of stims on node 39: 7937 
  Number of stims on node 7: 7947 
  Number of stims on node 37: 7937 
  Number of stims on node 5: 7947 
  Number of stims on node 1: 7947 
  Number of stims on node 0: 7947 
  Number of stims on node 24: 7947 
  Number of stims on node 34: 7937 
  Number of stims on node 3: 7947 
  Number of stims on node 26: 7937 
  Number of stims on node 20: 7946 
  Number of stims on node 10: 7947 
  Number of stims on node 23: 7947 
  Number of stims on node 36: 7937 
  Number of stims on node 8: 7947 
  Number of stims on node 25: 7947 
  Number of stims on node 31: 7937 
  Number of stims on node 32: 7937 
  Number of stims on node 4: 7947 
  Number of stims on node 12: 7946 
  Number of stims on node 38: 7937 
  Number of stims on node 18: 7946 
  Number of stims on node 27: 7937 
  Number of stims on node 33: 7937 
  Number of stims on node 21: 7947 
  Number of stims on node 28: 7937 
  Number of stims on node 35: 7937 
  Number of stims on node 9: 7947 
  Number of stims on node 2: 7947 
  Number of stims on node 17: 7946 
  Number of stims on node 30: 7937 
  Number of stims on node 14: 7946 
  Number of stims on node 11: 7947 
  Number of stims on node 15: 7946 
  Number of stims on node 19: 7946 
  Number of stims on node 16: 7946 
  Number of stims on node 13: 7946 
  Number of stims on node 22: 7947 
  Number of stims on node 6: 7947 
  Number of stims on node 29: 7937 
  Done; cell stims creation time = 9.14 s.
Recording 20 traces of 1 types on node 7
Recording 20 traces of 1 types on node 39
Recording 17 traces of 1 types on node 1
Recording 30 traces of 1 types on node 5
Recording 22 traces of 1 types on node 23
Recording 23 traces of 1 types on node 0
Recording 29 traces of 1 types on node 4
Recording 20 traces of 1 types on node 18
Recording 26 traces of 1 types on node 16
Recording 21 traces of 1 types on node 37
Recording 26 traces of 1 types on node 2
Recording 21 traces of 1 types on node 21
Recording 21 traces of 1 types on node 25
Recording 21 traces of 1 types on node 19
Recording 19 traces of 1 types on node 9
Recording 29 traces of 1 types on node 11
Recording 26 traces of 1 types on node 24
Recording 29 traces of 1 types on node 33
Recording 18 traces of 1 types on node 31
Recording 27 traces of 1 types on node 35
Recording 24 traces of 1 types on node 38
Recording 26 traces of 1 types on node 8
Recording 22 traces of 1 types on node 17
Recording 25 traces of 1 types on node 6
Recording 26 traces of 1 types on node 15
Recording 31 traces of 1 types on node 27
Recording 22 traces of 1 types on node 34
Recording 26 traces of 1 types on node 3
Recording 23 traces of 1 types on node 30
Recording 23 traces of 1 types on node 32
Recording 25 traces of 1 types on node 29
Recording 23 traces of 1 types on node 36
Recording 22 traces of 1 types on node 10
Recording 22 traces of 1 types on node 28
Recording 25 traces of 1 types on node 22
Recording 27 traces of 1 types on node 14
Recording 28 traces of 1 types on node 12
Recording 26 traces of 1 types on node 26
Recording 22 traces of 1 types on node 13
Recording 26 traces of 1 types on node 20
0.0s

Running simulation for 5000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
  Done; run time = 102002.03 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 13.81 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 958361 (4.96 Hz)
  Simulated time: 5.0 s; 40 workers
  Run time: 102002.03 s
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.000 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.000 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.014 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 0.067 Hz
   L23_BP_bIR : 0.000 Hz
   L23_BP_bNA : 0.143 Hz
   L23_BP_cAC : 0.486 Hz
   L23_BP_cNA : 0.650 Hz
   L23_BP_dST : 0.000 Hz
   L23_BTC_bAC : 0.173 Hz
   L23_BTC_bIR : 0.000 Hz
   L23_BTC_bNA : 0.261 Hz
   L23_BTC_cAC : 0.000 Hz
   L23_BTC_cNA : 0.222 Hz
   L23_ChC_cAC : 0.817 Hz
   L23_ChC_cNA : 0.783 Hz
   L23_ChC_dNA : 0.240 Hz
   L23_DBC_bAC : 0.017 Hz
   L23_DBC_bIR : 0.000 Hz
   L23_DBC_bNA : 0.069 Hz
   L23_DBC_cAC : 0.010 Hz
   L23_LBC_bAC : 0.126 Hz
   L23_LBC_bNA : 5.200 Hz
   L23_LBC_cAC : 0.906 Hz
   L23_LBC_cNA : 1.750 Hz
   L23_LBC_cST : 2.500 Hz
   L23_LBC_dNA : 3.602 Hz
   L23_MC_bAC : 0.000 Hz
   L23_MC_bNA : 0.000 Hz
   L23_MC_cAC : 0.000 Hz
   L23_MC_cNA : 0.000 Hz
   L23_MC_dNA : 0.000 Hz
   L23_NBC_bAC : 0.043 Hz
   L23_NBC_bNA : 1.733 Hz
   L23_NBC_cAC : 0.105 Hz
   L23_NBC_cIR : 0.000 Hz
   L23_NBC_cNA : 0.128 Hz
   L23_NBC_dNA : 0.827 Hz
   L23_NGC_bNA : 0.000 Hz
   L23_NGC_cAC : 0.040 Hz
   L23_NGC_cNA : 0.015 Hz
   L23_NGC_cST : 0.000 Hz
   L23_PC_cAD : 0.364 Hz
   L23_SBC_bNA : 3.600 Hz
   L23_SBC_cAC : 3.107 Hz
   L23_SBC_dNA : 2.291 Hz
   L4_BP_bAC : 0.000 Hz
   L4_BP_bIR : 0.000 Hz
   L4_BP_bNA : 2.300 Hz
   L4_BP_cAC : 0.400 Hz
   L4_BP_cNA : 9.200 Hz
   L4_BP_dST : 0.000 Hz
   L4_BTC_bAC : 2.800 Hz
   L4_BTC_bIR : 0.800 Hz
   L4_BTC_bST : 2.700 Hz
   L4_BTC_cAC : 4.978 Hz
   L4_BTC_cNA : 10.600 Hz
   L4_BTC_dNA : 1.800 Hz
   L4_ChC_cAC : 18.933 Hz
   L4_ChC_cNA : 14.067 Hz
   L4_ChC_dNA : 3.100 Hz
   L4_DBC_bAC : 3.500 Hz
   L4_DBC_bIR : 0.185 Hz
   L4_DBC_bNA : 1.500 Hz
   L4_DBC_bST : 0.050 Hz
   L4_DBC_cAC : 0.700 Hz
   L4_DBC_cIR : 0.343 Hz
   L4_DBC_cNA : 3.550 Hz
   L4_LBC_cAC : 14.018 Hz
   L4_LBC_cNA : 20.143 Hz
   L4_LBC_cST : 15.310 Hz
   L4_LBC_dNA : 23.330 Hz
   L4_LBC_dST : 18.156 Hz
   L4_MC_bAC : 0.000 Hz
   L4_MC_bNA : 0.000 Hz
   L4_MC_cAC : 0.054 Hz
   L4_MC_cNA : 0.000 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 13.920 Hz
   L4_NBC_cIR : 8.880 Hz
   L4_NBC_cNA : 24.987 Hz
   L4_NBC_dNA : 19.533 Hz
   L4_NGC_bNA : 4.800 Hz
   L4_NGC_cAC : 4.400 Hz
   L4_NGC_cNA : 2.933 Hz
   L4_NGC_cST : 0.800 Hz
   L4_PC_cAD : 3.401 Hz
   L4_SBC_bNA : 24.190 Hz
   L4_SBC_cAC : 15.027 Hz
   L4_SBC_dNA : 23.729 Hz
   L4_SP_cAD : 4.326 Hz
   L4_SS_cAD : 4.932 Hz
   L5_BP_bAC : 8.067 Hz
   L5_BP_bIR : 1.400 Hz
   L5_BP_bNA : 15.200 Hz
   L5_BP_cAC : 12.778 Hz
   L5_BP_cNA : 24.800 Hz
   L5_BP_dST : 1.667 Hz
   L5_BTC_bAC : 10.200 Hz
   L5_BTC_cAC : 9.872 Hz
   L5_BTC_cNA : 17.138 Hz
   L5_ChC_cAC : 25.314 Hz
   L5_ChC_cNA : 33.400 Hz
   L5_ChC_dNA : 31.480 Hz
   L5_DBC_bAC : 3.511 Hz
   L5_DBC_bIR : 0.565 Hz
   L5_DBC_bNA : 5.578 Hz
   L5_DBC_bST : 1.778 Hz
   L5_DBC_cAC : 5.689 Hz
   L5_DBC_cIR : 1.129 Hz
   L5_DBC_cNA : 10.222 Hz
   L5_LBC_bAC : 9.683 Hz
   L5_LBC_cAC : 18.712 Hz
   L5_LBC_cIR : 5.477 Hz
   L5_LBC_cNA : 39.476 Hz
   L5_LBC_cST : 30.546 Hz
   L5_LBC_dNA : 36.649 Hz
   L5_LBC_dST : 25.927 Hz
   L5_MC_bAC : 0.272 Hz
   L5_MC_bIR : 0.100 Hz
   L5_MC_bST : 0.013 Hz
   L5_MC_cAC : 1.241 Hz
   L5_MC_cNA : 0.650 Hz
   L5_MC_cST : 0.000 Hz
   L5_MC_dNA : 0.025 Hz
   L5_NBC_bAC : 7.000 Hz
   L5_NBC_bIR : 3.600 Hz
   L5_NBC_bST : 23.215 Hz
   L5_NBC_cAC : 23.355 Hz
   L5_NBC_cIR : 12.729 Hz
   L5_NBC_cNA : 33.118 Hz
   L5_NBC_cST : 24.515 Hz
   L5_NBC_dST : 28.708 Hz
   L5_NGC_bNA : 10.200 Hz
   L5_NGC_cAC : 13.200 Hz
   L5_NGC_cNA : 22.920 Hz
   L5_NGC_cST : 0.800 Hz
   L5_SBC_bNA : 21.356 Hz
   L5_SBC_cAC : 14.311 Hz
   L5_SBC_dNA : 44.543 Hz
   L5_STPC_cAD : 7.142 Hz
   L5_TTPC1_cAD : 7.317 Hz
   L5_TTPC2_cAD : 7.616 Hz
   L5_UTPC_cAD : 9.882 Hz
   L6_BPC_cAD : 4.682 Hz
   L6_BP_bAC : 6.533 Hz
   L6_BP_bIR : 1.140 Hz
   L6_BP_bNA : 13.432 Hz
   L6_BP_cAC : 12.053 Hz
   L6_BP_cNA : 20.560 Hz
   L6_BP_dST : 0.833 Hz
   L6_BTC_bAC : 6.540 Hz
   L6_BTC_cAC : 11.124 Hz
   L6_BTC_cNA : 20.580 Hz
   L6_ChC_cAC : 18.067 Hz
   L6_ChC_cNA : 48.900 Hz
   L6_ChC_dNA : 27.100 Hz
   L6_DBC_bAC : 8.000 Hz
   L6_DBC_bIR : 1.240 Hz
   L6_DBC_bNA : 7.067 Hz
   L6_DBC_bST : 3.267 Hz
   L6_DBC_cAC : 9.733 Hz
   L6_DBC_cIR : 2.900 Hz
   L6_DBC_cNA : 5.933 Hz
   L6_IPC_cAD : 4.397 Hz
   L6_LBC_bAC : 6.729 Hz
   L6_LBC_bIR : 3.954 Hz
   L6_LBC_bNA : 54.260 Hz
   L6_LBC_bST : 28.427 Hz
   L6_LBC_cNA : 43.881 Hz
   L6_LBC_cST : 24.163 Hz
   L6_MC_bAC : 0.190 Hz
   L6_MC_bIR : 0.026 Hz
   L6_MC_bNA : 0.757 Hz
   L6_MC_bST : 0.029 Hz
   L6_MC_cAC : 1.400 Hz
   L6_MC_cIR : 0.000 Hz
   L6_MC_cNA : 0.814 Hz
   L6_NBC_bAC : 7.171 Hz
   L6_NBC_bIR : 4.786 Hz
   L6_NBC_bST : 33.178 Hz
   L6_NBC_cAC : 14.179 Hz
   L6_NBC_cIR : 6.957 Hz
   L6_NBC_cNA : 30.778 Hz
   L6_NBC_cST : 26.697 Hz
   L6_NBC_dST : 31.700 Hz
   L6_NGC_bNA : 14.400 Hz
   L6_NGC_cAC : 12.800 Hz
   L6_NGC_cNA : 22.891 Hz
   L6_NGC_cST : 1.500 Hz
   L6_SBC_bNA : 41.233 Hz
   L6_SBC_cAC : 23.833 Hz
   L6_SBC_dNA : 27.011 Hz
   L6_TPC_L1_cAD : 4.741 Hz
   L6_TPC_L4_cAD : 5.638 Hz
   L6_UTPC_cAD : 6.018 Hz
   ss_RTN_o : 8.022 Hz
   ss_RTN_m : 9.771 Hz
   ss_RTN_i : 9.838 Hz
   VPL_sTC : 1.765 Hz
   VPM_sTC : 2.377 Hz
   POm_sTC_s1 : 3.536 Hz
Saving output as ../data/v6_batch0/v6_batch0_0_0.json  ... 
Finished saving!
  Done; saving time = 82.00 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 2888.35 s

Total time = 121243.29 s

End time:  2021-11-22 13:22:23.186391
