numprocs=160

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v4_batch0/v4_batch0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py

Start time:  2021-01-22 13:11:55.849912
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py
Importing netParams from ../data/v4_batch0/v4_batch0_netParams.py

Creating network of 55 cell populations on 160 hosts...
  Number of cells on node 119: 196 
  Number of cells on node 128: 196 
  Number of cells on node 83: 196 
  Number of cells on node 5: 196 
  Number of cells on node 109: 196 
  Number of cells on node 46: 196 
  Number of cells on node 68: 196 
  Number of cells on node 141: 196 
  Number of cells on node 42: 196 
  Number of cells on node 126: 196 
  Number of cells on node 129: 196 
  Number of cells on node 71: 196 
  Number of cells on node 10: 196 
  Number of cells on node 120: 196 
  Number of cells on node 85: 196 
  Number of cells on node 97: 196 
  Number of cells on node 80: 196 
  Number of cells on node 135: 196 
  Number of cells on node 13: 196 
  Number of cells on node 95: 196 
  Number of cells on node 24: 196 
  Number of cells on node 14: 196 
  Number of cells on node 154: 195 
  Number of cells on node 22: 196 
  Number of cells on node 130: 196 
  Number of cells on node 33: 196 
  Number of cells on node 115: 196 
  Number of cells on node 52: 196 
  Number of cells on node 40: 196 
  Number of cells on node 34: 196 
  Number of cells on node 18: 196 
  Number of cells on node 8: 196 
  Number of cells on node 131: 196 
  Number of cells on node 73: 196 
  Number of cells on node 122: 196 
  Number of cells on node 29: 196 
  Number of cells on node 124: 196 
  Number of cells on node 113: 196 
  Number of cells on node 31: 196 
  Number of cells on node 151: 195 
  Number of cells on node 91: 196 
  Number of cells on node 37: 196 
  Number of cells on node 32: 196 
  Number of cells on node 104: 196 
  Number of cells on node 27: 196 
  Number of cells on node 96: 196 
  Number of cells on node 145: 196 
  Number of cells on node 147: 195 
  Number of cells on node 159: 195 
  Number of cells on node 16: 196 
  Number of cells on node 53: 196 
  Number of cells on node 133: 196 
  Number of cells on node 137: 196 
  Number of cells on node 127: 196 
  Number of cells on node 139: 196 
  Number of cells on node 50: 196 
  Number of cells on node 148: 195 
  Number of cells on node 35: 196 
  Number of cells on node 57: 196 
  Number of cells on node 102: 196 
  Number of cells on node 157: 195 
  Number of cells on node 7: 196 
  Number of cells on node 140: 196 
  Number of cells on node 142: 196 
  Number of cells on node 6: 196 
  Number of cells on node 51: 196 
  Number of cells on node 25: 196 
  Number of cells on node 26: 196 
  Number of cells on node 103: 196 
  Number of cells on node 81: 196 
  Number of cells on node 30: 196 
  Number of cells on node 150: 195 
  Number of cells on node 23: 196 
  Number of cells on node 82: 196 
  Number of cells on node 11: 196 
  Number of cells on node 94: 196 
  Number of cells on node 28: 196 
  Number of cells on node 134: 196 
  Number of cells on node 155: 195 
  Number of cells on node 101: 196 
  Number of cells on node 153: 195 
  Number of cells on node 88: 196 
  Number of cells on node 21: 196 
  Number of cells on node 59: 196 
  Number of cells on node 74: 196 
  Number of cells on node 62: 196 
  Number of cells on node 60: 196 
  Number of cells on node 99: 196 
  Number of cells on node 93: 196 
  Number of cells on node 61: 196 
  Number of cells on node 112: 196 
  Number of cells on node 116: 196 
  Number of cells on node 49: 196 
  Number of cells on node 143: 196 
  Number of cells on node 132: 196 
  Number of cells on node 86: 196 
  Number of cells on node 144: 196 
  Number of cells on node 48: 196 
  Number of cells on node 117: 196 
  Number of cells on node 87: 196 
  Number of cells on node 47: 196 
  Number of cells on node 79: 196 
  Number of cells on node 72: 196 
  Number of cells on node 0: 196 
  Done; cell creation time = 17.94 s.
Making connections...
  Number of cells on node 78: 196 
  Number of cells on node 66: 196 
  Number of cells on node 106: 196 
  Number of cells on node 55: 196 
  Number of cells on node 38: 196 
  Number of cells on node 63: 196 
  Number of cells on node 138: 196 
  Number of cells on node 75: 196 
  Number of cells on node 64: 196 
  Number of cells on node 158: 195 
  Number of cells on node 110: 196 
  Number of cells on node 76: 196 
  Number of cells on node 20: 196 
  Number of cells on node 2: 196 
  Number of cells on node 12: 196 
  Number of cells on node 58: 196 
  Number of cells on node 152: 195 
  Number of cells on node 123: 196 
  Number of cells on node 39: 196 
  Number of cells on node 69: 196 
  Number of cells on node 15: 196 
  Number of cells on node 89: 196 
  Number of cells on node 156: 195 
  Number of cells on node 36: 196 
  Number of cells on node 65: 196 
  Number of cells on node 90: 196 
  Number of cells on node 54: 196 
  Number of cells on node 92: 196 
  Number of cells on node 136: 196 
  Number of cells on node 77: 196 
  Number of cells on node 56: 196 
  Number of cells on node 146: 195 
  Number of cells on node 125: 196 
  Number of cells on node 44: 196 
  Number of cells on node 121: 196 
  Number of cells on node 100: 196 
  Number of cells on node 114: 196 
  Number of cells on node 111: 196 
  Number of cells on node 149: 195 
  Number of cells on node 107: 196 
  Number of cells on node 108: 196 
  Number of cells on node 84: 196 
  Number of cells on node 3: 196 
  Number of cells on node 98: 196 
  Number of cells on node 45: 196 
  Number of cells on node 67: 196 
  Number of cells on node 17: 196 
  Number of cells on node 9: 196 
  Number of cells on node 41: 196 
  Number of cells on node 4: 196 
  Number of cells on node 19: 196 
  Number of cells on node 118: 196 
  Number of cells on node 1: 196 
  Number of cells on node 43: 196 
  Number of cells on node 105: 196 
  Number of cells on node 70: 196 
  Number of connections on node 73: 49002 
  Number of synaptic contacts on node 73: 458030 
  Number of connections on node 54: 49147 
  Number of synaptic contacts on node 54: 454468 
  Number of connections on node 147: 50021 
  Number of synaptic contacts on node 147: 465994 
  Number of connections on node 82: 50224 
  Number of synaptic contacts on node 82: 469348 
  Number of connections on node 14: 50572 
  Number of synaptic contacts on node 14: 470630 
  Number of connections on node 21: 50377 
  Number of synaptic contacts on node 21: 472286 
  Number of connections on node 119: 48584 
  Number of synaptic contacts on node 119: 454372 
  Number of connections on node 153: 52502 
  Number of synaptic contacts on node 153: 488196 
  Number of connections on node 74: 49455 
  Number of synaptic contacts on node 74: 457718 
  Number of connections on node 139: 51076 
  Number of synaptic contacts on node 139: 474448 
  Number of connections on node 31: 49807 
  Number of synaptic contacts on node 31: 466240 
  Number of connections on node 35: 50617 
  Number of synaptic contacts on node 35: 474910 
  Number of connections on node 149: 50854 
  Number of synaptic contacts on node 149: 467904 
  Number of connections on node 112: 49687 
  Number of synaptic contacts on node 112: 464274 
  Number of connections on node 13: 50805 
  Number of synaptic contacts on node 13: 473984 
  Number of connections on node 118: 50812 
  Number of synaptic contacts on node 118: 471184 
  Number of connections on node 1: 51065 
  Number of synaptic contacts on node 1: 475324 
  Number of connections on node 60: 50806 
  Number of synaptic contacts on node 60: 474194 
  Number of connections on node 27: 50163 
  Number of synaptic contacts on node 27: 462446 
  Number of connections on node 50: 49069 
  Number of synaptic contacts on node 50: 455572 
  Number of connections on node 78: 51372 
  Number of synaptic contacts on node 78: 475042 
  Number of connections on node 115: 50080 
  Number of synaptic contacts on node 115: 469428 
  Number of connections on node 36: 50410 
  Number of synaptic contacts on node 36: 467570 
  Number of connections on node 116: 50638 
  Number of synaptic contacts on node 116: 474392 
  Number of connections on node 95: 50311 
  Number of synaptic contacts on node 95: 466738 
  Number of connections on node 151: 50748 
  Number of synaptic contacts on node 151: 476584 
  Number of connections on node 2: 50362 
  Number of synaptic contacts on node 2: 466886 
  Number of connections on node 134: 51637 
  Number of synaptic contacts on node 134: 478950 
  Number of connections on node 37: 50494 
  Number of synaptic contacts on node 37: 470294 
  Number of connections on node 55: 49458 
  Number of synaptic contacts on node 55: 461612 
  Number of connections on node 146: 50267 
  Number of synaptic contacts on node 146: 473726 
  Number of connections on node 130: 50264 
  Number of synaptic contacts on node 130: 468322 
  Number of connections on node 106: 49464 
  Number of synaptic contacts on node 106: 458744 
  Number of connections on node 34: 50046 
  Number of synaptic contacts on node 34: 463318 
  Number of connections on node 136: 51219 
  Number of synaptic contacts on node 136: 475892 
  Number of connections on node 141: 50913 
  Number of synaptic contacts on node 141: 471596 
  Number of connections on node 11: 51062 
  Number of synaptic contacts on node 11: 476664 
  Number of connections on node 85: 49795 
  Number of synaptic contacts on node 85: 463454 
  Number of connections on node 71: 50983 
  Number of synaptic contacts on node 71: 475528 
  Number of connections on node 10: 49612 
  Number of synaptic contacts on node 10: 464608 
  Number of connections on node 131: 49545 
  Number of synaptic contacts on node 131: 467388 
  Number of connections on node 100: 50127 
  Number of synaptic contacts on node 100: 462032 
  Number of connections on node 44: 49831 
  Number of synaptic contacts on node 44: 462588 
  Number of connections on node 76: 52057 
  Number of synaptic contacts on node 76: 488384 
  Number of connections on node 120: 50221 
  Number of synaptic contacts on node 120: 467450 
  Number of connections on node 32: 50056 
  Number of synaptic contacts on node 32: 465316 
  Number of connections on node 101: 51180 
  Number of synaptic contacts on node 101: 476064 
  Number of connections on node 5: 51607 
  Number of synaptic contacts on node 5: 484248 
  Number of connections on node 86: 49937 
  Number of synaptic contacts on node 86: 464692 
  Number of connections on node 114: 51051 
  Number of synaptic contacts on node 114: 472460 
  Number of connections on node 133: 50862 
  Number of synaptic contacts on node 133: 475362 
  Number of connections on node 42: 50073 
  Number of synaptic contacts on node 42: 462740 
  Number of connections on node 45: 50876 
  Number of synaptic contacts on node 45: 480320 
  Number of connections on node 128: 49886 
  Number of synaptic contacts on node 128: 464506 
  Number of connections on node 49: 48504 
  Number of synaptic contacts on node 49: 453316 
  Number of connections on node 9: 48241 
  Number of synaptic contacts on node 9: 451582 
  Number of connections on node 99: 51039 
  Number of synaptic contacts on node 99: 475860 
  Number of connections on node 64: 49210 
  Number of synaptic contacts on node 64: 456016 
  Number of connections on node 150: 49980 
  Number of synaptic contacts on node 150: 470064 
  Number of connections on node 79: 48483 
  Number of synaptic contacts on node 79: 448060 
  Number of connections on node 0: 52824 
  Number of synaptic contacts on node 0: 489952 
  Number of connections on node 138: 49834 
  Number of synaptic contacts on node 138: 463958 
  Number of connections on node 16: 49093 
  Number of synaptic contacts on node 16: 456896 
  Number of connections on node 15: 50350 
  Number of synaptic contacts on node 15: 468754 
  Number of connections on node 40: 50569 
  Number of synaptic contacts on node 40: 470642 
  Number of connections on node 89: 50699 
  Number of synaptic contacts on node 89: 474598 
  Number of connections on node 117: 49531 
  Number of synaptic contacts on node 117: 459664 
  Number of connections on node 28: 50169 
  Number of synaptic contacts on node 28: 471184 
  Number of connections on node 24: 51495 
  Number of synaptic contacts on node 24: 478964 
  Number of connections on node 125: 49107 
  Number of synaptic contacts on node 125: 454914 
  Number of connections on node 92: 50644 
  Number of synaptic contacts on node 92: 471096 
  Number of connections on node 88: 50648 
  Number of synaptic contacts on node 88: 470750 
  Number of connections on node 158: 50360 
  Number of synaptic contacts on node 158: 469274 
  Number of connections on node 159: 49473 
  Number of synaptic contacts on node 159: 463732 
  Number of connections on node 81: 49603 
  Number of synaptic contacts on node 81: 463298 
  Number of connections on node 30: 50938 
  Number of synaptic contacts on node 30: 469686 
  Number of connections on node 61: 49645 
  Number of synaptic contacts on node 61: 464302 
  Number of connections on node 43: 49817 
  Number of synaptic contacts on node 43: 465066 
  Number of connections on node 6: 50893 
  Number of synaptic contacts on node 6: 476080 
  Number of connections on node 121: 50793 
  Number of synaptic contacts on node 121: 475356 
  Number of connections on node 132: 50810 
  Number of synaptic contacts on node 132: 472234 
  Number of connections on node 70: 49383 
  Number of synaptic contacts on node 70: 459592 
  Number of connections on node 75: 50085 
  Number of synaptic contacts on node 75: 465412 
  Number of connections on node 94: 48790 
  Number of synaptic contacts on node 94: 454300 
  Number of connections on node 65: 49897 
  Number of synaptic contacts on node 65: 462354 
  Number of connections on node 129: 49882 
  Number of synaptic contacts on node 129: 466994 
  Number of connections on node 87: 49730 
  Number of synaptic contacts on node 87: 462152 
  Number of connections on node 26: 49633 
  Number of synaptic contacts on node 26: 461522 
  Number of connections on node 105: 50558 
  Number of synaptic contacts on node 105: 472140 
  Number of connections on node 145: 51462 
  Number of synaptic contacts on node 145: 480224 
  Number of connections on node 143: 50552 
  Number of synaptic contacts on node 143: 465638 
  Number of connections on node 148: 49415 
  Number of synaptic contacts on node 148: 462922 
  Number of connections on node 62: 49984 
  Number of synaptic contacts on node 62: 465376 
  Number of connections on node 155: 49960 
  Number of synaptic contacts on node 155: 466604 
  Number of connections on node 96: 48437 
  Number of synaptic contacts on node 96: 448822 
  Number of connections on node 22: 49629 
  Number of synaptic contacts on node 22: 464814 
  Number of connections on node 72: 50132 
  Number of synaptic contacts on node 72: 465544 
  Number of connections on node 47: 49910 
  Number of synaptic contacts on node 47: 469100 
  Number of connections on node 122: 50752 
  Number of synaptic contacts on node 122: 476572 
  Number of connections on node 152: 50474 
  Number of synaptic contacts on node 152: 464538 
  Number of connections on node 111: 51572 
  Number of synaptic contacts on node 111: 478178 
  Number of connections on node 98: 49319 
  Number of synaptic contacts on node 98: 459516 
  Number of connections on node 109: 50003 
  Number of synaptic contacts on node 109: 461012 
  Number of connections on node 29: 48884 
  Number of synaptic contacts on node 29: 456124 
  Number of connections on node 33: 51967 
  Number of synaptic contacts on node 33: 484150 
  Number of connections on node 107: 49258 
  Number of synaptic contacts on node 107: 461746 
  Number of connections on node 20: 50937 
  Number of synaptic contacts on node 20: 478042 
  Number of connections on node 135: 50556 
  Number of synaptic contacts on node 135: 466516 
  Number of connections on node 80: 49161 
  Number of synaptic contacts on node 80: 460314 
  Number of connections on node 144: 50264 
  Number of synaptic contacts on node 144: 469370 
  Number of connections on node 51: 49481 
  Number of synaptic contacts on node 51: 457696 
  Number of connections on node 142: 50510 
  Number of synaptic contacts on node 142: 467350 
  Number of connections on node 7: 50466 
  Number of synaptic contacts on node 7: 467888 
  Number of connections on node 46: 49519 
  Number of synaptic contacts on node 46: 461846 
  Number of connections on node 93: 49892 
  Number of synaptic contacts on node 93: 460300 
  Number of connections on node 83: 50026 
  Number of synaptic contacts on node 83: 460810 
  Number of connections on node 25: 49522 
  Number of synaptic contacts on node 25: 463600 
  Number of connections on node 91: 49094 
  Number of synaptic contacts on node 91: 455840 
  Number of connections on node 38: 50164 
  Number of synaptic contacts on node 38: 471392 
  Number of connections on node 154: 49228 
  Number of synaptic contacts on node 154: 456936 
  Number of connections on node 18: 50932 
  Number of synaptic contacts on node 18: 476144 
  Number of connections on node 48: 50473 
  Number of synaptic contacts on node 48: 469072 
  Number of connections on node 137: 48847 
  Number of synaptic contacts on node 137: 455352 
  Number of connections on node 103: 49285 
  Number of synaptic contacts on node 103: 458112 
  Number of connections on node 90: 49926 
  Number of synaptic contacts on node 90: 461076 
  Number of connections on node 110: 49223 
  Number of synaptic contacts on node 110: 462716 
  Number of connections on node 59: 50165 
  Number of synaptic contacts on node 59: 465050 
  Number of connections on node 12: 50757 
  Number of synaptic contacts on node 12: 474842 
  Number of connections on node 140: 52507 
  Number of synaptic contacts on node 140: 492448 
  Number of connections on node 69: 50512 
  Number of synaptic contacts on node 69: 461946 
  Number of connections on node 104: 50557 
  Number of synaptic contacts on node 104: 470230 
  Number of connections on node 39: 49712 
  Number of synaptic contacts on node 39: 462708 
  Number of connections on node 156: 50959 
  Number of synaptic contacts on node 156: 478722 
  Number of connections on node 126: 50887 
  Number of synaptic contacts on node 126: 480060 
  Number of connections on node 8: 50785 
  Number of synaptic contacts on node 8: 470292 
  Number of connections on node 157: 50613 
  Number of synaptic contacts on node 157: 471930 
  Number of connections on node 108: 50138 
  Number of synaptic contacts on node 108: 466030 
  Number of connections on node 58: 50181 
  Number of synaptic contacts on node 58: 465118 
  Number of connections on node 67: 52072 
  Number of synaptic contacts on node 67: 491706 
  Number of connections on node 56: 51469 
  Number of synaptic contacts on node 56: 478402 
  Number of connections on node 4: 49904 
  Number of synaptic contacts on node 4: 469862 
  Number of connections on node 102: 50854 
  Number of synaptic contacts on node 102: 471452 
  Number of connections on node 17: 51442 
  Number of synaptic contacts on node 17: 481366 
  Number of connections on node 84: 49282 
  Number of synaptic contacts on node 84: 460562 
  Number of connections on node 124: 49831 
  Number of synaptic contacts on node 124: 465374 
  Number of connections on node 127: 50573 
  Number of synaptic contacts on node 127: 471956 
  Number of connections on node 66: 50472 
  Number of synaptic contacts on node 66: 472178 
  Number of connections on node 57: 50509 
  Number of synaptic contacts on node 57: 469738 
  Number of connections on node 97: 48891 
  Number of synaptic contacts on node 97: 451878 
  Number of connections on node 23: 50455 
  Number of synaptic contacts on node 23: 468506 
  Number of connections on node 113: 49674 
  Number of synaptic contacts on node 113: 459778 
  Number of connections on node 41: 50281 
  Number of synaptic contacts on node 41: 468324 
  Number of connections on node 53: 49009 
  Number of synaptic contacts on node 53: 452972 
  Number of connections on node 52: 48953 
  Number of synaptic contacts on node 52: 449458 
  Number of connections on node 63: 49288 
  Number of synaptic contacts on node 63: 460564 
  Number of connections on node 68: 49829 
  Number of synaptic contacts on node 68: 463378 
  Number of connections on node 77: 49944 
  Number of synaptic contacts on node 77: 464010 
  Number of connections on node 19: 50609 
  Number of synaptic contacts on node 19: 473822 
  Number of connections on node 3: 52324 
  Number of synaptic contacts on node 3: 492314 
  Number of connections on node 123: 50884 
  Number of synaptic contacts on node 123: 470430 
  Done; cell connection time = 20807.70 s.
Adding stims...
  Number of stims on node 129: 392 
  Number of stims on node 11: 392 
  Number of stims on node 97: 392 
  Number of stims on node 25: 392 
  Number of stims on node 77: 392 
  Number of stims on node 89: 392 
  Number of stims on node 13: 392 
  Number of stims on node 143: 392 
  Number of stims on node 58: 392 
  Number of stims on node 7: 392 
  Number of stims on node 94: 392 
  Number of stims on node 133: 392 
  Number of stims on node 43: 392 
  Number of stims on node 31: 392 
  Number of stims on node 119: 392 
  Number of stims on node 149: 390 
  Number of stims on node 56: 392 
  Number of stims on node 4: 392 
  Number of stims on node 27: 392 
  Number of stims on node 32: 392 
  Number of stims on node 132: 392 
  Number of stims on node 125: 392 
  Number of stims on node 3: 392 
  Number of stims on node 155: 390 
  Number of stims on node 87: 392 
  Number of stims on node 100: 392 
  Number of stims on node 150: 390 
  Number of stims on node 69: 392 
  Number of stims on node 18: 392 
  Number of stims on node 68: 392 
  Number of stims on node 15: 392 
  Number of stims on node 111: 392 
  Number of stims on node 139: 392 
  Number of stims on node 134: 392 
  Number of stims on node 57: 392 
  Number of stims on node 71: 392 
  Number of stims on node 38: 392 
  Number of stims on node 110: 392 
  Number of stims on node 91: 392 
  Number of stims on node 95: 392 
  Number of stims on node 46: 392 
  Number of stims on node 66: 392 
  Number of stims on node 14: 392 
  Number of stims on node 16: 392 
  Number of stims on node 75: 392 
  Number of stims on node 79: 392 
  Number of stims on node 22: 392 
  Number of stims on node 145: 392 
  Number of stims on node 29: 392 
  Number of stims on node 61: 392 
  Number of stims on node 54: 392 
  Number of stims on node 140: 392 
  Number of stims on node 90: 392 
  Number of stims on node 45: 392 
  Number of stims on node 67: 392 
  Number of stims on node 152: 390 
  Number of stims on node 138: 392 
  Number of stims on node 1: 392 
  Number of stims on node 92: 392 
  Number of stims on node 42: 392 
  Number of stims on node 5: 392 
  Number of stims on node 141: 392 
  Number of stims on node 2: 392 
  Number of stims on node 128: 392 
  Number of stims on node 70: 392 
  Number of stims on node 157: 390 
  Number of stims on node 112: 392 
  Number of stims on node 65: 392 
  Number of stims on node 51: 392 
  Number of stims on node 81: 392 
  Number of stims on node 74: 392 
  Number of stims on node 20: 392 
  Number of stims on node 9: 392 
  Number of stims on node 73: 392 
  Number of stims on node 0: 392 
  Number of stims on node 34: 392 
  Number of stims on node 154: 390 
  Number of stims on node 114: 392 
  Number of stims on node 44: 392 
  Number of stims on node 49: 392 
  Number of stims on node 50: 392 
  Number of stims on node 137: 392 
  Number of stims on node 82: 392 
  Number of stims on node 158: 390 
  Number of stims on node 151: 390 
  Number of stims on node 131: 392 
  Number of stims on node 21: 392 
  Number of stims on node 99: 392 
  Number of stims on node 48: 392 
  Number of stims on node 148: 390 
  Number of stims on node 23: 392 
  Number of stims on node 63: 392 
  Number of stims on node 10: 392 
  Number of stims on node 144: 392 
  Number of stims on node 115: 392 
  Number of stims on node 156: 390 
  Number of stims on node 98: 392 
  Number of stims on node 80: 392 
  Number of stims on node 52: 392 
  Number of stims on node 86: 392 
  Number of stims on node 146: 390 
  Number of stims on node 123: 392 
  Number of stims on node 40: 392 
  Number of stims on node 85: 392 
  Number of stims on node 101: 392 
  Number of stims on node 104: 392 
  Number of stims on node 41: 392 
  Number of stims on node 24: 392 
  Number of stims on node 33: 392 
  Number of stims on node 39: 392 
  Number of stims on node 121: 392 
  Number of stims on node 103: 392 
  Number of stims on node 118: 392 
  Number of stims on node 84: 392 
  Number of stims on node 93: 392 
  Number of stims on node 96: 392 
  Number of stims on node 109: 392 
  Number of stims on node 35: 392 
  Number of stims on node 106: 392 
  Number of stims on node 60: 392 
  Number of stims on node 105: 392 
  Number of stims on node 78: 392 
  Number of stims on node 147: 390 
  Number of stims on node 64: 392 
  Number of stims on node 36: 392 
  Number of stims on node 124: 392 
  Number of stims on node 30: 392 
  Number of stims on node 116: 392 
  Number of stims on node 55: 392 
  Number of stims on node 17: 392 
  Number of stims on node 26: 392 
  Number of stims on node 108: 392 
  Number of stims on node 153: 390 
  Number of stims on node 107: 392 
  Number of stims on node 8: 392 
  Number of stims on node 53: 392 
  Number of stims on node 120: 392 
  Number of stims on node 122: 392 
  Number of stims on node 113: 392 
  Number of stims on node 76: 392 
  Number of stims on node 135: 392 
  Number of stims on node 19: 392 
  Number of stims on node 12: 392 
  Number of stims on node 88: 392 
  Number of stims on node 102: 392 
  Number of stims on node 62: 392 
  Number of stims on node 59: 392 
  Number of stims on node 47: 392 
  Number of stims on node 28: 392 
  Number of stims on node 136: 392 
  Number of stims on node 142: 392 
  Number of stims on node 72: 392 
  Number of stims on node 127: 392 
  Number of stims on node 130: 392 
  Number of stims on node 83: 392 
  Number of stims on node 117: 392 
  Number of stims on node 159: 390 
  Number of stims on node 126: 392 
  Number of stims on node 37: 392 
  Done; cell stims creation time = 5.92 s.
  Number of stims on node 6: 392 
Recording 1 traces of 1 types on node 82
Recording 0 traces of 0 types on node 125
Recording 1 traces of 1 types on node 57
Recording 0 traces of 0 types on node 119
Recording 0 traces of 0 types on node 155
Recording 2 traces of 1 types on node 72
Recording 0 traces of 0 types on node 44
Recording 0 traces of 0 types on node 147
Recording 0 traces of 0 types on node 32
Recording 0 traces of 0 types on node 139
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 43
Recording 0 traces of 0 types on node 89
Recording 0 traces of 0 types on node 149
Recording 0 traces of 0 types on node 31
Recording 1 traces of 1 types on node 60
Recording 0 traces of 0 types on node 100
Recording 0 traces of 0 types on node 154
Recording 1 traces of 1 types on node 7
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 79
Recording 1 traces of 1 types on node 51
Recording 0 traces of 0 types on node 24
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 143
Recording 0 traces of 0 types on node 61
Recording 1 traces of 1 types on node 117
Recording 0 traces of 0 types on node 135
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 48
Recording 0 traces of 0 types on node 99
Recording 0 traces of 0 types on node 94
Recording 1 traces of 1 types on node 66
Recording 0 traces of 0 types on node 129
Recording 0 traces of 0 types on node 49
Recording 0 traces of 0 types on node 133
Recording 2 traces of 1 types on node 13
Recording 0 traces of 0 types on node 56
Recording 0 traces of 0 types on node 87
Recording 0 traces of 0 types on node 93
Recording 1 traces of 1 types on node 127
Recording 1 traces of 1 types on node 74
Recording 0 traces of 0 types on node 35
Recording 0 traces of 0 types on node 151
Recording 1 traces of 1 types on node 3
Recording 1 traces of 1 types on node 116
Recording 0 traces of 0 types on node 71
Recording 0 traces of 0 types on node 92
Recording 0 traces of 0 types on node 152
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 144
Recording 0 traces of 0 types on node 80
Recording 0 traces of 0 types on node 95
Recording 0 traces of 0 types on node 45
Recording 1 traces of 1 types on node 137
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 107
Recording 0 traces of 0 types on node 53
Recording 0 traces of 0 types on node 21
Recording 1 traces of 1 types on node 0
Recording 0 traces of 0 types on node 91
Recording 0 traces of 0 types on node 115
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 106
Recording 0 traces of 0 types on node 136
Recording 0 traces of 0 types on node 90
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 20
Recording 2 traces of 1 types on node 46
Recording 0 traces of 0 types on node 97
Recording 0 traces of 0 types on node 65
Recording 3 traces of 1 types on node 50
Recording 1 traces of 1 types on node 142
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 118
Recording 1 traces of 1 types on node 38
Recording 1 traces of 1 types on node 16
Recording 0 traces of 0 types on node 39
Recording 0 traces of 0 types on node 105
Recording 0 traces of 0 types on node 63
Recording 1 traces of 1 types on node 59
Recording 0 traces of 0 types on node 140
Recording 1 traces of 1 types on node 85
Recording 0 traces of 0 types on node 157
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 110
Recording 0 traces of 0 types on node 111
Recording 0 traces of 0 types on node 62
Recording 1 traces of 1 types on node 153
Recording 0 traces of 0 types on node 101
Recording 0 traces of 0 types on node 52
Recording 1 traces of 1 types on node 103
Recording 0 traces of 0 types on node 75
Recording 0 traces of 0 types on node 81
Recording 0 traces of 0 types on node 102
Recording 0 traces of 0 types on node 104
Recording 0 traces of 0 types on node 159
Recording 0 traces of 0 types on node 123
Recording 0 traces of 0 types on node 41
Recording 0 traces of 0 types on node 96
Recording 0 traces of 0 types on node 78
Recording 2 traces of 1 types on node 58
Recording 0 traces of 0 types on node 36
Recording 0 traces of 0 types on node 64
Recording 1 traces of 1 types on node 114
Recording 0 traces of 0 types on node 131
Recording 0 traces of 0 types on node 84
Recording 1 traces of 1 types on node 67
Recording 0 traces of 0 types on node 128
Recording 0 traces of 0 types on node 138
Recording 1 traces of 1 types on node 112
Recording 1 traces of 1 types on node 30
Recording 0 traces of 0 types on node 76
Recording 2 traces of 1 types on node 134
Recording 1 traces of 1 types on node 68
Recording 2 traces of 1 types on node 11
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 37
Recording 0 traces of 0 types on node 47
Recording 0 traces of 0 types on node 54
Recording 1 traces of 1 types on node 98
Recording 0 traces of 0 types on node 40
Recording 1 traces of 1 types on node 124
Recording 1 traces of 1 types on node 12
Recording 0 traces of 0 types on node 28
Recording 1 traces of 1 types on node 55
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 69
Recording 1 traces of 1 types on node 10
Recording 0 traces of 0 types on node 121
Recording 0 traces of 0 types on node 88
Recording 0 traces of 0 types on node 146
Recording 0 traces of 0 types on node 73
Recording 0 traces of 0 types on node 33
Recording 1 traces of 1 types on node 148
Recording 0 traces of 0 types on node 158
Recording 1 traces of 1 types on node 109
Recording 0 traces of 0 types on node 34
Recording 0 traces of 0 types on node 126
Recording 0 traces of 0 types on node 122
Recording 1 traces of 1 types on node 156
Recording 0 traces of 0 types on node 8
Recording 1 traces of 1 types on node 22
Recording 1 traces of 1 types on node 120
Recording 1 traces of 1 types on node 42
Recording 0 traces of 0 types on node 145
Recording 0 traces of 0 types on node 108
Recording 0 traces of 0 types on node 141
Recording 1 traces of 1 types on node 26
Recording 0 traces of 0 types on node 132
Recording 2 traces of 1 types on node 18
Recording 0 traces of 0 types on node 70
Recording 0 traces of 0 types on node 77
Recording 0 traces of 0 types on node 130
Recording 0 traces of 0 types on node 83
Recording 0 traces of 0 types on node 27
Recording 1 traces of 1 types on node 150
Recording 0 traces of 0 types on node 113
Recording 0 traces of 0 types on node 86
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 16754.08 s; real-time ratio: 0.00.
Saving output as ../data/v4_batch0/v4_batch0_030.pkl ... 

  Done; saving time = 0.28 s.

Gathering data...
  Gathering only sim data...
  Done; gather time = 9.38 s.

Analyzing...
  Cells: 196
  Connections: 0 (0.00 per cell)
  Spikes: 70770 (180.54 Hz)
  Simulated time: 2.0 s; 160 workers
  Run time: 16754.08 s
Plotting raster...
  Done; plotting time = 2.08 s

Total time = 37625.28 s

End time:  2021-01-22 23:39:01.131822
